### ISSUE TITLE
faille de sécurité : base de donnée téléchargeable

### ISSUE THREAD

**Issue by thib3113** [ldleman/yana-server#100]
Bonjour, la base de donnée est téléchargeable depuis le serveur web !
En vous rendant à l'adresse http://your-raspberry/yana-server/db/.database.db, le fichier database.db se lance au téléchargement, et est lisible

**Comment by ldleman** [comment]
le soucis c'est que www-data doit avoir les droits sur ce fichier pour que php puisse le consulter, hors  si www-data a l'accès, le serveur http donnera luis aussi cet accès au fichier

**Comment by Freeflod** [comment]
Je lance yana-server avec NGINX qui gère le .htaccess
Quand je vérifie dans le rep. je ne vois pas de .htaccess.
Que puis-je mettre dedans ?
