### ISSUE TITLE
bug de l'installeur

### ISSUE THREAD

**Issue by thib3113** [ldleman/yana-server#103]
je ne suis pas sur mais : 
```shell
/////////////////////
LAZASS INSTALLER 1.8-FR-SA-AB-UN par Sarrailh Remi - Gplv3
__________________________________
__________________________________
Installation de LIGHTTPD (serveur web) Whhaouuhh !
__________________________________
__________________________________
./install.sh: ligne483: install_webserver : commande introuvable
```

ça semble pas être une bonne chose

**Comment by ldleman** [comment]
Le bug est il toujours présent ? Tu peux donner un peu de plus de détails ?

**Comment by maditnerd** [comment]
Effectivement la ligne 483 renvoie à une fonction qui n'existe pas, à priori j'ai du vouloir créer une fonction pour installer le serveur web puis je me suis rendu compte que faire une fonction pour juste faire ``` apt-get install lighttpd ``` c'était pas utile.

Je vais voir ça ainsi que ça aussi https://github.com/ldleman/yana-server/issues/104#issuecomment-68828066, ça devrait pas être long à corriger.

![image](https://cloud.githubusercontent.com/assets/2841495/5627485/ed99ed76-9598-11e4-81f4-da894b476c21.png)
