### ISSUE TITLE
erreur d'installation 2

### ISSUE THREAD

**Issue by thib3113** [ldleman/yana-server#104]
```shell
[....] Starting web server: lighttpd2014-10-15 13:38:40: (network.c.405) can't bind to port:  80 Address already in use 
 failed!
```
il semblerais que il y ai un soucis avec la vérification des webserver

**Comment by ldleman** [comment]
ha bon ? :) On ne m'a pas mis au courant alors ... :D
Aucune détection n'est prévue par yana-server ou pour l'installateur.

Si apache est déjà démarré sur le port 80, c'est normal que lighttpd ne puisse le prendre.
Il te faut changer le port d'apache ou de lighttpd, ou n'utiliser qu'apache pour héberger yana server

**Comment by maditnerd** [comment]
J'avais uploadé ça en douce (c'est pas bien :-1: )

Ma vérif pour tester si un paquet est installé à l'air d'être dépendant de la langue du système (les locales)
````dpkg -s "$1"|grep "Status: install ok installed" > /dev/null 2>&1````
Avec
````dpkg-query -l "$1" | grep "ii" > /dev/null 2>&1````
Le problème ne devrait pas se poser

Par contre, j'ai remarqué quelque-chose, si apache2 a été désinstallé avec
````apt-get remove apache2````
Il n'est pas vraiment désinstallé, (les fichiers binaires/le script de démarrage dans /etc/init.d sont toujours là car il sont considérés comme des dépendances)
Seul un ````apt-get autoremove```` le supprime pour de vrai

Donc pour vraiment bien faire les choses, il est peut être plus prudent de vérifier l’existence de
* /usr/sbin/apache2
* /usr/sbin/nginx

J'ai choisi la méthode de la vérification de l'existance des fichiers, mais je peux remettre le check de dpkg si vous préférez.

Voilà le nouveau code:
https://gist.github.com/maditnerd/2fbd056df6d42090a307

Question piège pour @ldleman  : 
* Je le pull request ?
* Je le commit ?
* Où je te laisse faire ?

**Comment by ldleman** [comment]
@maditnerd tu maitrise entierement cette partie, tu as les accès contributeurs sur le depot et jusqu'ici tu ne m'a pas demandé la permission pour chaques update ya pas de raisons que ça change :D.

Bref fait toi plaisir ^^, merci pour ce bel installateur qui sauve la vie de pas mal d'utilisateurs si j'en crois les retours.

**Comment by maditnerd** [comment]
Ok! c'est fait, Merci à @thib3113 pour l'info! Je ferme les issues , hésitez pas à réouvrir si j'ai fait des bétises ^^

**Comment by thib3113** [comment]
personnellement je fais comme ceci pour tester l'installation d'un paquet :
'''shell
sudo dpkg --get-selections | grep "$soft" | grep -v deinstall | wc -l
'''
ou soft vaux :
'''shell
#pour un nom exact
soft="${1}\s" 
#pour un nom regex
soft=$1
'''

mais effectivement ça ne vérifie peut être pas que apache soit bien désinstallé
