### ISSUE TITLE
Taille limite du retour de Yana server

### ISSUE THREAD

**Issue by Florian56** [ldleman/yana-server#108]
Bonjour,

J'ai un problème lorsque Yana server retourne une chaine trop longue (Je n'ai pas le nombre de caractères exacts, mais cela joue à 1 caractère près). Le contenu est bien affiché sur le smartphone, mais n'est pas parlé par celui-ci.

Avez vous déjà eu le problème ? Savez-vous s'il y a bien une limite du nombre de caractères ? Est-ce un bug ?

Merci.

**Comment by ldleman** [comment]
Il faut que j'essaye de reproduire le bug ce we, pour le moment je n'ai jamais eu le soucis mais je n'ai jamais mis de commandes a rallonge non plus.

Ca intervient sur quelle commande/plugin exactement ?
