### ISSUE TITLE
web interface ne marche pas: Attention, les droits vers le fichier  radioEmission sont mal réglés.

### ISSUE THREAD

**Issue by jayce996** [ldleman/yana-server#110]
bonjour,
malgré avoir suivi la procédure à la lettre(:-/), mis les droits root:www-data sur radioEmission, et le chmod en 4777, les commandes fonctionnent via ligne de commande mais rien n'y fait via les interface web que ce soit via hcc ou via yana-server.
de plus, yana-server dit qu'il y a des droits vers le fichier radioEmission qui sont mal réglés mais la doc fait bien mention des réglages listés ci-dessus.

**Comment by Kassouma** [comment]
Salut, 
j'ai également un message sur la problématique des droits, j'ai essayé de désactiver/réactiver le plugin sans succès.
Cependant malgré ce message la commande semble se lancer lorsque j'appuie sur l'icone.
Quand cette commande est lancée, ma lampe s'eteinds puis se rallume, j'ai été voir dans les logs la commande executée : 
 
Le dernier argument semble être 1 pour allumer 0 pour eteindre, or le programme à l'air d'attendre un string "on" ou "off". 
Il semble donc avoir deux problématique, l'argument passé à la commande et la detection des droits...
Ou alors on a raté un truc dans la configuration xD
Je n'ai pas pris le temps de regarder plus car j'utilise le plugin rcswitch qui répond plus a mes besoins.....

**Comment by TOONSLAND** [comment]
Salut,
J'ai eu ce problème avec le message droit mal réglés:
j'ai fait: 

sudo chown -R www-data:www-data yana-server && sudo chown root:www-data /var/www/yana-server/plugins/radioRelay/radioEmission && sudo chmod +s /var/www/yana-server/plugins/radioRelay/radioEmission

Attention en suivant ce lien https://github.com/ldleman/yana-server dans "mise à jour" la suite de commande n'est pas à jour. plugins/relay/radioEmission  doit être: plugins/radioRelay/ radioEmission

**Comment by Kassouma** [comment]
Oui de même , la commande est bien lancée de mon côté mais le message s'affiche quand même :)

**Comment by jayce996** [comment]
Oui j'avais vu cette différence et fait la modif manuellement, mais rien n'y fait
j'ai refais la commande que tu as listé, mais même statut: OK via command-line mais pas via l'interface web

**Comment by Kassouma** [comment]
@jayce996 Verifie avec le widget log que la commande n'est pas lancée.
Que tapes tu en cli stp?

**Comment by TOONSLAND** [comment]
essayer cette manipe: (Emission et Reception doivent avoir des permissions)

sudo chown -R www-data:www-data yana-server
sudo chown root:www-data /var/www/yana-server/plugins/radioRelay/radioEmission
sudo chmod +s /var/www/yana-server/plugins/radioRelay/radioEmission

en plus

sudo chown root:www-data /var/www/yana-server/plugins/radioRelay/radioReception
sudo chmod +s /var/www/yana-server/plugins/radioRelay/radioReception

**Comment by jayce996** [comment]
alors,
@TOOSLAND, les modifs sur les permissions sont passées mais pas de changement

@Kassouma, merci ça permet d'avancer un peu plus:
en cli je tape: sudo ./radioEmission 0 11223344 1 on 
depuis /var/www/yana-server/plugins/radioRelay

via les logs j'ai:
03-01-2015 16:18:41 - [notice] :Launch system command : /var/www/yana-server/plugins/radioRelay/radioEmission 5 0 11223344 1 

les différences: le "5" en plus et le "on" ou "off" en moins
 viennent du wirringPi où j'ai mis 5 pour voir, même si avant j'avais mis 11 qui était le pin utilisé comme dans le blog.

**Comment by Kassouma** [comment]
@jayce996 

Je n'ai pas trop compris d'ou vient le 5, le 0 juste après définit le PIN utiisé ( peut être que tu as mal copié/collé?)

Au final on a bien le même soucis .
La commande qui "devrait" être passée est : 
./radioEmission 0 11223344 1 on 

mais celle qui est passée est  : 

./radioEmission 0 11223344 1 1

@TOONSLAND j'ai essayé également de donner les droits a radioReception mais rien n'y fait le message est toujours la ...

**Comment by Kassouma** [comment]
@TOONSLAND  par contre pour l'info je n'ai pas de dossier yana-server, a l'installation j'ai copié son contenu dans mon /var/www ... ( c'est tout ce qui pourrait être "particulier" chez moi je pense °°)

**Comment by TOONSLAND** [comment]
@Kassouma suis la trame d'installation. /var/www/yana-server.

Le script installe yana-server et donne des droits sur les fichiers .cpp pour info ;)

sudo wget https://raw.githubusercontent.com/ldleman/yana-server/master/install.sh && sudo chmod +x install.sh && sudo ./install.sh

puis

sudo chown -R www-data:www-data yana-server
sudo chown root:www-data /var/www/yana-server/plugins/radioRelay/radioEmission
sudo chmod +s /var/www/yana-server/plugins/radioRelay/radioEmission
sudo chown root:www-data /var/www/yana-server/plugins/radioRelay/radioReception
sudo chmod +s /var/www/yana-server/plugins/radioRelay/radioReception

**Comment by jayce996** [comment]
on avance on avance, merci beaucoup :+1: 
ce que je n'avais pas de bien configuré c'était la partie radioReception, seule la RadioEmission était faite correctement.
maintenant j'ai: 
- toujours le message d'alerte sur le dashboard
- l'interface web qui émet bien le signal vers les récepteurs RF MAIS:
-- mes 3 récepteurs DI.O s’allument et s’éteignent en même temps en 1/2 seconde
alors que via cli seul le commutateur désiré s'allume correctement, et qu'aucun des autres n'est référencé ni connu, ni n'a été appairé auparavant .

-commande cli exécutée: sudo ./radioEmission 0 11223344 1 on
-configuration de l'interface web:
--configuration/preference/radio relai: pin raspberry =1, code télécommande pris par raspberry =1
--configuration/relais radio: Nom= Lampe Salon, code radio=11223344, mode impulsion=0

**Comment by Kassouma** [comment]
@jayce996 

"mes 3 récepteurs DI.O s’allument et s’éteignent en même temps en 1/2 seconde alors que via cli seul le commutateur désiré s'allume correctement, et qu'aucun des autres n'est référencé ni connu, ni n'a été appairé auparavant avec la raspberry."

C'est du au fait que le paramètre est 1 ou 0 pas on ou off ;)
Tu n'as qu'a le taper en cli ca fera la même chose ;) :  
./radioEmission 0 11223344 1 1

**Comment by jayce996** [comment]
mais pourquoi l'interface web fait ça? il faut changer quelque chose quelque part?
je suis le seul a avoir ce problème?

**Comment by chriskross** [comment]
Bonsoir à tous !!!

Je constate le meme probleme sur mon interface YANA 3.0.6. j'ai essayé quelques modifications, coté plugin, mais rien y fait.... Je vais encore chercher de ce coté là, puis peut être bien qu 'un homme plus eclairé que nous, apportera la solution... 
sinon le plugin RCSwitch fonctionne très bien chez moi ;-) ... 

cordialement 
bonne soirée à très bientot

ps : merci IDLEMAN et toute l'equipe pour ce beau projet.

**Comment by chriskross** [comment]
je confirme ton histoire de on / off et 0 et 1 
commande ne fonctionnant pas ( ou plutot donne un marche arret) -> sudo ./radioEmission 2 16814250 0 1
commande fonctionnant normalement sudo ./radioEmission 2 16814250 0 1

au plaisir !!!

**Comment by chriskross** [comment]
solution bidouillée, à modifier plus serieusement.
dans le repertoire /var/www/yana-server/plugins/radioRelay/radioRelay.plugin.php
A partir de la ligne 294 - modifie la function radiorelay_plugin_change_state($engine,$state) comme suit :

function radiorelay_plugin_change_state($engine,$state){
	global $conf;
	global $states;
    if ($state == 1) {
	 $states = "on";
	 }
     else {
	 $states = "off";
	   }
	$radioRelay = new RadioRelay();
	$radioRelay = $radioRelay->getById($engine);

	$cmd = dirname(__FILE__).'/radioEmission '.$conf->get('plugin_radioRelay_emitter_pin').' '.$conf->get('plugin_radioRelay_emitter_code').' '.$radioRelay->radiocode.' ';
	$cmd .= $radioRelay->pulse ==0 ? $states : 'pulse '.$radioRelay->pulse;
					
	$radioRelay->state = $state;
	Functions::log('Launch system command : '.$cmd);
	system($cmd,$out);
	$radioRelay->save();

}

A +

**Comment by ldleman** [comment]
Je prends bonne note du soucis, je vais voir ce que je peux tester/debugger/patcher d'ici demain soir, désolé pour ce soucis :)

**Comment by ldleman** [comment]
J'ai tenté un ptit correctif à distance pour le on/ff dites moi si ça fonctionne.
Pour les droits je regarderais sous peu, il y a des chances que la verification ne soit pas bonne mais que les permissions soient bien réglées quand même.

**Comment by ldleman** [comment]
Salut @chriskross,
Effectivement c'est une boulette de ma part, ça m'apprendra a coder pendant l'apéro !
C'est corrigé normalement, peux tu faire une maj et re-tester ? :)

**Comment by chriskross** [comment]
Salut @idleman,
Je teste la correction ce soir, apres ma longue et éprouvante journée de travail !!  
Boire ou coder, il faut choisir  ... Ca devait quand meme etre un super apero pour faire autant de boulette ;-)

Bonne journée, je te tiens informé ce soir. ++

**Comment by chriskross** [comment]
function plugin_radiorelay_change(element,id) et engine  :  id .... 
Je soupçonné aussi un bug coté js. Vu que les engine ne s actualisés pas apres action.

**Comment by chriskross** [comment]
Re @Idleman,

Je viens de tester les dernieres modifications que tu as apporté aux fichiers radioRelay.plugin.php et RadioRelay.class.php. 
Les commandes on/off fonctionnent bien, et le code radio definit dans le plugin setting de radioRelay corespond bien à l'action demandée. 
Impeccable, tout semble rentrer dans l'ordre..
Tu vois quand tu es sobre cela fonctionne plutot mieux!!!

Si je peux me permettre dans radioRelay.plugin.php
<label for="offRadioRelay">Commande vocale "OFF" associée</label>
<?php echo $conf->get('VOCAL_ENTITY_NAME') ?>, <input type="text" id="offRadioRelay" value="<?php echo $selected->offCommand; ?>" placeholder="Eteinds la lumière, Ferme le volet…"/>

il y a un petit probleme de conjugaison ;-) -> placeholder = "Eteins la lumière, Ferme le volet" sera plus frenchie. je te l accorde c du chipottage !!!!

Merci pour toutes ces corrections, pour ta disponibilité, ta sympathie. Excellent projet !!
@++

**Comment by ldleman** [comment]
Yop @chriskross.
Ya moyen que tu ouvre une autre issue pour ce poblème différent ? C'est plus simple a gérer pour nous si on compartimente :)

**Comment by Gribou** [comment]
Bonjour,
Tout d'abord, merci pour ce projet, je me régale.
SI je viens poster une demande dans ce Git, et que cela n'est pas la bonne place, désolé, quelqu'un pourra sans doute m'indiquer une meilleure place.
En fait j'ai le même soucis que décrit ci dessus. A savoir j'arrive à allumer ma lampe en CLI, mais pas avec l'interface Web.
J'ai réglé les droits comme indiqué, mais rien n'y fait.
-rwsr-sr-x 1 root     www-data 13331 juin  13 15:05 radioEmission

J'ai fait de même pour le cpp
-rwsr-sr-x 1 root     www-data  5587 juin  13 15:05 radioEmission.cpp
au cas ou ...
le reste du repertoire : 
drwxr-xr-x 2 www-data www-data  4096 juin  13 15:05 css
-rwxr-xr-x 1 www-data www-data   572 juin  13 15:05 install
drwxr-xr-x 2 www-data www-data  4096 juin  13 15:05 js
-rwsr-sr-x 1 root     www-data 13331 juin  13 15:05 radioEmission
-rwsr-sr-x 1 root     www-data  5587 juin  13 15:05 radioEmission.cpp
-rwsr-sr-x 1 root     www-data 25288 juin  13 15:05 radioReception
-rwxr-xr-x 1 www-data www-data  3577 juin  13 15:05 radioReception.cpp
-rwxr-xr-x 1 www-data www-data  1020 juin  17 13:23 RadioRelay.class.php
-rwxr-xr-x 1 www-data www-data 17561 juin  18 08:34 radioRelay.plugin.php




J'ai, je pense, la dernière version (fresh install du 13/05).
Je vois que chriskross voit des logs, mais malgré mes recherches, je ne sais pas où est situé le fichier, est-ce le  /var/log/lighttpd/error.log car chez moi ce fichier est quasi vide.
Bref un petit coup de main serait sympa.

Par avance merci,

**Comment by maditnerd** [comment]
Test si le serveur web est capable de contrôler les prises en te connectant en tant que www-data comme ça tu pourras voir les erreurs.
````
su www-data
bash
````

**Comment by Gribou** [comment]
Salut,
je viens de faire 
su www-data
/var/www/yana-server/plugins/radioRelay/radioEmission 0 4419475 1 on
Et la lumiere s'est allumée

**Comment by Gribou** [comment]
dans la FAQ (http://projet.idleman.fr/yana/?page=FAQ) il est indiqué :
Le code télécommande (par défaut 8217034) et/ou le code récepteur ne correspondent pas à ce que la prise attends

Qu'est-ce le code télécommande et le code récepteur ?

**Comment by Gribou** [comment]
Ok, je viens de comprendre, en fait ça marche. Les droits sont bon. Mais je ne savais pas me servir de l'interface tout simplement. L'idée est que dans preference -> relais radio ,on fixe le pin de l'emeteur ( 0 ) et le code de la telecommande en particulier pour moi 4419475  et que ensuite dans 'Code radio' de preference->relai radio on mets un code specifique (par exemple 2) la commande generée parle code PHP sera donc :
/var/www/yana-server/plugins/radioRelay/radioEmission 0 4419475 2 on
Et zou ça marche ....

Pour les logs rien de plus simple : on les fait apparaitre dans un widget :-)
