### ISSUE TITLE
PHP Fatal error:  Call to a member function data() on a non-object in...

### ISSUE THREAD

**Issue by TOONSLAND** [ldleman/yana-server#112]
Bonjour,

Après installation automatique de YANA-SERVER j'ai cette erreur lors de l'enregistrement du widget avec un relais filaire, pas de problème avec le relais radio!

Si quelqu'un connaît comment résoudre ce problème?
Merci d'avance,

Log erreur de nginx:

2015/01/01 21:00:48 [error] 20558#0: *179 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function data() on a non-object in /var/www/yana-server/plugins/wireRelay/wirerelay.plugin.php on line 264" while reading response header from upstream, client: 192.168.0.4, server: localhost, request: "GET /action.php?action=wireRelay_save_widget&relay=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.9:9292", referrer: "http://192.168.0.9:9292/index.php"
2015/01/01 21:00:49 [error] 20558#0: *179 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function data() on a non-object in /var/www/yana-server/plugins/wireRelay/wirerelay.plugin.php on line 116" while reading response header from upstream, client: 192.168.0.4, server: localhost, request: "GET /action.php?action=wireRelay_load_widget HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.9:9292", referrer: "http://192.168.0.9:9292/index.php"

**Comment by TOONSLAND** [comment]
avec lighttpd

2015-01-04 11:39:46: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, no such table: yana_rank in /var/www/yana-server/classes/SQLiteEntity.class.php on line 265
PHP Fatal error:  Call to a member function fetchArray() on a non-object in /var/www/yana-server/classes/SQLiteEntity.class.php on line 269

**Comment by ldleman** [comment]
Pour la table manquante ça ressemble a une erreur d'installation, as tu desinstallé / réinstallé yana pour tout remettre au propre?

**Comment by TOONSLAND** [comment]
J'ai fait une nouvelle installation (formatage) avec lighttpd comme serveur (lien d'auto installation) mais ça ne marche toujours pas (voir erreur de lighttpd dans le mail plus haut). As tu les noms des paquets PHP et SQLite a mettre? je me demande si le problème ne vient pas de là?

**Comment by ldleman** [comment]
Normalement 
sudo apt-get install sqlite3 && sudo apt-get install php5-sqlite 
devrais installer sqlite et sa liaison avec le php quel que soit le serveur http installé.

Cela dit je pense que tu as ces prérequis puisqu 'il semble trouver la classe sqlite et qu'il pete en erreur en moment de trouver la table.

As tu fait un 
sudo chown -R www-data:www-data /var/www

Avant installation ?
Est ce que le fichier /var/www/yana-server/db/.database.db est présent et n'est pas vide (taille a 0ko) ?

**Comment by TOONSLAND** [comment]
Lu @ldleman 

après un git clone il n'y a pas de fichier .database.db. Il est créé lors de la première connexion par install.php

Bon bin voilà après deux nouvelles installations de raspbian+yana toujours la même erreur. Je ne comprends pas!

**Comment by chriskross** [comment]
Je regarderai demain si ce bug est present chez moi. Sinon Switchi est equivalent à wire relay, meme mieux à mon sens car il permet faire commuter une sortie gpio => 1 relai suivant trois type d interaction. Soit par commutation dune entree gpio, soit par commande vocale, soit par interface web. Cerise sur le 🎂... Il regroupe les relais par groupe pour permettreune action groupé. 
+++

**Comment by F0cks** [comment]
Bon alors perso j'ai pas d'erreur, par contre effectivement le relai est bien créé mais n'apparait pas la pièce.

**Comment by ldleman** [comment]
@TOONSLAND après installation ouvre le fichier .database.db avec adminer (gratuit) ou un autre browser sqlite et verifie que la table yana_rank existe.

**Comment by ldleman** [comment]
On peux clore ce bug ou il y a toujours un soucis ?
