### ISSUE TITLE
Probleme de droits avec yana android

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#114]
Après n ième reinstall de yana et un millier de je suis désolée je n'ai pas le droit de faire cela j'ai fini par commenter les lignes de vérification du user dans wirerelay.plugin.php et cela fonctionne.
Ceci dit j'aimerais comprendre ce qui ne fonctionne pas avec les users.

case 'wireRelay_vocal_change_state':
                        global $_,$myUser;
                        //try{
                                $response['responses'][0]['type'] = 'talk';
                        //      if(!$myUser->can('relais filaire','u')) throw new Exception ('Je ne vous connais pas, ou alors vous n\'avez pas le droit, je refuse de faire ça!');
                                wirerelay_plugin_change_state($_['engine'],$_['state']);
                                $response['responses'][0]['sentence'] = Personality::response('ORDER_CONFIRMATION');
                        //}catch(Exception $e){
                        //      $response['responses'][0]['sentence'] = Personality::response('WORRY_EMOTION').'! '.$e->getMessage();
                        //}
                        $json = json_encode($response);
                        echo ($json=='[]'?'{}':$json);
                break;

**Comment by ldleman** [comment]
Coucou :), peux tu faire un update et désactiver/réactiver le plugin  ? C'est un problème que j'ai résolu récemment, désolé pour le bug :)
