### ISSUE TITLE
toujours pb avec wirerelais

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#118]
Maintenant j'ai erreur de contact avec yana server depuis android.
Dans le log j'ai 
Fatal error: Call to private method System::command() from context 'Gpio' in /var/www/yana-server/classes/Gpio.class.php on line 15

une idee ?

**Comment by ldleman** [comment]
Yop !
Peux tu faire un update de yana et verifier que le problème est corrigé :) ?

**Comment by ingfred** [comment]
Excellent !
Pourquoi conserve t-on la notion de pièce (plugin room) dans les relais si tu désires les enlever à terme ?
Je continue à jouer. 
Pour info, J'ai eu un doublon de de dashboard dans les listes déroulantes. Suis pas allé voir dans la base pour voir si pb de base ou de mise à jour de la liste.
Si je peux reproduire le phénomène je re-issue.
Merci pour tout. Ton boulot fait des émules dans notre petit fablab tout récent du Jura.

**Comment by ldleman** [comment]
La notion de pièce vas rester, mais l'onget "room" vas dégager. 

Pour le moment je le laisse car il est encore utilisé par de nombreux
plugins, il faudrait que je toruve un moyen de contacter les
contributeurs pour qu'ils fassent la modif mais c'est pas gagné :)
Content de savoir qu'un fablab s'interesse a mes travaux, c'est toujours
gratifiant :) 

Le 11.02.2015 11:42, ingfred a écrit : 

> Excellent !
> Pourquoi conserve t-on la notion de pièce (plugin room) dans les relais si tu désires les enlever à terme ?
> Je continue à jouer. 
> Pour info, J'ai eu un doublon de de dashboard dans les listes déroulantes. Suis pas allé voir dans la base pour voir si pb de base ou de mise à jour de la liste.
> Si je peux reproduire le phénomène je re-issue.
> Merci pour tout. Ton boulot fait des émules dans notre petit fablab tout récent du Jura. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/ldleman/yana-server/issues/118#issuecomment-73862108

**Comment by ingfred** [comment]
Ton boulot permet de voir qu'avec un peu de sous, du jus de cerveau et du partage on peut faire de grandes choses.
Bel exemple pour tous.
Le jura est un peu  de chez toi mais si tu passe dans l'est n'hésite pas a appeler, l'apero sera prêt.
