### ISSUE TITLE
Yana Market : plugin Ethernet Relay bug corrigé.

### ISSUE THREAD

**Issue by chriskross** [ldleman/yana-server#120]
Bonsoir à tous,
Si comme moi vous utilisez un arduino avec shield Ethernet pour piloter vos relais et/ou module rf. Voici une modification à apporter.

Si vous ne faites pas cette correction, seul le dernier relais qui est placé sur le dashboard change d'état.

Pour debugger  le plugin, changer comme suit le fichier ethernetrelay.plugin.php : 
Ligne 201 A 229 

						<ul class="relay_pane">
								<li class="ethernetRelay-case" '.($relay->state?'active':'').' onclick="plugin_ethernetRelay_change(this,'.$relay->id.');" style="text-align:center;">
									<i title="On/Off" class="'.$relay->icon.'"></i>
								</li>
								<li>
									<h2>'.$relay->description.'</h2>
									<h1>Code '.$relay->code.'</h1>
								</li>
							</ul>

						
						<script type="text/javascript">
							function plugin_ethernetRelay_change(element,id){
								var state = $(element).hasClass(\'active\') ? 0 : 1 ;

								$.action(
									{
										action : \'ethernetRelay_manual_change_state\', 
										engine: id,
										state: state
									},
									function(response){
										$(element).toggleClass("active");
									}
								);

							}
						</script>

+++ bonne soirée

**Comment by chriskross** [comment]
@ldleman je me suis permis poster les modifs ici, car je n'ai pas connaissance d'un equivalent github pour les plugins presentés sur le market. et de fait, qui fait les MAJ ces plugins?

Désolé si ce n'est pas la bonne procèdure ++

**Comment by ldleman** [comment]
@chriskross Le market est alimenté par les contributeurs, visiblement celui dont tu parle a été codé par iya de iyadev.fr, il lui suffit de renvoyer le même plugin corrigé pour que je valide et que ça ecrase l'ancien @iyadev si tu nous entends... :)

**Comment by iyadev** [comment]
J'ai tester, et cela fonctionne. Je viens donc de l'envoyer sur le market. ^^

**Comment by chriskross** [comment]
@Idleman @iyadev

desolé je ne me suis pzs connecté sur github depuis un petit moment.
je cloture le post.

bonne soiree ++
