### ISSUE TITLE
Que peut-on mettre dans les commnades pour évenements ?

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#121]
J'ai du rater un truc, mais en essayant de de lancer un /var/www/.........../radioemission.... qui passe fort bien en ligne de commande via le gestionnaire d'évenement, yana ne lance rien. Quel type de commande peut-on lancer avec ce gestionnaire.
A classer peut-être dans les question débiles si la catégorie existe.
Second truc : Je suis prêt à faire les tutos des plugins que je teste (A force de jouer avec je finis par comprendre comment cela fonctionne), mais je les range ou ?

**Comment by ldleman** [comment]
@ingfred de mémoire (parce que le développement de ce module est assez lointain dans ma tête) la commande est executée sur le poste client ou se trouve le yana for windows, et non sur le serveur du rpi, d'ou ton radioemission qui ne fonctionne pas (puisqu'il est sur le serveur).

Pour ce qui est des tutos c'est des video ou du texte ? 
Ou pourrait ouvrir une section sur le market pour ça.

**Comment by ingfred** [comment]
Ok pour le lancement de commande. Merci de la réponse car n'utilisant pas windows j'aurais cherché un bout de temps.
Concernant les tutos, je pensais faire un bout de texte. Autant je trouve la vidéo utile pour les montages, pour le paramètrage soft je trouve cela galère. 
Je propose cela car j'ai des demandes du fablab pour leur montrer un peu ton très joli projet. Donc besoin de ces tutos.  Comme de plus je teste les modules et que je ne suis pas bon, j'ai une très bonne vision des problèmes potentiels que peuvent avoir les mauvais dans mon genre.
Bonne idée la la section sur le market.
Encore une fois merci pour ce projet.

**Comment by ingfred** [comment]
Bonjour.
Pour la gestion des events, j'ai l'impression qu'il s'agit d'un problème de droits.
J'avais eu le pb sur le plugin siplen ou j'ai viré le controle user....
Mais la je ne comprends pas la logique de l'event manager. 
as tu une idée de ce qui peut générer ce  {"error":"insufficient permissions for this account"}
dans le fichier action.php\?action\=GET_EVENT
Dans action.php, 
case 'GET_EVENT':
        if($myUser->getId()=='') exit('{"error":"invalid or missing token"}');
        if(!$myUser->can('vocal','r')) exit('{"error":"insufficient permissions for this account"}'); 
que cherche t-il a ramener par la fonction getid ?
merci par avance.
Fred

**Comment by Nini81** [comment]
Salut : 
J'ai regardé rapidement le code de cette section et je pense qu'il s'agit d'une "faute de frappe" dans le code.

Dans "action.php", peux-tu essayer de remplacer 
```php
if(!$myUser->can('vocal','r')) exit('{"error":"insufficient permissions for this account"}'); 
```
par
```php
if(!$myUser->can('vocalInfo','r')) exit('{"error":"insufficient permissions for this account"}'); 
```

De ce que j'ai compris rapidement dans le code et dans la bdd, le nom du plugin n'est pas vocal, mais bien vocalInfo. Donc je pense que tu passe dans ce if parce qu'effectivement, $myUser->can('vocal','r') n'existe pas. Par contre $myUser->can('vocalInfo','r') devrait exister et être à vrai (sauf si tu as toucher les droits dans la bdd :) )

Nini

**Comment by ldleman** [comment]
$myUser->getId() vérifie uniquement que ton user a un ID, et donc qu'il existe en base (bref que tu est loggué avec le bon utilisateur). Cela dit c'est la ligne suivante qui ne passe pas a savoir : if(!$myUser->can('vocal','r'))

En revanche il n'y a pas de fautes de frappe comme le suggère Nini, la section de sécurité rattachée a vocalInfo s'appelle bien "vocal" le problème ne viens donc pas de là.

Vérifie dans les accès de ton admin que tu as bien les cases c,r,u,d d'activées pour la section vocal.

**Comment by ingfred** [comment]
Bonjour et merci des infos.Désolé nini81, je n'avais pas vu ton post. Merci pour celui ci.
J'ai deux room et 3 vocal dans lea gestion des rangs de programmes. Le pb viens peut être de la.
Toutes les cases sont cochées : ajout, consultation, etc.

**Comment by ingfred** [comment]
Je n'ai pas bricolé la base. Mais en regardant dedans j'ai la table yana_plugin_vocalinfo qui est vide. c'est normal ?

**Comment by ingfred** [comment]
J'ai réinstaller yana tout neuf sur raspbian tout neuf.
L'install automatique fonctionne bien.
Seul hic restant les événements sur serveur. En fait le serveur n'a pas de token donc il ne peux pas avoir d'id (via crontab). N'est ce pas la mon problème ?

**Comment by ingfred** [comment]
Honte énorme.
Réponse à mes questions dans 
http://forum.idleman.fr/discussion/181/yana-gestion-des-evenements-comment-ca-marche
de février 2014.
