### ISSUE TITLE
Token Invalide

### ISSUE THREAD

**Issue by Thegritche** [ldleman/yana-server#122]
Bonjour à tous
J'ai installé une première fois Yana sans soucis et obtenu un token fonctionnel sur l'appli android, une reinstallation me donne un autre token qui cette fois me dit invalid 
un navigateur affiche {"error":"invalid or missing token"}

Comment nettoyer pour regenerer un autre token
Merci

**Comment by agentcobra** [comment]
tu peux regarder dans ces issues là -> #19 #47 #95

**Comment by Thegritche** [comment]
Hum,
Bon apres suppression du dossier www/yana-server le navigateur ne me donne plus d'erreur
Mais l'appli Android me dit que le token est invalide, je vais voir de ce coté la
