### ISSUE TITLE
Fonction inexistante dans getInfos() dans classes/system.class.php

### ISSUE THREAD

**Issue by Vax3** [ldleman/yana-server#123]
Salut Idleman 
j'aime bien ce que tu fais (non sans blague) mais voila j'ai un petit problème
J'ai quand même fais le test sur 2 rpi différents (le 1 m'a claqué entre les pattes donc rachat oblige) et j'ai toujours la même erreur.

J'ai aussi quand même fait le test avec l'installation manuelle et auto mais rien à faire le "module" des GPIO ne m'affiche rien

dans mon /var/log/lighttp/error.log j'ai:
2015-03-06 22:03:24: (mod_fastcgi.c.2676) FastCGI-stderr: PHP Fatal error:  Call to undefined method System::system() in /var/www/yana-server/classes/System.class.php on line 5

qui correspond à un appel system très exactement celui-ci
$return = self::system('cat /proc/cpuinfo');

et la je sèche je ne sais pas ce qu'il viens me faire c***r et je m'en remet donc à toi (ou tout autre âme charitable qui passerai par la)

ps: c'est bien dommage que tu habite si loin de paris je vais pas me taper un aller retour pour une bière :(

**Comment by maditnerd** [comment]
J'ai remplacé ````self::system```` par ````self::command```` et l'erreur a disparu.
Par contre ````system```` balance sa sortie ce qui dézingue le json.

Du coup j'ai crée une fonction ````command_silent```` qui utilise shell_exec à la place.

Je vais faire un commit à part avec la gestion des erreurs dans les widgets

**Comment by Vax3** [comment]
hey hey mon sauveur merci :) ca focntionne nickel
