### ISSUE TITLE
gpio inactif yana accueil

### ISSUE THREAD

**Issue by Vax3** [ldleman/yana-server#126]
Salut à tous,

J'ai encore un problème avec les gpio, cette fois ils s'affichent (quoique pas tous je suis en pi2 et j'en ait que 22/40 potentiellement) mais surtout lorsque je clic sur un gpio son etat theorique change mais pas en vrai sur le pi.

J'ai vu un petit quelque chose qui est susceptible de corriger tout ca ->
https://github.com/ldleman/yana-server/pull/98/commits

mais dans le code j'ai pas les modifs et pas d'erreur dans mes logs

**Comment by Nini81** [comment]
Bonjour à tous :D

La même ici. Installation toute neuve de raspbian sur un "vieux" rapsberry pi B. Donc tout est tout neuf et a jour (vérifications faites).

Ce qui fonctionne : 
- via la command line du pi ("gpio write 1 1" / "gpio write 1 0") d'allumer/eteindre une fucking led (que j'ai piqué sur une des loupiotte du vélo a ma fille, mais chut, faut pas le dire, mon WAF se casserai la gueule si la morpionne cafte :) ). 

- via une interface web récupérée par un mec qui semble souvent boire l'apéro ( celle là : http://blog.idleman.fr/raspberry-pi-06-utiliser-le-gpio-et-interagir-avec-le-monde-reel/ , "adaptée et modifiée" pour une seule led).

Ce qui ne fonctionne PAS : 
- via l'interface web yana-server, widget GPIO. On clic dessus, l'etat affiché switch bien de off à on (et vice-versa) mais aucune réaction du pi (aka pas de led qui s'allume).

Via l'interface web "oldschooljsuislroidlabidouille", j'allume la led (qui s'allume pour de vrai hein), F5 de l'interface yana-server : le state est bon (etat "on").

En gros, le get state des pins fonctionne de mon côté. C'est le set qui ne fonctionne pas. 

En espérant aider :)

**Comment by Nini81** [comment]
Bonjour :D 
Je reviens ici après une p'tite phase de débug pas bien méchante au final (le plus long ayant été de comprendre comment les choses fonctionnent côté php pour yana-server :)

Je me pencherai sur la proposition Git quand jaurai compris comment faire :p (non, je n'ai pas honte de n'avoir jamais utilisé ce truc en tant que dev. J'ai toujours utilisé SVN :p )

Voici ce que j'ai fais :
- fichier "plugins/wireRelay/wirelay.plugin.php" : dans le "case 'wireRelay_load_widget'", après les instructions css, remplacer le bout de code suivant  : 
```(Gpio::read($relay->pin,true)?'active':'')```
par
```(exec("/usr/local/bin/gpio read ".$relay->pin, $out)?'active':'')```

Cay moche, mais pas pris le temps de comprendre pourquoi ce bout de code ne fonctinonait pas avec l'appel à la classe GPIO.... Ceci devrait régler le p'tit bug du widget sur les WireRelay

- fichier "plugins/dashboard-monitoring/dashboard-monitoring.plugin.php" : dans le "case 'gpio'", dans la boucle for, le remplissage de la variable "$response['content']" contient une petite faute : le 2eme

**Comment by Vax3** [comment]
Salut a toi Nini81, je vais tester ça d'ici peu, si tu veux les commandes git pour les branches etc j'ai utilisé:

git remote add gpio https://github.com/thib3113/yana-server.git
git fetch gpio
git merge gpio/master

ca va aller te chercher les modifs par répo et les fusionner, j'avais teser avec thib3113 mais le bug étais toujours la. 
De plus il y a une phase de diff avec 5/6 fichiers pas bien méchante. Des que c'est fait git te donne les commandes a re-taper pour que la fusion soit eefective, de mémoire c'est git
fetch -a 
ou un truc comme ca

En tout cas merci à toi pour le debug :)

**Comment by Vax3** [comment]
J'ai tester et NICKEL merci Nini81, la micro chose dans "plugins/dashboard-monitoring/dashboard-monitoring.plugin.php" il n'y a pas la quote inversé a début `

**Comment by Nini81** [comment]
Content que ça ait fonctionné pour toi :D 
Désolé pour la " ` " dans mon commentaire au-dessus... Une faute de frappe lors de l'édition, c'est corrigé ;)

J'ai poussé la v1.0.0 du plugin de gestion de scenario, c'est en attente de validation. Bon, c'est une V1, donc ça ne gèrera que les  wirerelay pour l'instant, j'ai pas de quoi tester les relais radio (ça arrive demain :p)
