### ISSUE TITLE
Yana [trait d'union] Serveur

### ISSUE THREAD

**Issue by Chieft** [ldleman/yana-server#129]
Sur l'application android, lorsqu'il y a un problème avec Yana-Serveur, Yana nous dit qu'il y a un problème avec yana trait d'union serveur. Ce n'est pas gênant en soi, mais ça serait un peu plus propre de mettre comme réponse pour Yana : "il y a un problème avec Yana Serveur".

**Comment by sguernion** [comment]
le problème viens de l'application android
https://github.com/Etsuni/YANA

Traitement.java ligne 85

**Comment by ldleman** [comment]
Problème à reporter sur le github android, je cloture ici, n'hésitez pas a rouvrir si question sur le sujet :)
