### ISSUE TITLE
Problème affichage relais filaire

### ISSUE THREAD

**Issue by toto2882** [ldleman/yana-server#130]
Bonjour à tous ! 
Quand j'essaye d'ajouter un relais filaire au Widget correspondant sur la page d'accueil du serveur, j'obtiens cette erreur : 
![capture1](https://cloud.githubusercontent.com/assets/12058354/7264124/93216a20-e888-11e4-8203-8b9d72a0f02c.PNG)

Le relais que j'ai ajouté est configuré comme tel : 
![capture2](https://cloud.githubusercontent.com/assets/12058354/7264133/b9e3538a-e888-11e4-977e-06a48f8fe3b2.PNG)

Voila ^^ je n'ai aucune idée si c'est un problème de ma part, ou de prog, mais je prefère le poster :)
Bonne soirée !

**Comment by triple0s** [comment]
Bonjour 

Même soucis pour ma part
Une solution trouvée ?

merci

**Comment by toto2882** [comment]
Perso toujours pas, mais ne m'y connaissant que peu en PhP, je vais essayer d'y travailler un peu ce WE

**Comment by vouvrat** [comment]
Même problème pour moi aussi.

**Comment by Nini81** [comment]
Piste de correction (ainsi que contournement temporaire) dans https://github.com/ldleman/yana-server/issues/126

**Comment by triple0s** [comment]
impeccable cela fonctionne pour moi

Merci ;)

**Comment by Nini81** [comment]
Bonjour,

Après quelques recherches, le problème viendrait de la classe System.class.php, dans la methode read... (etonnant, hein)
L'utilisation de system semble retourner des choses bizzares :/ Pourtant, elle retourne bien l'etat 1 ou 0 de la pin. P'tet un problème de caractère invisible ou un truc du genre ...
Cependant, l'utilisation de exec à la place de system semble fonctionner. J'ai toujours eut du mal a comprendre la différence entre les deux, mais bon ...

difficile de comprendre pourquoi là... (bon, ok j'ai pas fini mon café du matin, mais quand même !)

**Comment by ldleman** [comment]
Normalement c'est corrigé par madit cf https://github.com/ldleman/yana-server/issues/138, a tester :)
