### ISSUE TITLE
retour sur les commandes vocales

### ISSUE THREAD

**Issue by tikismoke** [ldleman/yana-server#131]
Salut Idelman, j'ai un souci avec l'utilisation des commandes vocales qui éxecutent une commande directement sur le serveur.
Il n'y pas de retour json ou autre du coup les clients android ou linux me sortent une erreur.
Sous ANDROID:
"il y a eu une erreur lors du contact avec yana-server" sous android et:
Sous LINUX:
"No Json Answer"

**Comment by ldleman** [comment]
Je corrige ça sous peu, merci pour la remontée d'infos.

**Comment by ldleman** [comment]
As tu pu réessayer ? Normalement je leurs renvois un json vide maintenant, ça devrait éviter de les faire planter.

**Comment by tikismoke** [comment]
Nop, je récupere la derniere version et je regarde.

**Comment by tikismoke** [comment]
Ben pour le client android ça ne change rien, il dit toujours "il y  a eu une erreur lors du contact avec yana server".
Du coup on ne sais pas si la commande c'est bien déroulée, ni même si elle a été envoyer au serveur en fait.
C'est même plus vicieux pour les commandes rapides le client andoird me renvoye la répones de la commande précédentes:
Qu'elle geure est-il?: il est 11h42;
Qu'elle poubelle je dois sortir?: il est 11h42; (mais la commande c'est bien executé et le nabaztag m'a dit qu'elle poubelle je devait sortir.

Par contre pour le changement de mode de surveillance des caméras via zoneminder (la commande mets ~1min a répondre) la j'ai droit au message d'erreur de contact.

**Comment by ldleman** [comment]
Etrange, je renvois pourtant {} (chaine json vide) via yana server ça devrait satisfaire même les clients les plus récalcitrants...

as tu bien update yana-server (et non le client) avant de faire le test ?

Quand tu accède direct a la commande via http il te renvois bien {} ?

**Comment by ingfred** [comment]
Bonjour même soucis que tikismoke concernant la réponse aux speech command. Le message renvoyé est le dernier message stocké.
En tout cas merci car plus de plantage.

**Comment by ldleman** [comment]
Je ne peux pas faire beaucoup plus de mon coté, après chaques client gère la réponse vide a sa façon, je pourrais renvoyer une phrase vide mais ce serait vraiment pas propre, il faut que les clients fassent la vérif de la réponse de leurs cotés.
