### ISSUE TITLE
Bug dans le php speechcommand

### ISSUE THREAD

**Issue by chmacc** [ldleman/yana-server#133]
Bonjour,

depuis deux jours que j'explore Yana, j'avais le soucis de pouvoir lancer une commande en local sur mon poste Windows (genre Notepad, Internet Explorer ou un URL). Je suis parti du plug-in speechcommand pour déclarer les commandes dans l'interface web. Pas de soucis de ce côté.

Par contre, pour l'exécution, j'avais un erreur de fichier non déclaré. En épluchant le code **speechcommands.plugin.php**, je suis tombé sur le bug suivant dans la section *client_command* :
```
case 'client_command':
    $response = array ( 'responses'=>array ( array( 'type'=>'command'
                                                  , 'file'=>$command->parameter
                                                  )
                                            )
                       );
    $json = json_encode($response);
    echo ($json=='[]'?'{}':$json);
    break;
```
J'ai remplacé par **file** par **programme** :
```
case 'client_command':
    $response = array ( 'responses'=>array ( array('type'=>'command'
                                                 , 'program'=>$command->parameter
                                                 )
                                            )
                       );
    $json = json_encode($response);
    echo ($json=='[]'?'{}':$json);
    break;
```
Cela marche nickel depuis pour lancer des programmes ou des urls.

Encore merci Idleman pour ton développement.

**Comment by ldleman** [comment]
Bien vu ! C'est corrigé merci pour l'info :)
