### ISSUE TITLE
erreur avec l'install automatique

### ISSUE THREAD

**Issue by flamby69** [ldleman/yana-server#136]
Bonjour,

Je ne connais pas grand chose à la programmation, du coup j'ai lancé le script d'installation automatique sur une config raspbian toute propre, et j'ai le message d'erreur suivant ;

Warning: require_once(/var/www/yana-server/plugins/dashboard/../wireRelay/wireRelay.class.php): failed to open stream: No such file or directory in /var/www/yana-server/plugins/dashboard/install on line 77

Fatal error: require_once(): Failed opening required '/var/www/yana-server/plugins/dashboard/../wireRelay/wireRelay.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/yana-server/plugins/dashboard/install on line 77

quelqu'un aurrait il la solution pour régler ce problème..?
merci d'avance

**Comment by ldleman** [comment]
Je viens de corriger le soucis, une petite coquille sur une majuscule :D tu peux faire un pdate et reinstaller ça devrait le  faire.

**Comment by flamby69** [comment]
oh, merci beaucoup.., j'ai testé ta modif et je peux finir l'installation sans problème maintenant :-)
