### ISSUE TITLE
[Widget GPIO] : Gestion du raspberry pi 2 pour l'affichage des gpios

### ISSUE THREAD

**Issue by madnerds** [ldleman/yana-server#137]
On m'a signalé que Le Pi 2 n'est pas pris en charge par le widget GPIO, je procède actuellement aux modifications de ````System.class.php```` pour résoudre ce problème.

![image](https://cloud.githubusercontent.com/assets/7965143/8032626/782e4f84-0dd7-11e5-8a62-5e00c4163e4d.png)

**Comment by maditnerd** [comment]
(Oups je me suis gouré de compte) :-(

**Comment by maditnerd** [comment]
Normalement ça devrait marcher.
997b2e8e32cb6878352a793ecb168e2f162c0ff0

Je laisse l'issue ouvert s'il y a des problèmes.

**Comment by ldleman** [comment]
bien joué, a tester par un possesseur du pi2 voir si ça fonctionne.

**Comment by Gribou** [comment]
Bonjour, 
une petite coquille dans le script, si je fais cat/proc/cpuinfo sur mon pi2, j'ai : 
Hardware	: BCM2709
Revision	: a21041
Serial		: 00000000df1cd754

et non  a01041 
a moins qu'il n'y ait plusieurs revisions :-(

**Comment by ldleman** [comment]
Oui il y en a deux en fonction du constructeur (sinon ça serais trop simple), j'ajoute la a21041 et un système de detection des révisions inconnues un peu plus classe :D dans le prochain commit
