### ISSUE TITLE
Gpio::read casse le json du widget wirerelay 

### ISSUE THREAD

**Issue by maditnerd** [ldleman/yana-server#138]
Tricky bug, à priori si wiringpi n'est pas installé ou que www-data n'a pas accès à ````/usr/local/bin/gpio```` , le problème ne se produira pas.

![image](https://cloud.githubusercontent.com/assets/2841495/8034076/bf151d12-0de4-11e5-83ac-b571d11fafef.png)

J'ai remplacé self:system par System::commandSilent est tout semble rentrer dans l'ordre.

Je checke les modifications et je fais deux commits séparé pour les deux issues que je viens de poster.

**Comment by ldleman** [comment]
On est bon sur ce bug ou pas ? On peux close ?
