### ISSUE TITLE
Soucis avec le téléchargement des plugins sur le market

### ISSUE THREAD

**Issue by parrain27** [ldleman/yana-server#140]
impossible d'installer un seul plugins 
Téléchargement du plug-in ... 
Plugin téléchargé OK
Extraction du plug-in ... 
Echec de l'extraction Erreur

j'ai réinstaller 3 fois sans réussir

**Comment by maditnerd** [comment]
Même problème de mon coté.

Idleman est en train de travailler sur le market des plugins , et il a du cassé quelque-chose.
J'ai remarqué qu'actuellement sur le market , les plugins n'ont plus d'extension ? donc c'est peut être ça.

En attendant tu peux télécharger les plugins sur
* http://market.idleman.fr/index.php
* Les renommer en .zip
* Extraire le fichier
* Renommer le dossier avec le nom du plugin (par ex si le plugin s'appelle foobar.plugin.php alors le dossier s'appellera foobar.
* Le copier dans yana-server/plugins

C'est pas pratique mais bon, sinon il ne te reste plus qu'à attendre :-(

**Comment by parrain27** [comment]
ha c'est pas moi qui et en mode blond sa me rassure mdrr merci pour la réponse rapide :)

**Comment by Alomamabobo** [comment]
Idem, même problème ici, bon weekend :)

**Comment by ingfred** [comment]
meme probleme mais solution de Matinerd fonctionne.

**Comment by ldleman** [comment]
Désolé pour ça, je vais remettre en place le lien direct pour eviter ces erreurs d'extraction, mais cela ne comptabilisera plus les downloads (oui c'est moins genant mais moi ça me perturbe ^^).

**Comment by ingfred** [comment]
d'accord. Toujours utile de savoir combien depersonne charge un module.

**Comment by ldleman** [comment]
Pouvez vous tester avec la derniere version de yana voir si ça fonctionne ? :)

**Comment by parrain27** [comment]
Oui impec merci :)

**Comment by ldleman** [comment]
Niquel merfi pour le retour  :)

**Comment by parrain27** [comment]
Pas de souci si ta besoin même  pour des test hésite pas ;)

**Comment by Alomamabobo** [comment]
Ca fonctionne nickel :)
