### ISSUE TITLE
Bug de dashboard

### ISSUE THREAD

**Issue by yppdr** [ldleman/yana-server#141]
Hello  !

Apres une installation de Yana server, je me suis rendu compte a plusieurs reprise que le dashboard général plantais et n'affichais plus rien. J'ai du réinstaller a chaque fois.

**Comment by oliviermaridat** [comment]
Quand tu dis "n'affichait plus rien", tu veux dire qu'il n'affichait plus de widgets ?
Si c'est le cas, j'ai eu le même problème, et j'ai l'impression que ce problème apparaît lors du déplacement des widgets d'une colonne à l'autre (déplacement -> refresh page -> plus de widgets).

As-tu le même comportement ?

**Comment by lowas** [comment]
C'est exactement ca ! 

Même problème

**Comment by febrez** [comment]
J'ai rencontré le même problème !

**Comment by ldleman** [comment]
Salut, 
Avez vous toujours le problème depuis le commit du 13 aout ?

**Comment by yppdr** [comment]
Pour ma part non

**Comment by ldleman** [comment]
Cool :), je cloture avant que quelqu'un vienne me dire oui alors :D !
