### ISSUE TITLE
Révision inconnue pour le Raspberry Pi 2

### ISSUE THREAD

**Issue by bilyboy785** [ldleman/yana-server#142]
Révision inconnue du RPI2 révision : 1a01041

Des infos ? MAJ ?

**Comment by ldleman** [comment]
Peux tu me donner la version (1,2...) et le type (B, A, B+...) de ton rpi afin que je l'ajout au dictionnaire des versions ?

**Comment by daniel-wagner** [comment]
Raspberry Pi 2 model B (v1.1)

**Comment by daniel-wagner** [comment]
ne change pas l'état des broches correctement!

**Comment by ldleman** [comment]
Pas besoin de points d'exclamation j'ai l'impression que tu m'engueule ! :D 

Ta version des pins est visiblement similaire à la b+ 1.0 déclarée ici dans yana :
https://github.com/ldleman/yana-server/blob/master/classes/System.class.php#L97

Essaye de voir par rapport a ce tableau si il y a une mauvaise correspondance, on la corrigera.

**Comment by daniel-wagner** [comment]
désolé, merci pour l'aide, je vais prendre le test.
