### ISSUE TITLE
Probleme wirerelays DashBoard

### ISSUE THREAD

**Issue by gotrune** [ldleman/yana-server#143]
Salut a tous;
Tout d'abord merci a toute l'équipes des développeur pour ce super projet.
Je suis utilisateur du Rpi depuis environ 1 an et j'ai decouvert YANA recemment et commence doucement a le prendre en main.
J'ai un petit probleme sur la dashboard avec les widgets wirerelays, si j'en met un seul par dashboard pas de probleme tout fonctionne bien (allumage extinction), mais si j'en met plusieurs sur la meme page je ne peut plus piloter qu'un seul relais.
Je m'explique: si jactive la pin 3 elle sallume bien (et s'eteint bien) apres ja'llume une autre pin par ex la 6, rien ne se passe et quand j'eteint la pin 6, surprise la 3 s'eteint.
En fait sur cette dashboard tout les widgets wirerelays pilote la pin 3.
J'ai désactiver et réactiver le plugins mais rien n'y fait.
je n'ai pas d'autre idées 
Merci

**Comment by ldleman** [comment]
En effet je crois qu'on m'en a déjà parlé, je vérifie ça dès que possible :)

**Comment by ldleman** [comment]
Résolu dans le commit 2a4ad3c peux tu me confirmer que c'est bon ?

**Comment by ldleman** [comment]
@gotrune  des nouvelles ? Je peux clore ?
