### ISSUE TITLE
Plugins Domoticz 1.1.1

### ISSUE THREAD

**Issue by Yannp19** [ldleman/yana-server#144]
Bonjour,

Je rencontre un problème avec le plugin domoticz 1.1.1 à savoir que je l'installe mais ensuite je ne le trouve pas dans les plugins inactifs et donc ne peux pas l'utiliser en attendant une solution j'ai remis la version 1.0.3 qui fonctionne.

Merci de bien vouloir me guider.

**Comment by Yannp19** [comment]
Je viens de tester avec d'autres plugins du même auteur S.Guernion même problèmatique pour les autres sa fonctionne

**Comment by ldleman** [comment]
Ca ressemble a un mauvais download depuis le market intégré
regarde dans ton dossier plugin si tu n'a pas un dossier nommé bizzarement genre 00650650650, si oui renomme le par le même nom que le fichier .plugin.php qu'il contient et réésaye.

**Comment by ldleman** [comment]
@Yannp19 des nouvelles ? Je peux clore ?

**Comment by Yannp19** [comment]
Bonjour,
Merci idleman le sujet peut être clos j'avais un problème de droit sur le dossier plugins

Date: Fri, 15 Jan 2016 01:37:08 -0800

**Comment by ldleman** [comment]
Okay niquel :) bonne continuation :p
