### ISSUE TITLE
check_webserver dans install.sh

### ISSUE THREAD

**Issue by energy01** [ldleman/yana-server#148]
Salut,

juste pour préciser que le "check_webserver" dans le script install.sh ne "marche pas" et/ou ne sert pas j'ai lancé sur 2 pi qui avais apache2 d'installer et rien dit et cela a installer tout sans rien demander

à l'occasion pourrais surement être "mieux gerer" mais ne pose, pour le moment, pas de problèmes

@+
Anthony

**Comment by ldleman** [comment]
@maditnerd Tu pourrais regarder ça quand tu aura un moment ? :)

**Comment by maditnerd** [comment]
![image](https://cloud.githubusercontent.com/assets/2841495/11077993/5075c00c-8803-11e5-8903-d1f38ee5064e.png)

**Comment by ldleman** [comment]
Tu sais que t'es du genre pas rassurant du tout comme type ? :D

**Comment by maditnerd** [comment]
Teaser de ouf
Le minitel n'a qu'à bien se tenir...

![image](https://cloud.githubusercontent.com/assets/2841495/11104750/d360b400-88ca-11e5-83b2-d082e1afab27.png)

**Comment by ldleman** [comment]
*_* tu t'es laché là !! :D Ca déchire tellement la moumouthe que j'en ai une petite érection ! :D (mais ça manque de messages à la con comme dans world of goo ( disolving relationship....,swaping time and space,filtering moral...scraping funds,exceeding cpu quotas... XD)

**Comment by ldleman** [comment]
Tiens j'y pense dans le client v2.0 faut lancer le serveur socket.php via un ptit 'php /chemin/vers/socket.php), si je t'envois une beta du client v2 tu pense pouvoir l'integrer en lancement auto dans ton script ?

**Comment by maditnerd** [comment]
Pas de problème, j'ai hâte de voir le nouveau client ^^

**Comment by ldleman** [comment]
T'es un chef, je te l'envois tout de suite !! :D

**Comment by ldleman** [comment]
On en est ou sur ce bug ? C'est corrigé ?

**Comment by maditnerd** [comment]
J'ai laissé trainer ça bien trop longtemps je finis ça avant noël.

**Comment by ldleman** [comment]
Bonne année ! :D On peux clore ou c'est en stand by ?

**Comment by maditnerd** [comment]
La flemme, la flemme , bon il est grand temps que je me débarasse de ça. Je commit dès que c'est fini.

**Comment by maditnerd** [comment]
C'est fini !
Avant d'envoyer le script, voilà ce que je vais modifier (en dehors de install.sh)

* il va falloir que je change ````radioRelay.plugin.php````
Je vire l'alerte pour les permissions si le permissions ont été réglé par le script.
(J'ai enlevé le maximum de droit possible tout en restant fonctionnel)
````
$radioPermission = fileperms(Plugin::path().'radioEmission')!='36333';
if(($radioPermission !='36333') && ($radioPermission !='35913'))
````
* Je vais modifier le readme
La commande pour installer yana sera
````
curl -L yana.madnerd.org |sudo bash
````
yana.madnerd.org redirige vers https://raw.githubusercontent.com/ldleman/yana-server/master/install.sh

L'installateur est blindé de fonctionnalités, je ferais une documentation plus en détail mais pour le moment , je vais noter vite fait ici tout ça.

**Comment by maditnerd** [comment]
Prérequis
========
* Il est conseillé de partir de RASPBIAN JESSIE LITE afin d'alléger l'installation
https://downloads.raspberrypi.org/raspbian_lite_latest
Reporter vous à **Restauration** si vous voulez réinstaller Yana-Server sans perdre votre
configuration actuelle.

* Si un autre programme utilise un serveur web, vous devrez paramétrer vous même le serveur web.

* Si vous ne l'avez pas fait, installer le service BONJOUR sur votre ordinateur, cela permettra de ne pas avoir à utiliser son adresse IP.
(Si vous avez skype/itunes/windows 10/mac osx c'est déjà le cas)
http://support.apple.com/kb/DL999
Pour Linux , ça dépends (je n'ai pas vraiment tester) , il faut installer *AVAHI* si nous n'arrivez pas à accéder à votre Raspberry Pi.

Installation
=========
* Connecter vous à votre Raspberry Pi avec votre terminal preféré (putty ?) avec l'adresse *raspberrypi.local*

*  Tapez 
> curl -L yana.madnerd.org|sudo bash

Cela affichera un menu
![yana01](https://cloud.githubusercontent.com/assets/2841495/12224050/c47fdd02-b7e7-11e5-9205-35b40654b0f6.png)

* Appuyez sur Installer
* Suivez les instructions à l'écran, en cas de problème vous serez averti,par un **message en rouge**
La majorité des codes d'erreurs sont vérifiés tout au long de l'étape de l'installation.

Plus d'informations
====

Voilà ce que l'installateur va faire:
- Redimensionner la carte SD si nécessaire
- Renommer votre Raspberry Pi (maison.local par défaut)
- Préparer votre Raspberry Pi
     * Mettre le terminal en français
     * Régler automatiquement le fuseau horaire avec tzupdate
     * Mettre à jour apt-get update / apt-get upgrade
     * Installer wiringPi (pour gérer les gpios)
     * Installer le serveur web (si un serveur web autre que lighttpd est installé, peut être passer)
     * Paramétrer lighttpd.conf (la database sera protégé)
     * Copier yana-server (vous pouvez passer cette étape)

Une vois yana-server installé, l'installateur va attendre que vous créer le premier utilisateur (si la base de données n'est plus vide alors il continue)
* Aller sur http://maison.local ou l'adresse affiché sur l'écran
![yana03](https://cloud.githubusercontent.com/assets/2841495/12224198/8db73934-b7ea-11e5-9d83-ec621736a0c0.png)
* Supprimer install.php 

* Rentrer un mot de passe pour le terminal
![yana04](https://cloud.githubusercontent.com/assets/2841495/12224211/00b9cafa-b7eb-11e5-854c-51460b221e88.png)

* Vérifier les permissions de /var/www/yana-server
* Donner les droits roots à tout les fichiers binaires accompagnés d'un .cpp

![yana02](https://cloud.githubusercontent.com/assets/2841495/12224190/37a06570-b7ea-11e5-87e8-86ebde100b51.png)

* Installer supervisor pour gérer le socket Yana
* Vérifie que le socket est correctement lancé sinon affiche le log de supervisor (/var/log/yanaSocket.log)

Il faut redémarrer le Raspberry Pi pour que la carte SD soit correctement redimensionné, Yana est installé et votre Raspberry Pi est prêt.

Vous pouvez accéder à votre Raspberry Pi en tapant http://maison.local (ou le nom que vous avez choisi)

Vous pouvez aussi paramétrer le client en utilisant maison.local au lieu de l'adresse ip

**Comment by maditnerd** [comment]
Sauvegarde
====

Vous pouvez sauvegarder votre installation de Yana-Server et sa configuration (/var/www/yana-server) sur une clé USB.

* Brancher une clé USB sur votre Raspberry Pi
* Tapez dans votre terminal:

> sudo configurer

* Si cela ne marche pas tapez

> curl -L yana.madnerd.org|sudo bash

![yana01](https://cloud.githubusercontent.com/assets/2841495/12224050/c47fdd02-b7e7-11e5-9205-35b40654b0f6.png)

* Appuyer sur Sauvegarder
![yana05](https://cloud.githubusercontent.com/assets/2841495/12224273/d160612c-b7ec-11e5-87dc-4689d7bd629b.png)

Plus de détails
===
* La clé USB est automatiquement détecté
* Elle est monté sur /media/backupUSB
* /var/www/yana-server et copier dans le dossier yana de votre clé USB
* Si une sauvegarde précédente existe, on prévient l'utilisateur
* La clé est démonté et prête à être retiré

**Comment by maditnerd** [comment]
Restauration
===

Revenir à une version précédente depuis une clé USB
===
* Tapez sudo configurer
* Appuyez sur Restauration

Votre configuration ainsi que l'état de yana-server vont être remis en place.
* Mettez à jour Yana 

Restauration sur une installation neuf de Raspbian
curl -L yana.madnerd.org|sudo bash
* Installer Yana
* Tapez sudo configurer
* Appuyer sur Restauration
* Mettez à jour YANA

**Comment by maditnerd** [comment]
Configuration et Mise à jour
===
* Tapez sudo configurer
* Appuyer sur Configurer

![yana06](https://cloud.githubusercontent.com/assets/2841495/12224359/8b6c2a3c-b7ee-11e5-8751-93b3e8563cb9.png)

* Vérifier YANA : Installation sans copie de yana-server
* Mettre à jour YANA : Reset la branche git et la met à jour
* Redimensionner la carte SD : (fait pendant l'installation) lance raspi-config en unattended

Scripts plugins
===
Ce menu permet de gérer des scripts dans les plugins
Si un script est présent dans un plugin (/var/www/yana-server/plugins/example/install.sh)
Il vous sera proposé ici de le lancer dans un menu

Vous pouvez utiliser toutes les fonctions/variables du script d'installation dans votre script.
(voir le code source)

Par exemple si on crée un script /var/www/yana-server/plugins/radioRelay/install.sh
Le script radioRelay/install.sh sera proposé
Voici un example de script
````
verifyRoot #Verifie sur root
if [[ $isRoot -eq 1 ]];then
   echo "ROOT OK"
   #Donne les droits d'éxecution à radioEmission
   giveRootPermissions /var/www/yana-server/plugins/radioRelay/radioEmission
   echo -e "$OK Adresse IP: $IPADDRESS $NORMAL"
fi
````

**Comment by maditnerd** [comment]
Bon, je suis vanné, je remet le commit à demain histoire de rien casser, si vous voulez jouer avec le script
Il est ici provisoirement si ça vous intéresse: 
> https://gist.github.com/maditnerd/bcc3f9d0a9c59e868c95

**Comment by ldleman** [comment]
Tain tu met du temps a chauffer mais quand t'es lancé tu fait pas semblant ! :D 
Bien joué en tout cas ! :) Tiens moi au jus quand t'aura fait le commit final je copierais la doc sur le wiki officiel (si tu veux tu peux mettre le script d'install direct sur le github officiel aussi histoire qu'on ai tout au même endroit).

**Comment by maditnerd** [comment]
OK, j'ai envoyé le script sur le repo, j'en est profité pour rajouter un programme/script qui permet de récupérer le code de la télécommande dans radioRelay.
Il est accessible directement dans l'installeur (c'était histoire d'avoir un exemple pour les scripts plugins).

**Comment by ldleman** [comment]
T'es un chef !!! :)

**Comment by ldleman** [comment]
Du coup je clos le topic. Pour la doc tu veux la transcrire sur le wiki madit ? T'as les code du wiki je sais plus ?

**Comment by Singman33** [comment]
Bonjour,
Dans la doc, il est marqué en prérequis un **apache2**, l'installer proposer de mettre **lighttp**, et si on a déjà apache2, il ne met pas la configuration de celui-ci a jour et ne le redémarre pas. Du coup, le reste de l'installation bloque.
Deux solutions : enlever le prérequis Apache, ou bien installer le fichier de config.

**Comment by iPapy** [comment]
Bonsoir,
Visuellement c'est beau rien à dire, maintenant faut que je regarde pour piloter mes éléments telle que mon pont Philips Hue, mon pont Logitech Harmony, ma Google Home et autres objets de chez Xiaomi.
Franchement super boulot
