### ISSUE TITLE
Réponse YANA Switch, Case.

### ISSUE THREAD

**Issue by rol25** [ldleman/yana-server#150]
Salut,
Je rencontre actuellement un problème avec la réponse de YANA lorsque dans un plugin il y a deux fonctions qui contiennent le comparateur swtich, case. YANA répond deux fois alors que callback renvoie sur des fonctions différentes. Exemple:

function exemple_vocal_command(&$response,$actionUrl){
	global $conf;

		$response['commands'][] = array(
		'command'=>$conf->get('VOCAL_ENTITY_NAME').', fait le',
		'callback'=>'menage_cmd_menage',
		'confidence'=>0.8);

		$response['commands'][] = array(
		'command'=>$conf->get('VOCAL_ENTITY_NAME').' met la',
		'callback'=>'table_cmd_table',
		'confidence'=>0.8);
	}

function menage_cmd_menage($text,$confidence,$parameters){
	$cli = new Client();
	$cli->connect();
	switch($text){
		case 'table':
		$cli->talk("J'ai mis la table.");
			
		break;
		default:
			$cli->talk("Je ne peux pas faire le : ".$text);
		break;
	}
	$cli->disconnect();
}

function 'table_cmd_table($text,$confidence,$parameters){
	$cli = new Client();
	$cli->connect();
	switch($text){
		case menage':
		$cli->talk("J'ai mis la table.");
		break;
		default:
			$cli->talk("Je ne peux pas mettre la : ".$text);
		break;
	}
	$cli->disconnect();
}

Si jamais YANA comprend "YANA, met le vaisselle", elle va répondre je ne peux pas faire le vaisselle puis je ne peux pas mettre la vaisselle.

Aurais-tu une idée concernant mon problème ?

PS: J’espère avoir été assez claire ^^.
Amicalement,
Alexandre.

**Comment by ldleman** [comment]
Salut @rol25 , bon reflexe le github mais comme le nouveau client n'est pas encore sortis est ce qu'on peux continuer cette discussion par mail histoire de ne pas perdre les utilisateurs qui sont encore sur l'ancien ? :D 

Je ne suis pas certain que la repetition vienne du switch, je te recontacte apr mail pour en parler.
