### ISSUE TITLE
Dashboard qui disparaît.

### ISSUE THREAD

**Issue by rol25** [ldleman/yana-server#151]
Le dashboard disparaît lorsqu'un autre utilisateur se connecte à YANA et utilise son dashboard.

Amicalement,
Roland Alexandre.

**Comment by ldleman** [comment]
Résolu dans le commit 2a4ad3cd7163a9cfeea1d4e4012cc01311947b82 peux tu me confirmer que c'est bon ?

**Comment by rol25** [comment]
Après essaie je te confirme que je n'ai plus de problème. =)

**Comment by ldleman** [comment]
Parfait :) ! Merci d'avoir signalé le soucis, je clos donc ce bug.
