### ISSUE TITLE
Probleme de fonctionnement des commmandes pour android & iPhone

### ISSUE THREAD

**Issue by HARRYJC** [ldleman/yana-server#152]
ANDROID : Echec de compréhension par rapport à la réponse du Raspberry Pi. Veuillez présenter le problème à Nover"
IPHONE, bug équivalemment, pas de mise a jours de la "liste des commandes" pas de possibilité de passer en speech l'application plante. desinstallation, reboot, reinstallation ... KO

ceci depuis la mise a jour via git et le dernier commit eabbaa897e929196b2a67f0271a5aac564a2bfef
y a t-il un log pour vous aidez ? 

Merci

**Comment by ldleman** [comment]
Salut :), 

Peux tu préciser a quel moment l'application plante ? Quand elle démarre
? Quand tu lance une commande vocale ? 

Le commit eabbaa8 ne touche normalement aucun fichier ou block de code
sensible pour les clients génération v1 (donc l'appli android et
iphone). 

J'ignore si il existe des logs coté android/iphone le mieux c'est de se
rapprocher de nover 

Coté yana-server un log existe dans /var/log/apache OU
lighttpd/error.log 

Tiens moi au jus ! :) 

Le 2015-11-04 08:41, HARRYJC a écrit : 

> ANDROID : Echec de compréhension par rapport à la réponse du Raspberry Pi. Veuillez présenter le problème à Nover"
> IPHONE, bug équivalemment, pas de mise a jours de la "liste des commandes" pas de possibilité de passer en speech l'application plante. desinstallation, reboot, reinstallation ... KO 
> 
> ceci depuis la mise a jour via git et le dernier commit eabbaa8 [1]
> y a t-il un log pour vous aidez ? 
> 
> Merci 
> 
> --
> Reply to this email directly or view it on GitHub [2].

  

Links:
------
[1]
https://github.com/ldleman/yana-server/commit/eabbaa897e929196b2a67f0271a5aac564a2bfef
[2] https://github.com/ldleman/yana-server/issues/152

**Comment by HARRYJC** [comment]
bonjour,
plugin a prevoir, 
-> logs des connections et actions des BOYD dans yana serait une aide au debug :-)

apres reboot, pour etre neutre sur la conf..

voici le log, mais seulement coté apache, 
[Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
[Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
[Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
[Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?init=1
[Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1
[Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1
[Sat Nov 07 08:30:18 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/templates/default/img/ui-bg_flat_75_ffffff_40x100.png, referer: http://172.17.35.91/yana-server/templates/default/css/jquery-ui-1.10.3.custom.css
[Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
[Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
[Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
[Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/setting.php?section=profil
[Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/setting.php?section=profil
[Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/setting.php?section=profil
[Sat Nov 07 08:30:48 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:30:48 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:30:49 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:32:07 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/templates/default/img/ui-bg_flat_75_ffffff_40x100.png, referer: http://172.17.35.91/yana-server/templates/default/css/jquery-ui-1.10.3.custom.css

plugin Meteo supprimé

^[[A^[[A


 [ ? ]  alsa-utils
 [ ? ]  bootmisc.sh
 [ ? ]  checkfs.sh
 [ ? ]  checkroot-bootclean.sh
 [ ? ]  dphys-swapfile
 [ ? ]  fake-hwclock
 [ ? ]  gpio_init.sh
 [ ? ]  hwclock.sh
 [ ? ]  killprocs
 [ ? ]  kmod
 [ ? ]  motion
 [ ? ]  motion.old
 [ ? ]  motion.save
 [ ? ]  mountall-bootclean.sh
 [ ? ]  mountall.sh
 [ ? ]  mountdevsubfs.sh
 [ ? ]  mountkernfs.sh
 [ ? ]  mountnfs-bootclean.sh
 [ ? ]  mountnfs.sh
 [ ? ]  mtab.sh
 [ ? ]  mysql
 [ ? ]  networking
 [ ? ]  plymouth
 [ ? ]  plymouth-log
 [ ? ]  raspi-config
 [ ? ]  rc.local
 [ ? ]  sendsigs
 [ ? ]  udev-mtab
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot
[Sat Nov 07 08:38:24 2015] [error] [client 172.17.35.21] PHP Warning:  SQLite3::exec(): database is locked in /var/www/yana-server/classes/SQLiteEntity.class.php on line 215, referer: http://172.17.35.91/yana-server/index.php
[Sat Nov 07 08:38:24 2015] [error] [client 192.168.1.88] PHP Warning:  SQLite3::query(): Unable to prepare statement: 5, database is locked in /var/www/yana-server/classes/SQLiteEntity.class.php on line 264
[Sat Nov 07 08:38:24 2015] [error] [client 192.168.1.88] PHP Fatal error:  Call to a member function fetchArray() on a non-object in /var/www/yana-server/classes/SQLiteEntity.class.php on line 268
 [ ? ]  alsa-utils
 [ ? ]  bootmisc.sh
 [ ? ]  checkfs.sh
 [ ? ]  checkroot-bootclean.sh
 [ ? ]  dphys-swapfile
 [ ? ]  fake-hwclock
 [ ? ]  gpio_init.sh
 [ ? ]  hwclock.sh
 [ ? ]  killprocs
 [ ? ]  kmod
 [ ? ]  motion
 [ ? ]  motion.old
 [ ? ]  motion.save
 [ ? ]  mountall-bootclean.sh
 [ ? ]  mountall.sh
 [ ? ]  mountdevsubfs.sh
 [ ? ]  mountkernfs.sh
 [ ? ]  mountnfs-bootclean.sh
 [ ? ]  mountnfs.sh
 [ ? ]  mtab.sh
 [ ? ]  mysql
 [ ? ]  networking
 [ ? ]  plymouth
 [ ? ]  plymouth-log
 [ ? ]  raspi-config
 [ ? ]  rc.local
 [ ? ]  sendsigs
 [ ? ]  udev-mtab
 [ ? ]  umountfs
 [ ? ]  umountnfs.sh
 [ ? ]  umountroot

j'en deduis que c'est plutot l'update du GIt PULL qui c'est mal passé.. 

Est-ce que tu veux que reinstall from scratch ?
Veux tu valider un script d'update a fournir pour les evolutions via GIT PULL ?
Merci a toi

**Comment by HARRYJC** [comment]
quelle est l'url (webservice) a effectuer a distance dans le navigateur pour avoir la liste des commandes ? 
http://IP_yana-server/yana-server/???????.php? 
je pourrai savoir si cela via du server ou des BYOD 
Merci

**Comment by HARRYJC** [comment]
je peux aussi te donner les droits d'acceder au raspberry, via RDS (authentification), si tu en as besoin.
Merci

**Comment by ldleman** [comment]
Ta base sqlite (/var/www/db/.database.db est verrouillée a cause d'une
mauvaise manip, essaye de la débloquer avec les astuces de ce topic [2] 

Le 2015-11-07 08:47, HARRYJC a écrit : 

> bonjour,
> plugin a prevoir, 
> -> logs des connections et actions des BOYD dans yana serait une aide au debug :-) 
> 
> apres reboot, pour etre neutre sur la conf.. 
> 
> voici le log, mais seulement coté apache, 
> [Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
> [Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
> [Sat Nov 07 08:30:06 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1&error=le+compte+sp%C3%A9cifi%C3%A9+est+inexistant
> [Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?init=1
> [Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1
> [Sat Nov 07 08:30:15 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?init=1
> [Sat Nov 07 08:30:18 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/templates/default/img/ui-bg_flat_75_ffffff_40x100.png, referer: http://172.17.35.91/yana-server/templates/default/css/jquery-ui-1.10.3.custom.css
> [Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
> [Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
> [Sat Nov 07 08:30:21 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php?module=eventmanager
> [Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:30:23 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/setting.php?section=profil
> [Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/setting.php?section=profil
> [Sat Nov 07 08:30:44 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/setting.php?section=profil
> [Sat Nov 07 08:30:48 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/css, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:30:48 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:30:49 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/plugins/meteo/js, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:32:07 2015] [error] [client 172.17.35.21] File does not exist: /var/www/yana-server/templates/default/img/ui-bg_flat_75_ffffff_40x100.png, referer: http://172.17.35.91/yana-server/templates/default/css/jquery-ui-1.10.3.custom.css 
> 
> plugin Meteo supprimé 
> 
> ^[[A^[[A 
> 
> [ ? ] alsa-utils
> [ ? ] bootmisc.sh
> [ ? ] checkfs.sh
> [ ? ] checkroot-bootclean.sh
> [ ? ] dphys-swapfile
> [ ? ] fake-hwclock
> [ ? ] gpio_init.sh
> [ ? ] hwclock.sh
> [ ? ] killprocs
> [ ? ] kmod
> [ ? ] motion
> [ ? ] motion.old
> [ ? ] motion.save
> [ ? ] mountall-bootclean.sh
> [ ? ] mountall.sh
> [ ? ] mountdevsubfs.sh
> [ ? ] mountkernfs.sh
> [ ? ] mountnfs-bootclean.sh
> [ ? ] mountnfs.sh
> [ ? ] mtab.sh
> [ ? ] mysql
> [ ? ] networking
> [ ? ] plymouth
> [ ? ] plymouth-log
> [ ? ] raspi-config
> [ ? ] rc.local
> [ ? ] sendsigs
> [ ? ] udev-mtab
> [ ? ] umountfs
> [ ? ] umountnfs.sh
> [ ? ] umountroot
> [Sat Nov 07 08:38:24 2015] [error] [client 172.17.35.21] PHP Warning: SQLite3::exec(): database is locked in /var/www/yana-server/classes/SQLiteEntity.class.php on line 215, referer: http://172.17.35.91/yana-server/index.php
> [Sat Nov 07 08:38:24 2015] [error] [client 192.168.1.88] PHP Warning: SQLite3::query(): Unable to prepare statement: 5, database is locked in /var/www/yana-server/classes/SQLiteEntity.class.php on line 264
> [Sat Nov 07 08:38:24 2015] [error] [client 192.168.1.88] PHP Fatal error: Call to a member function fetchArray() on a non-object in /var/www/yana-server/classes/SQLiteEntity.class.php on line 268
> [ ? ] alsa-utils
> [ ? ] bootmisc.sh
> [ ? ] checkfs.sh
> [ ? ] checkroot-bootclean.sh
> [ ? ] dphys-swapfile
> [ ? ] fake-hwclock
> [ ? ] gpio_init.sh
> [ ? ] hwclock.sh
> [ ? ] killprocs
> [ ? ] kmod
> [ ? ] motion
> [ ? ] motion.old
> [ ? ] motion.save
> [ ? ] mountall-bootclean.sh
> [ ? ] mountall.sh
> [ ? ] mountdevsubfs.sh
> [ ? ] mountkernfs.sh
> [ ? ] mountnfs-bootclean.sh
> [ ? ] mountnfs.sh
> [ ? ] mtab.sh
> [ ? ] mysql
> [ ? ] networking
> [ ? ] plymouth
> [ ? ] plymouth-log
> [ ? ] raspi-config
> [ ? ] rc.local
> [ ? ] sendsigs
> [ ? ] udev-mtab
> [ ? ] umountfs
> [ ? ] umountnfs.sh
> [ ? ] umountroot 
> 
> j'en deduis que c'est plutot l'update du GIt PULL qui c'est mal passé.. 
> 
> Est-ce que tu veux que reinstall from scratch ?
> Veux tu valider un script d'update a fournir pour les evolutions via GIT PULL ?
> Merci a toi 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1]
https://github.com/ldleman/yana-server/issues/152#issuecomment-154651280
[2]
http://stackoverflow.com/questions/151026/how-do-i-unlock-a-sqlite-database

**Comment by HARRYJC** [comment]
Je cloture le ticket. j'ai fais une restoration du system.
je ferai un test git pull plus tard
Si tu as bseoin de faire des validations sur une futur version ou sur YDLE (iphone/android)
Contact moi.
Merci Valentin

**Comment by parrain27** [comment]
perso suis un noob moyen d'avoir un petit tuto rapido 
merci d'avance :)

**Comment by hv3l** [comment]
My apologies for the fact that I don't speek French, but I installed the Yana server on raspberry pi today and I also installed the domoticz plugin and I can connect to my domoticz server. It also shows my commandes vocales from the domoticz. 

Unfortunally I found the following error in the var/log/lighttpd/error.log:
2016-02-10 21:25:02: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning:  SQLite3::query(): Unable to prepare statement: 5, database is locked in /var/www/yana-server/classes/SQLiteEntity.class.php on line 295
2016-02-10 21:25:02: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error:  Call to a member function fetchArray() on boolean in /var/www/yana-server/classes/SQLiteEntity.class.php on line 299

There are no processes which locks the .database.db and also the command cho ".dump" | sqlite3 old.db | sqlite3 new.db doesn't resolve the issue.

Any clues ?

Merci d'avance
Hans

**Comment by MelloXVI** [comment]
Hey salut, je viens d'installer aussi Yana server pour le coupler avec domoticz ! 
Malheureusement, je possède la même erreur que notre compère anglais

Avez vous des idées, O grand maitre idleman ? Et les autres, merci =)

(En tentant une réinstallation j'ai eu ces erreurs ....)
