### ISSUE TITLE
Problème liaison entre client et serveur (Client Yana4all Beta)

### ISSUE THREAD

**Issue by demlight** [ldleman/yana-server#164]
Bonjour Idle !

Tout d’abord, merci du nouveau client, il a l’air fonctionnel et plus joli ^^

Cependant, je rencontre un petit problème, apparemment le client n’arrive pas à se connecter au serveur, avec le socket.php exécuter sur le serveur bien sur :

http://img15.hostingpics.net/pics/498765pbyanasocket.png

Merci d’avance !

**Comment by ldleman** [comment]
Yop !

Visiblement le serveur est inaccessible, vérifie que tu peux accéder en telnet a ton serveur depuis ton poste en ouvrant une commande DOS et en tapant:

```shell
telnet  192.168.0.25 9999
```
(si telnet n'est pas reconnus, active le client telnet dans les composants windows)

Vérifie que le port 9999 n'est pas bloqué par un firewall ou un routeur quelquonque sur ton réseau

Assure toi que ton rpi dispose bien de l'ip 192.168.0.25 via la commande shell
```shell
ifconfig
```
Assure toi également que ton PC est bien sur le même réseau local que ton rpi (étant donné que tu utilise l'ip LAN)

Tiens moi au jus des tests :)

**Comment by demlight** [comment]
Re !

D'accord, je peux y accéder par SSH forcément, je vais installer telnet, je ne savais pas que le nouveau client utilisait le protocole telnet ^^

Merci !

**Comment by ldleman** [comment]
Le nouveau client n'utilise pas telnet mais les sockets, telnet est un simple outil permettant de vérifier que la liaison socket ip/port est disponible entre ton pc et le serveur (voir si c'est un problème de réseau au autre chose).

**Comment by ldleman** [comment]
@demlight  des nouvelles ? Je peux clore?

**Comment by demlight** [comment]
Oui excuse moi !

J'avais simplement pas régler mes règles iptables et pas ouvert le port 9999 sur ma Freebox ^^

D'autres part, j'ai mis la commande "sudo php /var/www/yana-server/socket.php" dans un peit script dans /etc/init.d/ (puis je l'ai activer au boot avec "update-rc.d script defaults")

Même au reboot, je peux accéder au nouveau client sans "allumer" le socket à partir du RaspBerry

Encore merci pour tout ce que tu fais Idle !

**Comment by ldleman** [comment]
Niquel je clos alors :).
Effectivement pour le script, faut que je pense a en proposer un offi.
