### ISSUE TITLE
probleme pas de socket.php

### ISSUE THREAD

**Issue by rikimaruneo** [ldleman/yana-server#166]
voila j'ai mis a jour
essaye de lancer le serveur mais voila rien snif

pi@raspberrypi:~ $ /var/www/yana-server/socket.php
bash: /var/www/yana-server/socket.php: Aucun fichier ou dossier de ce type
pi@raspberrypi:~ $ cd /var/www/yana-server
pi@raspberrypi:/var/www/yana-server $ sudo git pull
Already up-to-date.
pi@raspberrypi:/var/www/yana-server $ /var/www/yana-server/socket.php
bash: /var/www/yana-server/socket.php: Aucun fichier ou dossier de ce type
pi@raspberrypi:/var/www/yana-server $ cd
pi@raspberrypi:~ $ sudo apt-get install php5-cli
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
php5-cli est déjà la plus récente version disponible.
0 mis à jour, 0 nouvellement installés, 0 à enlever et 21 non mis à jour.

si j'ai oublier quelque chose merci de m'aidé
bonne soirée

**Comment by gwenoleR** [comment]
Hello, 
Si tu fais un <code> cd /var/www/yana-server </code> puis un <code>ls</code> ca donne quoi ?

**Comment by gwenoleR** [comment]
Attention, il semble que tu n'utilise pas la bonne commande pour lancer le socket, 
Pour le lancer il faut ajouter le mot <code> php </code> devant la commande, ca te donnerais quelque chose du genre : 
<code>php /var/www/yana-server/socket.php </code>

**Comment by ldleman** [comment]
+1

**Comment by rikimaruneo** [comment]
Bonjour
pour le premier message 
pi@raspberrypi:~ $ cd /var/www/yana-server
pi@raspberrypi:/var/www/yana-server $ ls
404.html    classes       db          index.php    plugins      setting.php
action.php  common.php    footer.php  install.php  RainTPL.php  templates
cache       constant.php  header.php  install.sh   README.md    test.txt


et pour le second
pi@raspberrypi:~ $ php /var/www/yana-server/socket.php
Could not open input file: /var/www/yana-server/socket.php

voila sa ne veut pas fonctionné chez moi

**Comment by ldleman** [comment]
Il te manque le fichier socket.php, essaye de faire un git pull 
```cd /var/www/yana-server && git pull```

**Comment by rikimaruneo** [comment]
mise a jour me dit qur c'est a jour
pi@raspberrypi:~ $ cd /var/www/yana-server && git pull
error: impossible d'ouvrir .git/FETCH_HEAD : Permission non accordée

pi@raspberrypi:/var/www/yana-server $ sudo git pull
Already up-to-date.
pi@raspberrypi:/var/www/yana-server $ cd
pi@raspberrypi:~ $ php /var/www/yana-server/socket.php
Could not open input file: /var/www/yana-server/socket.php

je vais tout reinstaler 

j'avais installé yana avec ce lien
sudo wget https://raw.githubusercontent.com/ldleman/yana-server/master/install.sh && sudo chmod +x install.sh && sudo ./install.sh

je reinstale tout est je vous tiens au courant

**Comment by ldleman** [comment]
Oui c'est étrange le fichier socket.php est pourtant bien sur le dépot git, a mon avis il se plante dans les MAJ je ne vois que ça.

**Comment by rikimaruneo** [comment]
J'ai tout réinstaller
Et miracle sa marche merci les gars
