### ISSUE TITLE
Yana-android / Store Android

### ISSUE THREAD

**Issue by ruf147** [ldleman/yana-server#169]
Bonjour,

il m' est impossible de telecharger l' apps Yana v2 sur le store : 

 https://play.google.com/store/apps/details?id=alexandreroland.yana 
=
We're sorry, the requested URL was not found on this server.

**Comment by ldleman** [comment]
Salut :) 
L'application d’Alexandre à été temporairement bannie par google car celui pensais qu'il violait les droits d'auteur de nover (concepteur de l'application v1) ben oui il sont un peu juste chez google ^^.

Du coup vas falloir être patient le temps qu'alexandre règle le quiproquo ou lui demander direct l'application sans passer par le store

**Comment by ruf147** [comment]
Ok merci à toi.

**Comment by ldleman** [comment]
On est en train de voir pour mettre une version temporaire sur mon cloud en attendant que ça se règle :)

**Comment by ruf147** [comment]
Ca marche :D

**Comment by ldleman** [comment]
https://cloud.idleman.fr/index.php/s/TtU3zZVzoxMGAUK

**Comment by ruf147** [comment]
Merci m'sieur, tout fonctionne parfaitement.

**Comment by ldleman** [comment]
Niquel, je clos le topic :)
