### ISSUE TITLE
Erreur de configuration sur l'interface web de Yana-Server

### ISSUE THREAD

**Issue by ultraalus** [ldleman/yana-server#173]
Bonjour à tous, tous d'abord merci à Idleman d'avoir adapté la version de Sarah au Raspberry Pi.
Voilà mon problème:
J'avais installé Yana une première fois, et ayant un micro assez rudimentaire, j'ai baissé les taux de sensibilité de la voix dans l'interface web dans Configuration -> Préférences -> Informations Vocales. Mais je ne sais plus pour quelles raisons, passons, j'ai voulu réinstaller Yana. Et depuis, lorsque je vais dans Informations Vocales, je tombe sur cette page : http://prntscr.com/9rrp5f .
Si une âme charitable est partante pour m'aider, j'accepterai volontiers.
Merci d'avance.

Louis L.

**Comment by ldleman** [comment]
oO tu devrait avoir exactement cette page mais avec un tableau  des commandes/sensibilités justes au dessus.
Vérifie les logs d'erreur apache avec un
``` tail -f /var/logs/apache2/error.log ```
Vérifie également la présence du fichier cmd.json dans plugins/vocal_infos et que ce fichier contient bien les commandes.

Une réinstallation du plugin après un git pull ne serait pas de trop si tu veux mon avis :)

**Comment by ldleman** [comment]
@ultraalus  du nouveau sur ce problème ? Je peux clore ?
