### ISSUE TITLE
Probleme redimensionnement carte SD

### ISSUE THREAD

**Issue by Aryombre** [ldleman/yana-server#174]
Bonjour à tous, 
Merci beaucoup à Idleman, sur le blog duquel j'ai bavé depuis quelques semaines avant de me lancer
J'ai essayé d'installer Yana (installeur automatique, parce que je viens à peine de découvrir Linux) et il y a apparemment un probleme avec la carte SD, l'installeur se bloque sur "Verification du redimensionnement de la carte SD"
C'est une carte microSD de 64 GB que j'avais reformatté en FAT32 pour que la raspberry puisse booter dessus, le problème est peut-être du à ça.
Ou alors j'ai juste fait une connerie...

**Comment by maditnerd** [comment]
Est-ce que tu as copié Raspbian Wheezie ou Jessie sur la carte SD ?

Pour redimensionner la carte SD, j'ai utilisé raspi-config
Mais maintenant j'ai un doute, peut être que sur la wheezie, raspi-config ne permettait pas de le faire (ce qui fait qu'il essaye d'afficher le menu de raspi-config plutôt que redimensionner la carte sd et bloque)

Peut-tu essayer de mettre à jour ton Raspberry Pi avant de lancer l'installeur ?
> sudo apt-get update
> sudo apt-get upgrade

Dans tout les cas , je vais tester et corriger ça au plus vite ^^
Merci pour le retour !

**Comment by maditnerd** [comment]
J'ai testé avec une carte SD de 32go sur wheezie et jessie et tout semble fonctionnel.

Je n'ai malheureusement pas de carte de 64go pour essayer, mais j'ai mis à jour le script d'installation afin de pouvoir passer le redimensionnement de la carte.

**Comment by Aryombre** [comment]
J'avais pris Jessie, avec NOOBS, que j'avais téléchargé sur le site de raspberry.
J'avais aussi déjà mis à jour avant de lancer l'installeur.
J'essaie avel la correction ce soir, merci beaucoup !

**Comment by ldleman** [comment]
Coucou @Aryombre, je clos ce post pour fair eun peu de ménage, je t'invite a rouvrir un post en décrivant le problème sur ton client windows si celui ci est encore d'actualité :)
