### ISSUE TITLE
relais filaire et relais radio impossible a faire fonctionner...

### ISSUE THREAD

**Issue by ruf147** [ldleman/yana-server#176]
Bonsoir à tous.

Je viens vers vous car, étant une grosse bille en électronique, il m' est impossible de faire fonctionner tels relais radio ou filaire avec mon raspberry, hors, allumer une led, il n' y a aucun problème.

Je pense, je dis biens je pense car comme je le redis je suis une bille en électronique, avoir tenter tous les branchements sur n' importe quels relais.

J' avoue que en ce moment je tente avec les prise chacon mais bon si meme avec les filaires rien ne fonctionne, je n imagine meme pas avec les radios.... (ce qui je le precise, je n arrive pas a faire fonctionner).

J ai vraiment besoin d aide de la part de n importe qui. Je deviens accros au blog d idleman et faire de mon appart un monde domotique, je ne demande que ca... 

N' hésitez pas a me demander n' importe quel photos ou autres de mes branchements, ou de mon matos achetez ( le meme qu' idle, de ses tutos en tout cas) pour avancer dans ce &€%#@ d' électronique.

Dans l' attente d' une âme charitable pour me faire avancer...

See u

**Comment by ruf147** [comment]
Je vais me commenter un peu tout seul, peut-être que cela va faire venir du monde : D

Alors tout d'abord, j'ai pris quelques photos de mon matos, si cela peut déjà eguyer les gens, sauf de mes framboises (j'en ai deux) un raspberry Pi 1 model B+ et un raspberry Pi 2 Model B (tous mes tests sont portés sur le raspberry Pi 2).
J' ai entendu tellement de fois sur google des histoires de résistance ou d'optocoupleur, de tension et autres à en perdre son latin, et me dis que je suis peut-être dans le même cas...

![wp_20160202_14_51_10_pro](https://cloud.githubusercontent.com/assets/16617233/12751772/58893758-c9bf-11e5-9489-6d856795d27f.jpg)
_Mes relais filaire_
Le x8 a grillé... (Paix a son âme) j'ai fait sauter les plonds 2 fois avec avant qu'il ne fonctionne plus.
Le x4 lui fonctionne, selon les branchements des câbles, ma lampe reste allumée ou éteinte... Le rpi ne l'éteint pas où ne l'allume pas.

![wp_20160202_14_51_51_pro](https://cloud.githubusercontent.com/assets/16617233/12751797/7edfb486-c9bf-11e5-92a3-3421c924ffcb.jpg)
_Mes relais radio_
Je ne fais que les contempler pour le moment :'( 

![wp_20160202_14_52_09_pro](https://cloud.githubusercontent.com/assets/16617233/12751854/bec8ca2e-c9bf-11e5-8a15-a8a58d9c4ae0.jpg)
_Mes câbles, ainsi que quelques diodes._
Mes fameuses petites diodes, et là où j'en perds mon latin, c'est qu'elle, branché en direct sur le rpi, fonctionne très bien, que ce soit en ligne de commande ou avec Yana....

![wp_20160202_14_54_56_pro](https://cloud.githubusercontent.com/assets/16617233/12751869/dae17a94-c9bf-11e5-98b3-598871854ede.jpg)
_Mes prises CHACON _
(il y en a bien deux autres, mais pour le moment je les utilise avec la telecommande)

![wp_20160202_14_52_35_pro](https://cloud.githubusercontent.com/assets/16617233/12751884/f59296ca-c9bf-11e5-9347-8c79d5666202.jpg)
_Un vieux câble USB_ 
il trainait, je l' ai retransformé en alim pour les relais (j'avoue qu'elle est un peu craignos) 

Voila ont a deja tout ca. 
Je tiens aussi à préciser, même si cela ne reste pas si important que ça, est que je ne debute pas sous Linux (et encore moins avec le rpi...) mon problème reste bien porter sur l'électronique. Enfin je pense.

Je suis un peu pris par mon travail en ce moment mais je compte bien vous envoyer quelques screen avec tous les éléments branchés que vous vous fassiez une petite idée.
Dans l'attente de vous

**Comment by ldleman** [comment]
Yop ! :)
Je pense que pour résoudre le problème, il te faut commencer par un montage le plus simple possible du type : un pin gpio de ton rpi connecté en filaire a une PIN commande de ton relais survivant, et utilisation de la commande gpio write <n°pin> 1 voir si ça réagis.

Le fait que la LED fonctionne et pas le relais laisse penser que ta tension de sortie GPIO (3.3v) est trop faible pour faire réagir la commande de ton relais (regarder dans la doc de celui ci la tension d'entrée de bascule).

Tiens moi au jus pour le test et si tu peux montre nous le schéma que tu met en œuvre ( sur les photos on ne vois généralement rien dès qu'il y a plus de 3 fils)

**Comment by ruf147** [comment]
Merci pour ta réponse très rapide :)
Donc ce que tu proposes c'est de brancher le relais à vide au rpi pour voir si je peux entendre le claque d'ouverture ou de fermeture?
Pas bete : D
Je ne suis plus à côté du rpi mais je te remonte les résultats au plus vite.
Pour ce qui est du schéma, je vais essayer de le faire temps bien que mal en suivant les tiens (par exemple, car j'avoue ne jamais avoir fait de schémas comme ça, seront-ils compréhensible, à voir...)

**Comment by ldleman** [comment]
Oui c'est ça, le clac de fermeture ou la led associée sur le relais.
Le but c'est surtout de savoir si, comme je le soupçonne, ta tension de sortie GPIO est trop faible pour ta tension d'entrée relais, auquel cas il te faudra passer par un mosfet ou autre composant tiers pour concilier les deux.

**Comment by ruf147** [comment]
Ok, je m' y colle ce soir en rentrant. En espérant faire fonctionner tout ca. Merci a toi en tout cas 😁

**Comment by ruf147** [comment]
Hey!

Bon, le verdict tombe, mais je sais pas vraiment si c'est bon signe...
Donc, quand je branche le relais x4 sur le rpi, comme un barbare en l'alimentant direct en 3,3V, voila ce qui sa passe en photo:

![wp_20160204_02_16_27_pro](https://cloud.githubusercontent.com/assets/16617233/12802933/bb98854c-cae6-11e5-9f01-29eee8633fcf.jpg)
gpio write 7 1

![wp_20160204_02_16_39_pro](https://cloud.githubusercontent.com/assets/16617233/12802970/05991788-cae7-11e5-85c6-b1c90cbb2603.jpg)
gpio write 7 0

J' ai mis la LED en fond car même branché, useless, elle sert à rien, pas de réaction...
Et pour ce qui est du relais, quand je lance les commandes, aucun "CLIC, CLAC ou CLOC"... malgré la LED verte presente sur le relais qui me précise (je suppose) que le courant passe (ou pas...).

Alors docteur ?

PS : au passage, j'ai tenté d'alimenter le relais en 5 V, rien ne fonctionne mieu....

**Comment by ldleman** [comment]
A voir avec la doc du relais mais classiquement si la led est allumée, le bloc relais est censé être alimenté je penche donc pour l'un des problèmes suivants : 

- Le relais disfonctionne
- Le relais n'est pas alimenté (partie puissance) avec une tension/intensité sufissante (voir doc) la led verte me  paraissant faible par rapport a la rouge ce qui pourrait indiquer un faible courant dans le bloc relais.

Je penche plus pour le point 2.

Le fait que la led verte s'allume semble indiquer que le soucis ne viens pas du rpi, du branchement ou de la commande mais d'une histoire de tension ou de relais.

As tu essayé d'alimenter ton relais avec une alim externe ou utilise tu l'alim du rpi ? Ca pourrait venir de là car les pin 3 et 5v du rpi sont très mauvais pour alimenter des composants un peu gourmands comme les relais.

Essaye de faire ton test en branchant une alim externe (ex un chargeur de portable en 5v) au relais.

Le schema de branchement c'est : 
- le `+` de l'alim au `+` du relais
- le `-` de l'alime au `-` du relais
- le `-` du relais au `-` du rpi
- le `gpio `du rpi au pin `data` du relais

**Comment by chriskross** [comment]
Bonsoir,
je sais un rapide passage pour t aider à résoudre ton pb. 
concernant les relais présents sur ta carte, je confirme les dires de idleman, commutation sur 5vcc uniquement. 
pour éclairer tes lanternes,je te mets un petit schéma  : https://www.google.fr/imgres?imgurl=http%3A%2F%2Fcompcar.ru%2Fforum%2Fattachment.php%3Fattachmentid%3D13815%26d%3D1326316572&imgrefurl=http%3A%2F%2Fcompcar.ru%2Fforum%2Fshowthread.php%3Ft%3D5968%26page%3D6&docid=WgctBg1bq3vQIM&tbnid=qkSobs4qiXhEeM%3A&w=800&h=303&ved=0ahUKEwjsm6fg7N7KAhXLSRoKHTr_AGUQxiAIBTAB&iact=c&ictx=1

donc comme tu peux le voir,

cas numero 1, jumper en place : 
 optocoupleur est alimenté en 5vcc.
 il attend donc une tension de 5vcc pour être bloqué. ce qui permettra de bloquer le trasistor du deuxième étage Q1. donc faire commuter le relai

chose impossible si ton entrée est en 3.3vcc (rpi)

donc cas numero 2, retrait du jumper  :  

alimentions des optocoupleurs et relais indépendantes. alimentation des optocoupleurs en 3.3vcc = borne vdd /  pour les relais 5vcc = borne  jd-vcc / une = les masses sont communes.

**Comment by ruf147** [comment]
Bonjour à vous...

Bon suite au dernier poste de @ldleman, qui me précisait de regarder le doc. Je me suis rappelé qu'à l'achat, je n'en avais pas eu (J' achete tous mes relais dans un petit magazin d'électronique spécialisé ARDUINO). 
Du coup, ni une ni deux, je m'empresse de retourner au magasin avec mes relais pour avoir le doc, et là il s'avère que ça Co@""#&%... de femme m'avait vendu un relais x4 12 volts, et non 5... rassurés, je lui achete un 5v et là, comme par magie, tout fonctionne, enfin oui et non, mais je vais rouvrir un poste pour ça.

Juste une petite question, maintenant j'ai un relais x4-12v qui me reste sur les bras, que puis-je en faire et surtout comment le faire fonctionner....

En tout cas merci à @ldleman et @chriskross pour vos indications très précises et très rapides....

**Comment by chriskross** [comment]
salut @ruf147 

Si tu as bien compris la réponse que je t'ai transmis et surtout si ta carte relais possède un jumper pour dissocier la partie commande (généralement optocoupleur), de la partie puissance ( transistor de commande + relai).
Tu peux très bien te servir de cette carte, il faudra simplement que tu alimentes ta broche JD-VCC en +12V et évidement toujours relier les masses (GND) en elles. Ne fait pas attention aux résistances, elles sont remplacées par un optocoupleur sur ta carte. 

<img src=http://i.imgur.com/burQmD3.png>

Je te donne une petite astuce pour ta fabriqué un petite alimentation pas cher (généralement de la récupération) qui fournit toutes les tensions qui te seront utiles (3.3v - 5v - 12v - (-)12v - 24v).
Il te suffit pour ça de recycler une vieille alim ATX. 
Pour t'aider tu peux suivre le lien ci-dessous.
Sinon une alim de dd externe fait en général  12v, ou alors une alim sur-mesure en vente sur ton bon site marchand comme Ebxxxx.... 

<H2>la solution sur-mesure</H2>
<img src=http://i.ebayimg.com/00/s/MTIwMFgxMjAw/z/qUgAAOSwnGJWTEff/$_57.JPG> 

<H2>la solution ATX</H2>
<img src=http://w>ww.latelierdugeek.fr/wp-content/uploads/2013/05/alimentation-pc-transformee-alim-atelier.jpg>

http://www.latelierdugeek.fr/2013/05/11/transformer-une-alimentation-de-pc-en-alimentation-datelier

**Comment by ruf147** [comment]
Hello.

Merci @chriskross pour toutes ces infos.
J' ai bien une alimentation qui traîne chez moi, par contre c est une 400w.... Ca va pas être trop gourmand pour l usage prevue?

**Comment by chriskross** [comment]
non elle sera même démesuré pour ton installation ! Une alim qui fournit 12v et quelques ampères (1A voir 2A) aurait été suffisante. mais c bien connu qui peut le plus, peut le moins !

**Comment by ruf147** [comment]
OK, je comprends mais imaginons qu'un jour (pas pour le moment, c'est sur, n'ayant aucune connaissance) j'aurai besoin d'une alim 24 V, je peux très bien en greffer une dessus ?

J' essaie encore de comprendre le schéma, mais je l'avoue avec beaucoup de mal... 
J' ai bien compris que l'on pouvait y mettre du 3,3 du 5 et du 12 V, mais le 24 je bloque un peu, et surtout est ce que cela est utile (si bien sur l'utilisation de relais 24V devait pointer le bout de son nez)?

**Comment by chriskross** [comment]
salut @ruf147,

alors pour répondre à ta question. L'alim ATX transformée en générateur de laboratoire te permettra de générer une alimentation 24volts mais aussi bien d autres tensions. Je m explique comme je te l ai dis dans ma première réponse à ton post, (voir code couleur ci-dessous) ton alim fournit après filtrage redressement et transformation(lissage couplage), les tensions suivantes  :  0V, 3.3V, 5V, 12V et -12V. donc libre à toi de moduler ton potentiel. par exemple, non pas à partir du 0V (gnd) mais d un -12V donc Vsortie =potentiel A-potentiel B donc Vsortie= (12V)- (-12v) donc 24v. tu peux faire Vsortie = 12V - 5V = 7V ect...

<img src=
http://poloastucien.free.fr/con_puis_CM_coul.gif>

Voilà j espère que c un peu plus clair !  ++

**Comment by ruf147** [comment]
Oui merci @chriskross , c' est déjà plus clair!
