### ISSUE TITLE
Problèmes divers suite à mise à jour de Yana-Server

### ISSUE THREAD

**Issue by Toshibs161** [ldleman/yana-server#177]
Bonjour à tous,

Je viens de tenter d'utiliser le nouveau client de YANA, et je rencontre quelques soucis en suivant le tuto d'Idleman (attention, j'approche le niveau 0 en informatique) : 

Quand je lance la commande "sudo php /var/www/yana-server/socket.php", la Raspberry me renvoie la réponse suivante : "[31/01/2016 17:44:55] Could not bind to server". En cherchant un peu sur le github, j'ai essayé d'ouvrir le port 9999 via iptables, mais rien n'y fait !
Pourtant quand le lance le client sur Windows, ça a l'air de se connecter correctement...

Autre problème : je n'arrive plus à faire fonctionner YANA Android (ancienne version de Nover) depuis que j'ai mis à jour Yana-Server. Il me répond : "Echec de compréhension par rapport à la réponse du Raspberry pi". J'ai beau avoir désinstallé/réinstallé l'application, rien n'y fait.

Et enfin (et oui), je n'arrive pas non plus à faire fonctionner la nouvelle version du client Android développé par Alexandre Robert. J'arrive bien à l'installer, le configurer et il a l'air de se connecter correctement (la liste des commandes se met bien à jour). Je teste une commande vocale, mais rien ne se passe...

Voilà, voilà... Merci d'avance pour votre aide !

**Comment by ldleman** [comment]
Yop !
L'application de nover n'est plus compatible avec yana-server depuis passage a la v2.0.

Concernant l'appli d'alexandre, je te suggere de lui en toucher un mot directement, il est en pleine phase de tests sur ce client. 

Pour le premier soucis, regarde si tu n'as pas un soft déjà actif sur le port 9999, au pire change ce port en 9998 dans [socket.php L 289](https://github.com/ldleman/yana-server/blob/master/socket.php#L289) voir si ça viens de là

**Comment by ldleman** [comment]
si tu peux faire un screenshot du résultats de la commande 
`ifconfig `
ça pourrait aider aussi :

**Comment by ruf147** [comment]
Salut, as tu une ROM modifié d' Android?
J' avais un vieux NEXUS non compatible avec la V2, changé de ROM pour le passez en KITKAT, et j' ai eu à peu prés les mêmes probleme que toi.

**Comment by Toshibs161** [comment]
Bonjour à tous et merci pour vos réponses !
Dans l'ordre : 

Idle, j'ai changé le numéro de port conformément à tes conseils et effectivement, ça marche ! Le serveur se lance normalement et les 3 applications (Face, Hear et Mouth) ont l'air d'être connectées. Par contre, j'ai toujours quelques soucis : 
J'ai beaucoup de mal à faire reconnaître une commande vocale. Je pensais que ça venait de la qualité de mon micro (qui n'est certes pas top), mais avec l'ancien client de Yana Windows, ça marche sans souci.
Et les rares fois où la commande est reconnue, je n'ai aucun retour, vocal ou autre.

ruf, ma version d'Android est la version "d'origine" de mon Samsung S6 (Lollipop il me semble). Tu as réussi à t'en sortir malgré tout ?

**Comment by ldleman** [comment]
Essaye d'executer ear.exe avec le parametre -v tu aura plus de logs par rapport a la reconnaissance.
Regarde si ce n'est pas un problème de seuil tout simplement.

Le client v2 utilise la même lib de reco que le v1 donc je ne pense pas que ça vienne du soft en lui même.

**Comment by Toshibs161** [comment]
Salut Idle,

Euh... Au risque de poser une question bête, que veux-tu dire pas "lancer ear.exe avec le paramètre -v" ?

Sinon en fait, quand je lance une commande vocale (par exemple "Quelle heure est-il ?"), il reconnait "Quelle heure est-il les touristes aujourd'hui"

Et encore autre chose (oui, je sais, je suis un peu lourd avec mes questions) : j'ai laissé la voix par défaut que tu as définie (Best-of-Vox Fabienne). Tu l'as téléchargée où ? Ou sinon, comment je peux appliquer la voix Virginie de Scansoft par exemple ?

Encore merci pour ta patience !

**Comment by ldleman** [comment]
> Euh... Au risque de poser une question bête, que veux-tu dire pas "lancer ear.exe avec le paramètre -v" ?
Il n'existe pas de questions bêtes :). il s'agit de lancer l'executable en ligne de commande  avec un argument en plus permettant d'ajouter plus de logs dans la console.

Par exemple si ear.exe se trouve sur ton c: tu peux lancer la commande : 
![cap](https://cloud.githubusercontent.com/assets/2620979/13042221/d50d1674-d3be-11e5-88f5-9ead87df207b.png)

Curieux qu'il reconnaisse autant d emots après ta phrase, t'aurais pas un fort accent du sud par hasard ? :D Plus sérieusement je pense qu'il serait bon d'acheter un micro de meilleur qualité ça pourrait venir de là.

J'ai téléchargé la voix fabienne sur le site best of vox, les vois sont payantes mais très réalistes, si tu veux utiliser virginie tu dois mettre son nom complet dans le fichier conf.json en lieu et place de best of vox fabienne.

**Comment by Toshibs161** [comment]
Salut Idle,
Désolé pour ce retour tardif, mais mon "WAF" ne me permet pas de passer autant de temps sur mon Raspberry que je le voudrais :-)

Bon j'enchaine avec les questions bêtes : je ne dispose en effet pas de la voix de Fabienne de Best of Vox, je suis pour l'instant resté sur la voix de Virginie utilisée avec l'ancien client. Vers quel fichier je dois renvoyer dans le conf.json du coup ?

Sinon, j'ai l'impression que j'ai un problème général avec le nouveau client : les rares fois où YANA reconnait un de mes ordres, il ne se passe rien (et avec l'ancien que j'ai conservé, c'est nickel). C'est d'ailleurs peut-être pour ça que je te disais précédemment que je n'arrivais pas à faire marcher l'application d'Alexandre. J'ai beau avoir essayé de réinstaller plusieurs fois le nouveau client, rien n'y fait. Tu aurais une idée ?

Merci d'avance !

**Comment by poopeye** [comment]
Salut, je me permets de m'immiscer en précisant que j'en quasi au même point. J'ai changé le port et les 3 applis sont conectées. Les commandes vocales sont reconnues mais aucune action résultante, ni de réponde de Yana... Faut-il modifer le port à un autre endroit??
Merci d'avance!

**Comment by ldleman** [comment]
@Toshibs161 tu n'as pas besoin de renvoyer vers un fichier, seul le nom "officiel" de ta voix installé suffit, si tu veux être sur de ne pas te tromper, supprime ton fichier conf et relance le launcher général du client, il te proposera de choisir dans une liste des voix installé.

Il faudrait que tu lance le mode verbose et que tu m'envois les logs affiché après la commande pour que je puisse t'aider d'avantage sur ton pb de reconnaissance, idem pour @poopeye

**Comment by zb2oby** [comment]
pour info j'ai eu exactement les meme souci avec yana4all 
Tout marchais parfaitement mais c'est apres une coupure courant chez moi que les ennuis on commencés. la coupure avait changé toute mes ip. 
Donc, Apres avoir reaffecté toute mes ip (en static cette fois) j'avais essayé tout les clients et seul yana android ne voulait pas fonctionner exactement comme vous le decrivez.
au depart le port me renvoyais l'erreur "could not bind" j'ai cherché de longues heures sans reponse. (j'ai essayé de changer le port, etc etc....)
j'ai contacté alexandre, nous n'avons pas trouvé. 
j'ai finalement du passer par une reinstall complete du serveur en faisant gaffe de bien ouvrir mes ports, de bien lancer le socket et miracle yana android à remarché...

moralité je ne saurait pas vous dire d'ou vient l'erreur mais je sais que pour la régler il a fallu passer par une réinstall propre de l'ensemble...

voila voila apres ce gros coup de démotivation je sors.... ;-)

**Comment by poopeye** [comment]
Bon... Je vais me diriger vers cette solution... Sinon comment as tu réglé
l'erreur "could not bind"? Perso j'ai changé de 9999 à 9998 mais ca
m'intéresse de savoir quand même!

**Comment by zb2oby** [comment]
je pense que le probleme global vient justement de là..apres pourquoi je ne saurait pas l'expliquer... et c'est justement en reinstallant que ce probleme à disparu pour moi et mon client android à enfin pu recommuniquer...
pour les plugins (issues 189) je ne pense pas que les plugins soient incompatibles mais il me semble avoir lu quelque-part qu'il fallait les installer et les activer avant d'installer et de mettre en route les clients auquel cas ils n'étaient pas reconnus.

**Comment by Toshibs161** [comment]
Bonjour à tous,
Désolé pour mon temps de latence...
J'ai pris le temps de réinstaller entièrement Yana-Server et tout marche nickel (Yana4all, Yana-Android version d'Alexandre Robert, etc.) sans que je m'explique vraiment pourquoi ! On peut donc considérer que mon problème est soldé.
Merci à tous pour votre aide en tout cas !

**Comment by ldleman** [comment]
Oki doki, je clos le topic en esperant que ton pb venait simplement d'une vielle install qui merdait quelque part :D n'hésite pas a rouvrir un post si le problème revient
