### ISSUE TITLE
Problème de compréhension scenario

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#179]
Bonjour à tous.
Les scénarii à contrôle vocal fonctionne.
Par contre quand je place */1 * * * * wget http://localhost/yana-server/action.php?action=crontab -O /dev/null 2>&1 dans le crontab (pour utilisation date heure), yana balance le signal toutes les minutes (allumage lampe siplec par radio). J'éteins, ca rallume, etc.
De plus faut il ajouter le token dans cette ligne crontab ?

**Comment by ldleman** [comment]
Tu as quoi comme causes dans ton scénario? :)

**Comment by ingfred** [comment]
J'avais simplement mis une date heure toutes les minutes 17 de chaque heure (il était 15) pour test.
Mais le soucis ne vient a mon avis pas de la car après avoir effacé le scénarion, j'ai eu le même symptome.
Plus de problème après avoir commenté cette ligne du crontab
*/1 * * * * wget "http://localhost/action.php?**action=cronta**b&checker=server&token=7fe69b2f37a3e6d7restdutoken" -O /dev/null 2>&1
A noter : j'ai aussi */1 * * * * wget "http://localhost/action.php?action=GET_EVENT&checker=serve..... dans le crontab. Si les scenarii fonctionne, plus besoin de la gestion d'évenement. Il ne faut peut êtr e pas cumuler les deux.

**Comment by ldleman** [comment]
Tu peux supprimer */1 * * * * wget "http://localhost/action.php?action=GET_EVENT&checker=serve... du crontab si tu le souhaite il ne sert que pour le plugin evenement, cela dis les deux peuvent fonctionner en parallèle.

Tu n'est pas obligé de mettre le token dans le premier cron, en revanche vérifie que ta syntaxe est bien 
```*/1 * * * * wget http://localhost/yana-server/action.php?action=crontab -O /dev/null 2>&1```
Ce cron appelle le script toutes les minutes et la vérification des causes de ton scénario se fait a ce moment là.
Si ton scénario s'enclenche toutes les minutes, c'est que yana penese que toutes les causes de ton scénario sont valide, c'est pourquoi je pense que ça viens d'un bug lié à la cause.

Peux tu faire un screenshot de ta cause ?

**Comment by ingfred** [comment]
il n'y a pas de guillement pour "http://local....token=...."  dans la ligne de crontab ?

**Comment by ingfred** [comment]
![capture du 2016-02-02 16 17 57](https://cloud.githubusercontent.com/assets/8363638/12753728/9592de52-c9c8-11e5-9520-7acdc62d02d8.png)
et voila.

**Comment by ingfred** [comment]
pour info, cette cause donne l'effet phrase sur le client (il dit "test").
Et sur le client android il vient de me répéter trois fois test.
Ton diagnostique semble donc bon. c'est lié à la cause.
quel talent !

**Comment by ldleman** [comment]
Du coup reste a trouver pourquoi ça valide, j'ai reproduit ce test chez moi, de mon coté ça s'active bien uniquement a 18.

Essaye d’exécuter via ton navigateur http://chemin/vers/yana-server/action.php?action=crontab puis affiche moi le log de la dernière action effectuée : 
![2016-02-02 16_31_11-yana server 3 0 6](https://cloud.githubusercontent.com/assets/2620979/12754212/a91dddbc-c9ca-11e5-8656-e48d0ddd678c.png)

**Comment by ingfred** [comment]
Excuses moi j'ai du bosser un peu !
la répétition venait du fait que le scénario s'est recopié plusieur fois ! J'ai tout effacé et recommencé ensuite tout ok (test 2).

**Comment by ldleman** [comment]
Okay, je peux clore donc ?

**Comment by ingfred** [comment]
Oui.
Merci.Il faut faire simplement attention a ne pas cliquer plusieurs fois sur enregistrer le scanario car cela le duplique.
J'ai oublie de te dire que j'ai remis à jour reset origin yana ce matin !
Je continue les tests.
Merci encore.
boulot génial.

**Comment by ldleman** [comment]
Cool :), oui faudrait que je fasse une verif sur les clics compulsifs :D ! 
Content que ça te plaise en tout cas :p
