### ISSUE TITLE
Yana fonctionne mais fait toute à l'envers ...

### ISSUE THREAD

**Issue by ruf147** [ldleman/yana-server#180]
Bonjour;

Encore moi, oui je sais : D

Je viens vers vous aujourd'hui car j'ai un léger souci avec Yana, je pense côté serveur.
Je m'explique, quand je rentre mes commandes relais dans l'interface admin pour une lampe (par exemple), tout est bien pris en compte sauf, que quand je lui demande d'allumer la lampe, elle me l'eteinds, et quand je lui demande de me l' eteindre, elle me l'allume...
Bon aux débuts cela peut être amusant mais a la longue ...

Voili voilà, dans l'attente de vous lire

**Comment by ruf147** [comment]
J' ai oublié de préciser qu'en ligne de commande, tout fonctionne très bien...

**Comment by F0cks** [comment]
Yop @ruf147 !
Sur un relai, en sortie tu as C (com), NC (Normaly Closed) et NO (normaly opened).
Normalement, sur ta lampe tu as deux fils: le fil de masse (0V) et celui qui est relié au relai (sur la broche C). Il faut ensuite connecter ton alimentation à NO.
Explication:
Si ton relai ne reçoit 0V: NC et C sont reliés, ta lampe ne s’allume pas car NC n'est relié à rien.
Si ton relai reçoit le 5V: C'est alors NO et C qui sont reliés, ta lampe s'allume car NO est à l'alim.
(Si jamais ça ne fonctionne pas, si la lampe reste tout le temps allumée ou éteinte avec ce branchement, il suffit de brancher l'alim sur NC et pas NO).

**Comment by ruf147** [comment]
Bonjour,

Merci a toi @F0ckws pour toutes ces précisions et oui effectivement, tout fonctionne normalement ..

Sur ce, une bonne journée 😊
