### ISSUE TITLE
retour sur probleme scenario

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#181]
Bonjour à tous.
J'avais évoqué un problème de scénario qui semblait résolu grace à l'intervention d'Idleman en personne.
J'ai de nouveau eu le soucis après réinstall complète de yana.
En fait c'est le premier scénario de la liste qui se lance toutes les minutes, sauf si c'est un scenario dont la cause est un date/heure.
J'ai fait un scénario allume tout en lancant la commande /var/www/yana-server.plugins/siplec/radioEmission... de messieurs idleman et robin5wood. Le scenario se lance toutes les minutes... s'il est premier de la liste.
J'ai tout viré et placé en premier un scenario reveil (qui lance une phrase c'est l'heure sur le client) puis refait mon scenario allume tout. Et la plus de problème.
J'ai recommencé le test en placant en premier le scenario eteins tout, et la tout s'etiens toutes les minutes. Les autres scenarii placés après fonctionnent  normalement (allume tout par exemple).
J'ai donc l'impression que si le premier scenario n'est pas date heure, la cause prend en compte un date heure qui est toujours vrai sans tenir compte de la cause "phrase".

**Comment by ingfred** [comment]
Eh bien non. Ce n'est pas le premier scenar qui est en cause. Désolé pour la mauvaise description.
C'est un scenar de milieu de tableau que se lance !
![capture du 2016-02-07 15 10 39](https://cloud.githubusercontent.com/assets/8363638/12872799/0a90806e-cdad-11e5-84ea-c15bd7687c09.png)
il allume la lampe 3 , toutes les minutes !
a n'y rien comprendre.

**Comment by ingfred** [comment]
Et que celle ci !
![capture du 2016-02-07 15 13 29](https://cloud.githubusercontent.com/assets/8363638/12872814/6ab32424-cdad-11e5-83d1-ff0f074a6ca0.png)

**Comment by ldleman** [comment]
Vraiment louche en effet, je vais faire des tests de mon coté voir si j'arrive a reproduire le pb.

**Comment by ldleman** [comment]
Yop ! Peux tu mettre à jour yana puis lancer l'url :   
http://ton.url.yana**/action.php?action=crontab&mode=verbose**

et screenshoter le résultat ? :)

**Comment by ingfred** [comment]
Bonjour.
Ce soir.
Suis au boulot et ai débranché tout le bastringue.
C'est le premier scenario sans date qui prends a priori. c'est a dire 
que s'il y en a un avant avec cause date, c'est le second avec cause 
phrase qui déclenche tout de meme.
J'ai vu dans le code que tu avais commencé a regarder les capteurs pour 
cause dans scenario ... Quelle bonne idee.

De plus dans common.php, la ligne de debug avec tes ip n'etait pas 
commentée. Est ce normal ?

**Comment by ldleman** [comment]
Je pense avoir compris le soucis, le pb ne viens pas des scnéario de date mais du fait que je stocke la derniere phrase énoncée dans une variable et que je test dans les scénar de phrases si cette variable correspond a la phrase a enoncer pour lancer le scénario.

Sauf que jamais ne je vide cette variable, du coup si tu as prononcé la phrase une fois, elle vas s'executer a chaques fois.

Fois que je revois la conception.

Oui les capteurs c'est prévu et mêmes quelques autres features mais pour le moment j'essaye de stabiliser les fonctions de base ^^.

Pour les ip, oui c'est normal, ça me sert a faire du debug sans gener les utilisateurs.

**Comment by ldleman** [comment]
J'ai corrigé si tu peux reesayer (après update) quand t'a une minute...

**Comment by ingfred** [comment]
Je teste cela rapidement.
Faut commenter la ligne dans le common.php ?

**Comment by ingfred** [comment]
![capture du 2016-02-08 12 26 20](https://cloud.githubusercontent.com/assets/8363638/12884527/36f6b990-ce5f-11e5-81a3-ab350de36739.png)
Voila pour le screenshot

il m'a ajouté des \\ avant tous les / dans le lancement des commandes du scenar : 
sudo \\/var\\/www\\/yana-server\\/plugins\\/siplec\\/radioEmission 0 1414 1 off
normal ?
Je ne peux pas verifier d'ici si tout ok
on aura la réponse que cet AM.
Merci en tous cas.

**Comment by ingfred** [comment]
A noter screenshot apres mise à jour, d'ou derniere phrase enonce à "" sans doute.

**Comment by ingfred** [comment]
Bon apetit.

**Comment by ldleman** [comment]
Donc ça a l'air d'avoir résolu ton premier pb.
Pour common.php tu n'as rien besoin de commenter, ça active simplement un retour de debug quand c'est mon ip, pour les autres, c'est transparent.
les \/ ajoutés ça ne gene normalement pas l'execution ce sont des caracteres déchappement auto ajoutés pour eviter de sortir de la chaine

**Comment by ingfred** [comment]
Je restesterais en arrivant à la maison, mais selon mon correspondant local la bas cela ne fonctionne plus. Les caractères d'échapement se multiplient !
au lieu de sudo /var/.... je suis arrivé à sudo \\/var\\/www.... puis à sudo \\\\\\\\/var\\\\\\\\/www\\\\\\\/......
j'ai corrigé le scenar à la main. Il me remet les deux caractères d'échappement mais plus de multiplication autre pour l'instant;

**Comment by ingfred** [comment]
Tu as ajouté une fonction d'import ?
Super idée.
Par contre petit bug, le fichier json à l'export comprend les caractère d'échappement multipliés :+1:  {"story":{"id":"4","date":"1454943593","user":"","label":"allume tout","state":"1","log":"====== Execution 08\/02\/2016 16:07======\n3 effets \u00e0 executer\n> Execution de l\\'effet \"command\"\n\tcommande server lanc\u00e9e : sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 1 on\n> Execution de l\\'effet \"command\"\n\tcommande server lanc\u00e9e : sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 2 on\n> Execution de l\\'effet \"command\"\n\tcommande server lanc\u00e9e : sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 3 on\n"},"causes":[{"id":"15","story":"4","sort":"0","type":"listen","values":"{\"type\":\"listen\",\"operator\":\"=\",\"value\":\"allume tout\",\"union\":\"\"}","union":"","operator":"="}],"effects":[{"id":"25","story":"4","sort":"0","type":"command","union":"","values":"{\"type\":\"command\",\"target\":\"server\",\"value\":\"sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 1 on\",\"union\":\"\"}"},{"id":"26","story":"4","sort":"1","type":"command","union":"","values":"{\"type\":\"command\",\"target\":\"server\",\"value\":\"sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 2 on\",\"union\":\"ET\"}"},{"id":"27","story":"4","sort":"2","type":"command","union":"","values":"{\"type\":\"command\",\"target\":\"server\",\"value\":\"sudo\\\\\/var\\\\\/www\\\\\/yana-server\\\\\/plugins\\\\\/siplec\\\\\/radioEmission 0 1414 3 on\",\"union\":\"ET\"}"}]}

**Comment by ingfred** [comment]
Pour info php 5.6.17. Au cas ou cela aurait une influence

**Comment by ingfred** [comment]
Erreur database hier en lancant un scenar à la main.
tout crasché Yana.
je reinstalle

**Comment by juliendiotworldtour** [comment]
Bonjour @ldleman, comment vas tu?
de mon coté je ne peux pas créer de scénario. Une fenêtre pop up me dit erreur indéfinie, merci de contacter un administrateur.

Voici mon scénario douche:

Cause:
Phrase = lance la douche

Effet 
Phrase = la douche commence dans 5 seconde
GPIO 0 actif
Pause 125 secondes
GPIO 5 inactif
Pause 5 secondes
GPIO 5 actif
Pause 20 secondes
GPIO 5 inactif
Pause 40 secondes
GPIO 5 actif
Pause 60 secondes

dois-je écrire ce scénario différemment pour qu'il soit accepter?

Merci!
Julien

**Comment by ldleman** [comment]
@juliendiotworldtour es tu sût d'avoir ton plugin story a jour ? Ca ressemble beaucoup a d'anciens bugs réglés depuis un moment. J'ai fait le teste an local, l'ordre est bien conservé et les temps ont l'air respectés : 
![01](https://cloud.githubusercontent.com/assets/2620979/13106200/52bad79c-d567-11e5-8bcc-614a91564679.PNG)

![02](https://cloud.githubusercontent.com/assets/2620979/13106209/5645cf52-d567-11e5-8abd-57077810a08f.PNG)


@ingfred je vais regarder pour les caractères d'échappement.

**Comment by juliendiotworldtour** [comment]
Bonsoir @Idleman, j'essaye de nouveau ce soir, quitte à refaire une maj, et je te dis cela !  Est ce que tu as des tuyaux à me donner pour mieux réussir mon scénario ou est il bon tel que rédigé dans mon précédent commentaire ?  Merci beaucoup !

**Comment by juliendiotworldtour** [comment]
Rebonsoir @ldleman , voici mon retour:
J'ai bien vérifié, YANA est à jour. Toutefois mes relais s'allume toujours l'un après l'autre et non ensemble. 
Pour l'instant j'ai d'abord mon cycle du GPIO 0 qui commence (125 secondes), et seulement une fois que ce cycle est fini le GPIO 6 débutent ses différents cycles.
Dans l'idéal, j'aimerai que le GPIO 0 ait un cycle actif de 125 secondes **au cours duquel** le GPIO 6 est OFF 5 secondes, ON 20 secondes, 0FF 40 secondes et ON 60 secondes (le cumul donne 125 secondes). Les 2 s'arrêtent donc en même temps.

Penses tu que je puisse écrire 2 scénarios avec la même commande vocale? ceci permettrai d'avoir 1 scénario par relai et par conséquent je pourrais résoudre mon problème

**Comment by juliendiotworldtour** [comment]
C'est bon @ldleman , j'ai ENFIN réussi!!! voici le scénario à taper:

Cause: Phrase YANA lance la douche
Effet:
GPIO 0 Inactif
Pause 5 secondes
GPIO 6 inactif
Pause 20 secondes
GPIO 6 actif
Pause 40 secondes
GPIO 6 inactif
Pause 60 secondes
GPIO 6 actif
GPIO 0 actif

TU NE PEUX PAS SAVOIR A QUEL POINT JE SUIS HEUREUUUUUUUUX!!!!!

Un très grand merci à toi :+1:

**Comment by ingfred** [comment]
Bonjour.
Après réinstall, tout ok. Ajout tout de même de caractères d'échappement.
Je n'ai pas encore testé les sauvegardes.

**Comment by ldleman** [comment]
@juliendiotworldtour content que ça fonctionne (oui je sais réponse tardive ^^)
@ingfred oki doki, je clos pour faire un peu de ménage, n'hésite pas a rouvrir un post si le problème persiste
