### ISSUE TITLE
Plugin door

### ISSUE THREAD

**Issue by theos10** [ldleman/yana-server#186]
Bonjour,

J'utilise yana depuis peu,je suis un ex de sarah.
J'utilise un banana pi et yana se comporte tres bien.
j'ai donc commencer a créé un mapping des gpio pour le banana pi.
j'utilise wirerelais pour gérer la porte de mon garage, mais je souhaitai afficher l’état de la porte sur le dash. j'ai donc installé le plugin door pour récupérer l’état de la porte sur un gpio via un contact sec.
mais je me suis aperçu que le plugin door n'a pas de widget.
Je me suis mis au travail.
j'ai ajouté un widget au plugins ( en calquant sur celui de wirerelais).
le widget fonctionne, mais il ne me retour pas l’état de la porte. Dommage, c'est l'idée à la base.
J'ai aussi modifier la page de configuration du plugin.
Je ne suis pas developpeur, mais je me soigne, et j'ai donc des petits soucis.
Lorsque j'enregistre une nouvelle porte il ajoute les champs dans la base de donnée, plus une ligne avec les champs vide. J'utilise onclick="plugin_door_save(this)"
Ensuite je souhaite modifier une porte, et il ne remonte pas les valeurs contenus dans la BD.
et bloque au niveau des icones. (Je precise aussi que j'ai ajouter le choix le l'icone de la porte).

Merci de votre aide.

Comment faire pour partager mon travail ? 

Ghislain.

**Comment by theos10** [comment]
J'ai résolu mes problèmes.
La mise a jour du plugin Door est finalisé, et je souhaiterai en faire profiter a la communauté.
Je n'arrive pas a valider mon inscription au yana market.

**Comment by valentin8709** [comment]
Super idée! J'espère que tu auras un peu de temps pour balancer ça sur le market car je pense que je ne serai pas le seul intéressé! Et bravo en tout cas!

**Comment by theos10** [comment]
Bonjour, sur le mark et tu trouveras le plugin Door v2.
N hésite pas à suggèrer des améliorations. Ou me signaler d éventuelle bug.

**Comment by moebius911** [comment]
Bonjour
Je suis très intéresser par ton plugin par contre lors du téléchargement sur le market j’ai une erreur 

Téléchargement du plugin...
Plugin téléchargé OK
Extraction du plugin...
Plugin extrait OK
Plugin invalide, fichier principal manquant Erreur

Y a-t-il une procédure particulière pour le récupérer ?
Merci d’avance

PS : je précise que je n’ai aucun problème pour télécharger d’autre plugin

**Comment by moebius911** [comment]
Problème résolu :
1 -J’ai supprimé le dossier « door » existant.
2- Je télécharge le plugin door V2 sur le market 
3 -le plugin s’extrait dans un dossier portant un nom avec un code hexa. J’ai donc copié le contenu de ce dossier dans le dossier plugin.

Si ça peut aider quelqu’un.

Bonne journée

**Comment by theos10** [comment]
Bonjour,

C’est ce que j'allais te proposer comme solution provisoire.
Je ne vois pas trop le problème, il ne manque pas de fichier.
Peut-être que Idleman a une idée ?
J'ai déjà essayé d'autre plug in avec le même souci.	

J’ai déjà fait quelques corrections depuis la publication, donc si tu remarques des choses qui ne fonctionne pas, fait le moi savoir.

Ghislain.

**Comment by ldleman** [comment]
@theos10 Ce problème arrive quand le fichier plugin.php n'est pas a la racine du zip.
Ton arborescence doit etre du type :
`FichierZIP/nomdossierplugin/monplugin.plugin.php`
Alors qu'elle devrait être
`FichierZIP/monplugin.plugin.php`

Tiens moi au jus si ça ne fonctionne toujours pas après ça mais il y a de grandes chances que le pb vienne de là

**Comment by ldleman** [comment]
@theos10 
Je clos , n’hésitez pas a rouvrir si le pb persiste après remaniage du zip
