### ISSUE TITLE
Problème de commandes vocales

### ISSUE THREAD

**Issue by poopeye** [ldleman/yana-server#189]
Salut,
Je débute sur Yana et je rencontre quelques problèmes. Après chaque commande vocale, la commande "Yana énaerve toi" passe alors que je n'ai rien dit de tel. Heureusement, cette commande n'a aucun effet, (comme d'autre d'ailleurs) puisque le log affiche url à lancer: sans rien du tout. (Idem pour la commande "yana présente toi" qui est reconnue, mais le log affiche également url à lancer sans rien après.
Avez vous rencontré ces problèmes?
Petite précison, je suis actuellement en test avec un micro casque. Est ce que ça peut venir de ça? D'autre part, j'ai une pièce assez grande, quelle est la distance max pour le micro d'une kinect? (avant de passer à la caisse?)

**Comment by poopeye** [comment]
Autre bizarrerie, quand je tape l'adresse de locale de mon pi dans le navigateur, j'arrive sur Yana server.
Si je tappe, comme c'est préconisé, adresse.de.mon.pi/yana-server, j'ai un 404 Not Found...
J'ai du faire une boulette durant l'installation?

**Comment by ldleman** [comment]
Tu as du installer yana direct a la racine de ton serveur web d'ou le fait que tu y accede sans taper le nom du dossier, ce n'est pas grave a partir du moment ou tu ne compte pas instalelr d'autres applications web sur ce même serveur.

Quand tu lance en mode verbose ça donne quoi?

**Comment by poopeye** [comment]
Salut, et merci pour l'intérêt que tu portes à nos soucis!

Comme tu l'as vu sur l'autre post # 177, j'ai changé le port (de 9999 à
9998) et les 3 applis sont connectées. Les commandes vocales sont reconnues
mais aucune action résultante, ni de réponse de Yana...
Voici en PJ les logs. En mode verbose pour MOUTH, rien de plus!
Je ne suis pas expert, voire même novice (motivé mais novice), mais les
commandes semblent reconnues parfaitement sans que le lien ne se fasse avec
le serveur...
D'autre part, comme tu l'as dit dans le ticket 189, j'ai du installer Yana
direct à la racine de mon seveur web. Tu me dit que "ce n'est pas grave à
partir où je ne compte pas installer d'autres applications web sur le même
serveur". Je précise que j'ai installé Domoticz sur la même raspberry et
que tout fonctionne bien de ce coté. Mais peut être que mon souci avec Yana
(MOUTH) a un lien?
Bref, merci d'avance pour ton aide!
@+
Poopeye

**Comment by poopeye** [comment]
En mode verbose, rien de plus pour le MOTH.EXE. Pour le EAR.EXE, je vois bien tout ce qui se passe (comparaison avec toutes les commandes etc.)

Voici ce qui s'affiche sur ma connexion avec ma rasperry lors de la commande vocale: "Yana, quelle heure est il?"

[07/03/2016 17:55:37] Try to parse received data : {"action":"CATCH_COMMAND","command":"YANA quelle heure est il","confidence":"0,9774981","text":"YANA quelle heure est il le"}
[07/03/2016 17:55:37] Parsed action : CATCH_COMMAND
[07/03/2016 17:55:37] Call listen hook (v2.0 plugins) with params YANA quelle heure est il > YANA quelle heure est il le > 0,9774981

diction de la commande : YANA quelle heure est il
Test de comparaison avec 32 commandes
Commande ancien format trouvée, execution de l'url http://127.0.0.1:80/yana-server/action.php?action=vocalinfo_hour&token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaPHP Warning:  file_get_contents(http://127.0.0.1:80/yana-server/action.php?action=vocalinfo_hour&token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 in /var/www/yana-server/common.php on line 140

Warning: file_get_contents(http://127.0.0.1:80/yana-server/action.php?action=vocalinfo_hour&token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 in /var/www/yana-server/common.php on line 140

**Comment by zb2oby** [comment]
Hello

Une idee en passant. As tu routé ton port 9998 ? J'avais eu un soucis au départ avec le client android car je n'avais pas créer de regle nat sur le
 port 9999 au niveau de ma box.


Autre truc pour le client yana windows, dans les config modifie l'URL en supprimant le /yana-server . Tu met juste http://ipdurpi/action.php
J'ai aussi eu ce problème car mon yana je ne sait pour quelle raison est installé à la racine.

En espérant avoir aidé. 

François

**Comment by poopeye** [comment]
Salut et merci pour ton aide.
Mais en ouvrant les ports 9999 et 9998 sur la box, pas mieux... De plus mon
Yana-server est installé dans /var/www
Tout à l'air bien connecté sur Yana Face mais pas de réponse orale avec le
client Yana4all. Je précise qu'avec le client Windows tout fonctionne!
Est ce que ca peut venir du fait que les plugins actuels ne fonctionnent
pas avec yana4all?

**Comment by ldleman** [comment]
salut @poopeye , peux tu refaire une syntèse de ce qui fonctionne et ce qui ne fonctionne pas car en lisant tous els posts ci dessus je suis un peu perdu ^^.

Ton erreur 
`Warning: file_get_contents(http://127.0.0.1:80/yana-server/action.php?action=vocalinfo_hour&token=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found`

Est normale, il ne trouve pas la page d'action du plugin vocalinfo car il vas la chercher dans http://127.0.0.1:80/yana-server/ alors que ton instance de yana est installé à la racine soit sur http://127.0.0.1:80 il est donc nécessaire de modifier cette url pour qu'il retrouve ses petits

**Comment by ldleman** [comment]
Sans réponse de ta part, je clos le sujet, n'hésite pas a rouvrir un post a jour si besoin :)
