### ISSUE TITLE
yana à la racine du server

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#193]
J'ai lu dans les issues que certain s'inquiétaient du fait que l'on accède à yana en tapant simplement l'adresse du raspberry et non adresse/yana-server. C'est le cas si on installe yana via "curl -L yana.madnerd.org|sudo bash". A mon avis pas plus mal en fait si le raspi est dédié à cela.

**Comment by ldleman** [comment]
oui, maditnerd a conçu l'install dans cet optique de rpi dédié, étant donné la taille grandissante de yana ça peux se tenir mais personnellement j'aime bien garder la possibilité du multi app sur mon apache.
Le plus casse couille dans l'histoir étant que les tutos/aides/docs utilisent le chemin initial /yana-server du coup pas mal d'utilisateurs sont perdus dans les commandes.

@maditnerd ton avis sur le sujet ?

**Comment by darkpisto** [comment]
Perso je voyais plutôt ça comme @ldleman  avec le "/yana-server" pour que le RPI puisse servir à d'autres choses.

Mais l'argument d'une installation "rpi dédié" pensée pour les noobs est compréhensible.
Dans ce cas faudrait mettre à jour la doc pour virer les "/yana-server", et peut être ajouter quelque part un petit tuto pour expliquer comment modifier le vhost pour ceux qui veulent faire cohabiter plusieurs services sur le rpi (j'ai l'impression que pas mal fusionnent le projet avec Domoticz par exemple ^^).

A voir en demandant l'avis de la communauté ? :)

**Comment by ingfred** [comment]
A mon avis le mieux est effectivement de demander à maditnerd de revoir le script pour installer yana dans /yana-server. Quitte a faire un tuto pour que si l'on attaque adresse sans yana cela pointe vers adresse/yana-server. Comme cela tout le monde (sauf maditnerd) est content et pas de tutos à revoir.
Cela n'engage que moi, je ne fait que causer sans être capable de bricoler un bout de script.

**Comment by maditnerd** [comment]
Ok pas de soucis, je modifie ça. :+1: 

Pour info pour modifier le dossier racine de lighttpd,
il suffit de modifier dans **/etc/lighttpd/lighttpd.conf**
La ligne : `server.document-root        = "/var/www/"`

Par exemple pour avoir yana directement en tapant _addresse/_
`server.document-root        = "/var/www/yana-server"`

Lors de l'installation ce fichier est d'ailleurs réécrit afin d'être sûr que la configuration soit correcte, il suffit de modifier entre la [ligne 557](https://github.com/ldleman/yana-server/blob/master/install.sh#L557) à la ligne 587.

**Comment by darkpisto** [comment]
@maditnerd  : merci :)

**Comment by ingfred** [comment]
Quel SAP ! (Service Après Partage). Tu as bien fait de racheter ORANGE et Free. J'attends les premiers résultats avec impatience.

**Comment by zb2oby** [comment]
Hello
Un tout petit detail. Lors de la finalisation de l'install il est demandé dans le terminal de se rendre sur http://ipdurpi 
Depuis la modif cette adressage ne fonctionne plus il faudrais juste modifier cette info en http://ipdurpi/yana-server/  pour les noob afin de pouvoir acceder a l'interface de finalisation. Ca evitera les tickets inutiles ;-)

**Comment by maditnerd** [comment]
Effectivement j'avais oublié! c'est fait.

**Comment by ldleman** [comment]
Ké balèze ce madit ! :D On peux clore ?
