### ISSUE TITLE
Plantage yana windows apres historique

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#194]
Bonjour 
J'ai remarqué que yana Windows plante à chaques fois que je vais voir dans l'historique des commandes. J'y accede sans problème mais lorsque je ferme l'historique le client cesse de fonctionner. Et ce quelque soit la machine sur lequel il est installé.

**Comment by ldleman** [comment]
Ca ressemble beaucoup a un bug de la v1.0, as tu essayé le client v2 yana4all?

**Comment by zb2oby** [comment]
Ah ba ca va vachement mieux marcher comme ca...sorry j'ai mis un peu de temps a me rendre compte que j'étais obsolète.. Tu vas trop vite pour moi ;-).  Je passe a la V2 immédiatement ;-)

**Comment by ldleman** [comment]
Pas de soucis je ne communique pas assez sur ce sujet :) bonne continuation sur la v2.0
