### ISSUE TITLE
Rabperry PI 3 et plugin dash_monitoring

### ISSUE THREAD

**Issue by psylo24** [ldleman/yana-server#195]
Bonjour,

Suite à l'achat du RPI 3, le plugin dash_monitoring dans Yana ne reconnait pas le RPI 3 : voici le message que j'ai sur la page d'accueil : 
`Votre RPI dispose d'une révision (a02082) inconnue de yana, il n'est pas possible d'afficher ses pins.
Pour ajouter cette révision, merci de faire une demande sur github en précisant la révision, le nombre de pins, le modèle et la vesion de votre rpi.`

Ce n'est pas grand chose mais c'est juste un petit détail :)

Cordialement.

**Comment by ldleman** [comment]
Salut psylo :), peux tu me donner le  nombre de pins , le modèle et la version de ton rpi que je l'ajoute à la pinmap?

**Comment by psylo24** [comment]
Bonjour,

C'est le aspberry Pi 3 (le dernier du coup) il a exactement le même nombre de pins et fonctionalités que le Raspberry Pi 2 Model B il a juste le wifi et le bluetooth d'intégré en plus du pi 2 B.

N'hésite pas à revenir vers moi en cas de question.

**Comment by theos10** [comment]
Salut, dans le fichier System.class.php, tu ajout la ligne suivante :+1:
 `'a02082' => array('ram'=>'1024','version'=>'2.0','type'=>'b','revision'=>'a02082'),`
après la ligne : 
`'a01041' => array('ram'=>'1024','version'=>'1.0','type'=>'b2','revision'=>'a01041'),`
normalement ca devrait fonctionner.
Théos.

**Comment by ldleman** [comment]
Normalement c'est ajouté,n n'hésite pas a réouvrir si le problème persiste
