### ISSUE TITLE
Yana avec RPI en Wifi ne fonctionne pas.

### ISSUE THREAD

**Issue by psylo24** [ldleman/yana-server#196]
Bonjour,

Ayant acheté un RPI3 depuis quelques jours, j'ai installé yana sur celui ci mais quand je connecte mon RPI en Wifi, impossible de me connecter à Yana-sever ( j'ai bien lancé le socket.php) depuis l'appli Android.

Je ne vois aucune info php arrivée dans mon terminal alors que si je branche le RPI en filaire tout fonctionne parfaitement, je ne comprend pas pourquoi ca ne fonctionne pas étant donné que le wifi ou le filaire est juste un 'tuyau' différent.

Où puis-je consulter les logs afin de voir ce qu'il se passe ?

Je vais essayer de faire un tcp-dump pour voir si les trames arrivent bien sur le RPI...

Cordialement.

**Comment by ruf147** [comment]
Bonjour @psylo24, juste pour savoir, est tu en IP statique?

**Comment by psylo24** [comment]
Bonjour,

Oui j'ai mis une IP staique. Ca ne devrait pas poser de probléme particulier.
Il est vrai que en calbé je suis en DHCP avec une réservation d'IP sur mon routeur.

**Comment by ruf147** [comment]
Un petit ifconfig en filaire et en wifi ? Histoire de voire si les IP's sont les mêmes.

**Comment by psylo24** [comment]
Bonjour, non les IPs ne sont pas les mêmes.
En ethernet c'est le DHCP qui addresse mon RPI
En Wifi c'est une IP statique (dans le meme subnet 192.168.1.xxx)

J'ai même changé d'IP en cabé (changement de réservation d'IP dans le routeur) et ca fonctionne dans tous les cas.
Ce n'est pas un probléme d'adressage ca c'est sur étant donné que je prend bien la main en SSH sur mon RPI.
