### ISSUE TITLE
Accéder à la base SQLite3

### ISSUE THREAD

**Issue by AidepcXyz** [ldleman/yana-server#198]
Bonjour, comment accéder directement à la base de données SQLite3 utilisée par Yana-server ? j'ai pu accéder au serveur SQLite3 mais je n'y vois pas de database ? Merci !

**Comment by ingfred** [comment]
dans yana-server/db il y a le fichier .database (caché)

**Comment by ldleman** [comment]
Sqlite3 ne comporte pas de serveur, c'est un système de base de donnée monofichier, chez yana il est effectivement dans le dossier /db
