### ISSUE TITLE
Mise à jour de Yan server

### ISSUE THREAD

**Issue by poopeye** [ldleman/yana-server#200]
Salut, suite à mes différents soucis, j'ai tout ré installé. Je tente maintenant d'installer yana4all. Lors de la mise à jour avec un git pull dans le dossier /var/www/yana-server, la rasperry me dit :"already to update". Pourtant, le fichier socket.php n'existe pas dans le dossier yana server... Je ne peux donc pas le lancer (et accessoirement voir si ça passe enfin avec le port 9999!) Bref je bloque. Faut-il que je l'ajoute manuellement avec WinSCP dans le dossier Yana server de la raspberry? Quelque a t il déjà été cofronté à ce problème? Je précise que la première version de Yana Windows marche parfaitement.. Merci d'avance pour votre aide!

**Comment by maditnerd** [comment]
Teste cette commande, cela devrait forcer la mise à jour:
```
git fetch --all
git reset --hard origin/master
git pull
```
Normalement ça ne devrait pas affecter les plugins ajoutés à yana et la base de données (mais je ne garantie rien)

Source : http://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head

**Comment by poopeye** [comment]
la commande "git reset --hard origin/master" me retourne:
"HEAD is now at d2d02d0 Correction https://github.com/ldleman/yana-server/issues/78"
Et toujours pas de fichier socket.php dans yana-server...

**Comment by poopeye** [comment]
HEAD is now at d2d02d0 Correction https://github.com/ldleman/yana-server/issues/78

**Comment by poopeye** [comment]
HEAD is now at d2d02d0 Correction https ://github.com/ldleman/yana-server/issues/78

**Comment by maditnerd** [comment]
Je vois le problème ! Dans le tuto sur framboise 3.14 l'auteur n'arrivait pas à cloner yana alors il a forké le projet sur son compte github.

Résultat au lieu de récupérer yana-server sur le github d'idleman , tu es sur la version de celui-ci qui n'est plus à jour.

Tape:
````
git remote set-url origin https://github.com/ldleman/yana-server
git pull
````
Et ça devrait marcher, mais je te conseille de lancer le script install.sh 
````
/var/www/yana-server/install.sh
````
et dans le menu
````
Configurer -> Vérifier Yana
````
Cela fera du socket un service et vérifiera les permissions (et aussi fera un petit apt-get update & upgrade)

@ldleman , ça serait peut être bien d'en parler à François histoire qu'il change la ligne ou ça git clone, voir si ça vous dit, vu que l'auteur n'a pas eu le temps de faire la suite, je peux refaire cette partie et faire les suivantes (ça titile mon coté obessionnel les tutos pas fini , bien que j'en est aussi un paquet en préparation de mon coté)

**Comment by poopeye** [comment]
Salut, et merci!

Les commandes  "git remote set-url origin
https://github.com/ldleman/yana-server"
<https://github.com/ldleman/yana-server>
puis "git pull" fonctionnent!!

En revanche, je n'arrive pas à lancer le script install.sh...

Un "sudo bash install.sh" me retourne "     :    " ... A la prochaine!"

**Comment by ldleman** [comment]
@maditnerd faut que je contact framboise merci pour l'info, a voir si il accepte que tu complete son tuto, sinon au pire si tu veux en faire un officiel bien propre pour le wiki ou pour la page officielle (http://idleman.fr/yana) n'hésite pas a me le transferer

**Comment by ldleman** [comment]
@poopeye tu peux diminuer la tolerance sur la commande enerve toi dans les config de yana server (mais un meilleur micro c'est toujours un plus ^^)

**Comment by poopeye** [comment]
Merci pour ton aide. Concrètement, pour diminuer la tolérance, il faut
modifier quel fichier? J'imagine qu'il faut augmenter augmenter le seuil
(de 0.8 à 1) pour que la commande ne passe plus, ou seulement quand elle
est parfaitement prononcée?

**Comment by ldleman** [comment]
Normalement tu as juste a aller dans les config -> préférences -> informations vocales et tu modifie le chiffre a droite de la commande puis tu clic sur enregsitrer, plus la valeur est haute et plus tu devras être précis pour que yana la reconnaisse, si tu veux la désactiver complétement tu peux aussi décocher la case à gauche de chaques commande.
