### ISSUE TITLE
Problème Door V2

### ISSUE THREAD

**Issue by SkyRuNNer26** [ldleman/yana-server#203]
Bonjour,
Je viens de recevoir aimant et capteur à effet de Hall et de ce fait j'ai installer Door V2. Seul souci lorsque je crée ma porte il me demande obligatoirement un pin pour la gâche électrique or je n'en possède pas. J'ai donc mis un pin non utilisé au hasard et indiqué le pin de mon capteur a effet de Hall. Le problème est là : sur le widget du dashboard, l'état reste "inactive" qu'il y est un aimant ou pas.
Si vous avez une solution je suis preneur.

Merci en tout cas pour tout votre boulot c'est formidable.
SkyRuNNer

**Comment by ldleman** [comment]
quand tu lis ton pin en ligne de commande via 
`gpio read n°pin`
il change bien d'état en fonction de l'aimant ?

**Comment by SkyRuNNer26** [comment]
Ah oui en fait c'est juste que mon aimant est pas très puissant donc le capteur ne le reconnait pas bien ^^ je vais racheter un aimant plus puissant :)
Problème résolu merci encore
