### ISSUE TITLE
probleme installation socket

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#205]
bonjour,

suite à un bug de source inconnue (plus d'action ou reponse de yana) j'ai fait une vérification de yana via le petit module d'installation et voici  l'erreur obtenue au moment de l'installation du socket

" Erreur dans /etc/supervisor/conf.d/yana.conf - error: < class 'socket.error' >, [Errno 2] No such files or directory: file: /usr/lib/pyton2.7/socket.py line: 224"

quelqu'un à t'il une idée ?

merci

**Comment by maditnerd** [comment]
supervisord est un programme pour transformer un programme (ici socket.php) en service , à priori quelquechose n'a pas bien marché lorsqu'il a recrée la configuration.

Essaye de faire ceci pour le redémarrer
````sudo service supervisor restart````

Si ça ne marche pas peut être que le réinstaller résoudras le problème
````sudo apt-get install supervisor --reinstall````

On peut aussi vérifier si le socket fonctionne bien en tapant
````sudo supervisorctl status yana````

Et lire les logs du socket en tapant
````sudo supervisorctl tail yana````

Il se peut aussi qu'il est un problème avec /var/run/supervisor.sock , le plus simple reste alors de rédemarrer le Raspberry Pi afin qu'il recrée celui-ci
En espérant que ça puisse t'aider.

**Comment by zb2oby** [comment]
Merci a toi pour ta réactivité. 
J'ai du réinstallé le supervisor. A priori le socket se lance mais voici les log :

Failed to open stream connection refused in var/www/yana-server/common.php line 140

WTF ?

**Comment by ldleman** [comment]
En partant du principe que tu dispose d ela dernière version ton bug semble du [à cette ligne](https://github.com/ldleman/yana-server/blob/master/common.php#L140) ce qui implique que tu execute une commande vocal a l'ancien format plugin et que visiblement l'url fournie par le plugin est inaccessible, soit parce que ton rpi n'a pas le net, soit parce que l'url du serveur n'est plus active.

**Comment by zb2oby** [comment]
Oui l'URL du serveur n'est plus joignable. Pour quelle raison je ne sait pas. Tout marchais bien et du jour au lendemain plus rien. Effectivement je n'ai plus du tout acces au dashboard...je ne vois pas du tout pourquoi car mes ip n'ont pas changé.

**Comment by ldleman** [comment]
Il ne s'gait pas forcement de l'url du serveur, c'est le plugin qui choisis
Essaye de faire un 

`var_dump($cmd['url'].'&token='.$user->getToken());`

Avant la ligne que j'ai spécifié voir quelle url il essaye d'attaquer.

**Comment by zb2oby** [comment]
ok. voici les nouveaux log

diction de la commande : YANA, Allume la cuisine
Test de comparaison avec 6 commandes
Commande ancien format trouvée, execution de l'url http://192.168.1.12:80/yana-server/action.php?action=ComboRelay_change_state&engine=1&state=1&webservice=true&token=a827c177051b1f427080e4a1dcf5e46acf3c2df7PHP Warning:  file_get_contents(http://192.168.1.12:80/yana-server/action.php?action=ComboRelay_change_state&engine=1&state=1&webservice=true&token=a827c177051b1f427080e4a1dcf5e46acf3c2df7): failed to open stream: Connection refused in /var/www/yana-server/common.php on line 140

Warning: file_get_contents(http://192.168.1.12:80/yana-server/action.php?action=ComboRelay_change_state&engine=1&state=1&webservice=true&token=a827c177051b1f427080e4a1dcf5e46acf3c2df7): failed to open stream: Connection refused in /var/www/yana-server/common.php on line 140

pour info j'utilise l'ancienne version car la nouvelle plante sans arrêt et cree enormement de faux positif chez moi donc j'apprend a connaitre la v1 et je verrais pour la v2 un peu plus tard ;-)

en tout cas merci pour vos aides

**Comment by zb2oby** [comment]
J'ai trouvé ! 
en fait mon serveur etait desinstallé..yana n'etais pas en cause...A savoir pourquoi,le mystere reste entier car sans avoir touché au raspi ni avoir utilisé yana, du jour au lendemain cela ne fonctionnais plus donc au final un petit "sudo apt-get install apache2 php5 mysql-server libapache2-mod-php5 php5-mysql" a resolu mon probleme....
Par contre, si quelqu'un à une idée de comment un serveur apache peut se désinstaller tout seul je suis preneur....

**Comment by ldleman** [comment]
Là à part une erreur ICC je ne vois pas ^^

**Comment by ldleman** [comment]
Je clos, n'éhsite pas a réouvrir si tu re constate le pb

**Comment by AF340** [comment]
Même problème survenu hier, serveur plus joignable et même symptôme, mais installer apache et mysql semble etre un contournement, puisque yana n'a pas besoin d'une config si lourde...

**Comment by AF340** [comment]
Pour info, j'ai du désinstaller php / lighttpd et réinstaller yana avec la config auto qui ré les installe/ 
> fonctionne à nouveau/
