### ISSUE TITLE
revision rpi inconnu 

### ISSUE THREAD

**Issue by lotimerr** [ldleman/yana-server#211]
Votre RPI dispose d'une révision (a02082) inconnue de yana, il n'est pas possible d'afficher ses pins.
Pour ajouter cette révision, merci de faire une demande sur github en précisant la révision, le nombre de pins, le modèle et la vesion de votre rpi:

j ai un rpi 3   aucun pin est affiché

**Comment by ldleman** [comment]
Coucou, normalement c'est bon si tu peux faire un update et reverifier :)

**Comment by lotimerr** [comment]
j ai fais un update et sa na marche toujours pas je pense que je vais refaire l installe et je te ferai part du retour

**Comment by lotimerr** [comment]
c bon merci idleman avec un update sa marcher pas mais avec une reinstalle complete sa a marcher merci

**Comment by ldleman** [comment]
Etrange, l'update aurait pourtant du mettre à jour, la révision étant en dur dans système.class.php l'installation n'y change normalement rien :).
