### ISSUE TITLE
[Suggestion] Plugin IPCAM 

### ISSUE THREAD

**Issue by theos10** [ldleman/yana-server#212]
Bonjour,
Comme beaucoup d'entre vous, je possède une camera IP
Malheureusement le plugin ne gère pas tous les modèles de camera IP.
Serait il possible de décrire différent modèle de camera dans la classe du plugin, du même type que les gpio dans la class system, avec un Array.
Ensuite dans l'interface de configuration on sélectionnerai sont modèle.
dans la description il y aurait le model, et le liens de streaming.
Je possède une foscam fi8908 et le lien de streaming est le suivant : 
http://'.$camera->ip.'/videostream.cgi?user='.$camera->login.'&pwd='.$camera->password.'&resolution=32&rate=0
Comme cela chacun pourrai partager sa config et alimenter ainsi yana.

**Comment by ldleman** [comment]
J'ai ajouté un système identique dans Camera.class.php, j'y ai également ajouté ton modèle, merci pour la suggestion. :)

**Comment by theos10** [comment]
Ca marche nickel, je clos
