### ISSUE TITLE
Installation impossible de Yana

### ISSUE THREAD

**Issue by Lrtcfr** [ldleman/yana-server#214]
Bonjour, 
Quand j'essaye d'installer Yana, j'arrive à l'étape ou je doit aller sur la page web pour terminer l'installation. Le problème, c'est que la page met "404- Not Found". Que puis-je faire ?

**Comment by Srogath** [comment]
Bonjour, 

je rencontre également cette erreur, je précise que je suis sous Apache2..

Il est possible d'accéder à la page d’accueil de l'apache à savoir: http:\\maison.local\
Mais impossible d'accéder à http:\\maison.local\yana-server\ (404-NOT FOUND)
Je pense qu'un fichier doit manquer mais malheureusement je débute complètement.

Merci à tous.

**Comment by theos10** [comment]
Bonjour,

Si tu accède a http://maison.local/ , ton URL pour YANA doit être http://maison.local/yana-server/
après si tu souhaite accéder a yana via l'adresse http://yana.local/ tu doit décrire un virtualhost sur ton serveur apache.
pour commencer et vérifier que yana est bien installé, test avec l'adresse IP.

Ghislain.

**Comment by Srogath** [comment]
Bonjour,

tout d'abord merci pour cette réponse.

Lors du paramétrage de YANA à partir de l'installeur j'ai rentré le nom yana.local.

D'ailleurs lors de ma connexion sur http://yana.local/ je tombe bien sur la page d’accueil de mon apache en fonctionnement. Mais lorsque je souhaite accéder à http://yana.local/yana-server je retrouve le message indiqué plus haut.

J'ai tenté de mettre à jour et de réparer YANA mais rien n'y fait.

**Comment by zb2oby** [comment]
Hello

Plusieurs piste

Essaye directement avec ton ip locale
Ton ip locale est elle fixe ?
As tu routé le port 80 ?

**Comment by ingfred** [comment]
Bonjour. Il y a quoi dans le dossier yana-server ?
Pour l'install, tu as installé apache puis copié le dossier directement dans yana-server ou tu as utilisé une autre méthode ?
A moins que tu n'ai besoin d'apache, l'install automatique de matinerd fonctionne vraiment bien.
As tu essayé comme le dit zb2obi l'adresse 127.0.0.1/yana-server ?

**Comment by Raph94** [comment]
Bonjour.

J'ai un souci similaire après avoir installé avec le script de matinerd.

**Comment by Raph94** [comment]
Voici les logs lighttpd pour aider :
2016-04-26 17:50:21: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning: SQLite3::query(): Unable to prepare statement: 1, no such table: yana_configuration in /var/www/yana-server/classes/SQLiteEntity.class.php on line 295
2016-04-26 17:50:21: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error: Call to a member function fetchArray() on boolean in /var/www/yana-server/classes/SQLiteEntity.class.php on line 299

**Comment by Raph94** [comment]
Pour tenter d'avancer, j'ai fait quelques tests :
- mise en place d'un index.php d'info dans var/www pour vérifier si lighttpd est ok ce qui est le cas.
- mise en place d'un script php de création de base de donnée avec quelques tables dans un dossier spécifique pour vérifier que sqlite est ok ce qui est le cas.
- suppression de la base de donnée yana et retour sur la page http://ip-de-mon-rpi/yana-server. Toujours l'erreur 404 mais le fichier .db se crée (mais toujours à 0k).

Je ne suis pas un pro mais j'ai tenté de regarder un peu le code pour comprendre comment se créait le base et voir ce qui pourrait dans ma config ne pas fonctionner car je ne remets pas en cause le code puisque ça fonctionne chez d'autre.
Je vois bien les créations de tables dont la table configuration mais je ne trouve pas le moment où le fichier .db est créé. Peut être dans constant.php ?
Je n'arrive pas non plus à faire le lien avec le fichier SQLiteEntity.class.php indiqué dans l'erreur lighttpd.

Je continue à regarder ;)

**Comment by rasmila** [comment]
bonjour j'ai exactement le meme soucie. j'ai installée yana server avc la commande d'installation automatique, mais je bloque quand je veux accéder a la page yana server. je ne vois vraiment pas ou est le problème dans se que je fais

**Comment by Fabwiss** [comment]
Bonjour,
Même problème que les camarades avec le message 404 - Not Found lorsque je pointe vers http://maison.local/var/www/yana-server/install.php
Une idée.

Fabrice.

**Comment by darkouz** [comment]
Bonjour, 

Je viens de tester l'installation aujourd'hui et j'ai également le même problème. Page 404 quand j'essaie d'accéder à http://maison.local/yana-server

**Comment by ingfred** [comment]
Tu as essayer avec http://ton_adresse_ip_raspberry/yana-server ou http://ton_adresse_ip_raspberry

**Comment by ingfred** [comment]
essayé pas essayer.

**Comment by darkouz** [comment]
De mon côté, j'ai testé les deux, rien n'y fait

**Comment by ingfred** [comment]
tu as tout de meme bien les fichiers yana dans /var/www/yana-server ?

**Comment by darkouz** [comment]
Je sais pas, quand j'essaie d'accéder au dossier en scp, il me dit que je n'ai pas les droits

**Comment by ruf147** [comment]
Regarde en ligne de commande alors... 
- ls /var/www/ && ls /var/www/yana-server

**Comment by darkouz** [comment]
> yana-server
ls: cannot open directory /var/www/yana-server: Permission denied

>

**Comment by ruf147** [comment]
Bien relire le post de @theos10. Je crois qu effectivement, avec apache il faut cree un virtual host ou un lien symbolique. A savoir que l installation simplifié de yana tourne sous lighttpd, configuration  différented apache.

**Comment by ruf147** [comment]
Test : Chmod -R 777 /var/www/yana-server

**Comment by Raph94** [comment]
De mon côté, j'ai bien les droits...
L'installation a été faite avec le script auto.

Par contre j'ai remarqué que le fichier .database.db est créé mais qu'il n'a que des droits en 644. Peut être que ca a une influence... La base est créé, les tables ne peuvent pas être créées et quand on les appelle on aune fatal error...

**Comment by darkouz** [comment]
Toujours permission denied

**Comment by ingfred** [comment]
j'ai la meme chose. fait
sudo su
saisie de mot de passe puis
cd /var/www/yana-server

**Comment by ingfred** [comment]
Si tu fais un petit 
ls -ail
tu pourras comparer les droits avec ça : 
Ce sont les droits de mes fichiers yana.
266989 drwxr-x--- 11 www-data www-data   4096 avril 12 13:49 .
262612 drwxr-xr-x  4 www-data www-data   4096 avril 12 14:22 ..
267031 -rwxr-x---  1 www-data www-data   2725 avril 12 12:59 404.html
267034 -rwxr-x---  1 www-data www-data  10822 avril 12 12:59 action.php
267035 drwxr-x---  2 www-data www-data   4096 avril 12 12:59 api
267037 -rwxr-x---  1 www-data www-data    211 avril 12 12:59 apigen.neon
267038 -rwxr-x---  1 www-data www-data 607416 avril 12 12:59 apigen.phar
267413 drwxr-xr-x  2 root     root       4096 avril 12 13:49 c
267358 drwxr-xr-x  4 www-data www-data   4096 avril 12 13:40 cache
267039 drwxr-x---  2 www-data www-data   4096 avril 12 12:59 classes
267056 -rwxr-x---  1 www-data www-data   5760 avril 12 12:59 common.php
267057 -rwxr-x---  1 www-data www-data    989 avril 12 13:36 constant.php
267059 drwxr-x---  2 www-data www-data   4096 mai    3 17:12 db
267058 -rwxr-x---  1 www-data www-data    570 avril 12 12:59 db.json
267304 -rw-r--r--  1 www-data www-data      1 avril 12 13:25 dbversion
267061 -rwxr-x---  1 www-data www-data     41 avril 12 12:59 doc.bat
267062 -rwxr-x---  1 www-data www-data    139 avril 12 12:59 footer.php
266990 drwxr-x---  8 www-data www-data   4096 avril 27 10:17 .git
267029 -rwxr-x---  1 www-data www-data    138 avril 12 12:59 .gitignore
267063 -rwxr-x---  1 www-data www-data    255 avril 12 12:59 header.php
267064 -rwxr-x---  1 www-data www-data    341 avril 12 12:59 index.php
267066 -rwxr-x--x  1 www-data www-data  32293 avril 12 12:59 install.sh
267067 drwxr-x---  2 www-data www-data   4096 avril 12 13:41 log
267069 drwxr-x--- 29 www-data www-data   4096 mai    1 17:07 plugins
267033 -rwxr-x---  1 www-data www-data  36945 avril 12 12:59 RainTPL.php
267032 -rwxr-x---  1 www-data www-data   3189 avril 12 12:59 README.md
267246 -rwxr-x---  1 www-data www-data   2867 avril 12 12:59 setting.php
267247 -rwxr-x---  1 www-data www-data  15703 avril 12 12:59 socket.php
267248 drwxr-x---  3 www-data www-data   4096 avril 12 12:59 templates
267030 -rwxr-x---  1 www-data www-data    134 avril 12 12:59 .tool.sample.php

**Comment by ruf147** [comment]
Si je ne me trompe, il y a deja eu des posts similaire et qui je crois ont été résolues.

**Comment by Raph94** [comment]
Avant de poster, j'ai parcouru de long en large et c'est le seul poste que j'ai trouvé sur ce problème. Par contre, il se peut que je sois passé à côté. Si tu le retrouves, N'hésite pas :)

**Comment by theos10** [comment]
Pour lister un directory hors du /home/pi il faut etre root ou sudoer.
Tu a fait ton install en user ?
Si c est le cas c'est normal que ça ne marche pas.
Tu tape soit sudo su pourpasser en root, soit sudo install.sh

**Comment by theos10** [comment]
Une astuce, vire ton interface graphique, tu récupérera des ressources précieuses

**Comment by Raph94** [comment]
Merci pour ces retours, c'est sympa ! :)

Pour l'installation, j'ai fait :
sudo su
curl -L yana.madnerd.org|sudo bash

J'ai choisi installer et suivi l'installation qui est très bien faite.

Lorsqu'il est demandé de passer sur le navigateur, j'ai saisi :
http://ip_du_rpi/yana-server

Et là : erreur 404... Snif...

**Comment by Raph94** [comment]
Ah oui... J'avais installé au depart sur une Raspbian Jessie classique (erreur 404), j'ai donc changé pour une Raspbian Jessie Lite (erreur 404 aussi)...

**Comment by theos10** [comment]
Erreur 404 signifie qu'il ne trouve pas la page.
Donc verifie que ta conf apache ou lighthttp est correcte.
de base sans yana apache affiche it works.
il faut verifier la prise en charge des extension *.htm *.html
ensuite il faut activer le php.
dans ton /var/www/ tu cree un fichier index.htm basic, et un fichier index.php avec <php infophp(); ?>
si rien de s'affiche, verifie ou ton serveur web heberge les pages.
DocumentRoot /var/www

pour lighttpd voici un tuto : http://pazpop.fr/installer-un-serveur-web-leger-sur-son-raspberry-pi-lighttpd/

**Comment by theos10** [comment]
et un tuto apache : http://raspbian-france.fr/installer-serveur-web-raspberry/

**Comment by Raph94** [comment]
Merci pour ton retour. Je suis sur lighttpd.

En fait :
- j'ai bien var/www
- lorsque je mets un index.php dans www avec une valise info, ça fonctionne.

Lorsque le regarde les logs, je comprends (mais mon analyse n'est peut être pas la bonne) qu'il exécute bien install.php mais qu'il se plante lorsqu'il veut acceder à la table yana-configuration. J'ai la base .database.db qui est créée mais elle est à 0Ko.

Voici l'extrait des logs lighttpd :
2016-04-26 17:50:21: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Warning: SQLite3::query(): Unable to prepare statement: 1, no such table: yana_configuration in /var/www/yana-server/classes/SQLiteEntity.class.php on line 295
2016-04-26 17:50:21: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Fatal error: Call to a member function fetchArray() on boolean in /var/www/yana-server/classes/SQLiteEntity.class.php on line 299

**Comment by ruf147** [comment]
Alors en fouillant un peu sur google avec tes logs, je me disais bien qu iil y avait eu des  problèmes similaires et ou @idleman avait deja répondu : 

 - Je te conseille de faire une mise a jour de yana pour le second problème (cd /var/www/yana-server && git pull) et une reinstallation de la base pour le premier problème (supression du fichier db/.database.db puis tu refaitl'instal en suivant le formulaire d'installation).

Et pour les droits: 

sudo chown -R www-data:www-data /var/www/yana-server/

Si ca as pu aider.

**Comment by Raph94** [comment]
J'avais effectivement vu ce que tu indiques mais lorsque je fait un git pull, il m'indique que je suis déjà à jour :-/. Peut être qu'on peut le forcer à reprendre tout... Ce qui m'étonne c'est que le script d'auto installation fait lui même un fork du git donc ça me semblait normal d'être à jour.

Lorsque je fais une suppression de la base et que je relance install.php au travers du navigateur, il recrée la base vide et fait la même erreur.

**Comment by ldleman** [comment]
Yop,
Pas sûr que ça résolve ton problème mais j'ai corrigé un ptit truc sur la redirection de la page install, peux tu réeesayer l'installation voir ce que ça donne ?

**Comment by Raph94** [comment]
Salut !

Merci à toi. Je teste et te dit quoi ;)

**Comment by Raph94** [comment]
Incroyable, ça fonctionne !!!

J'ai fait un git pull, une mise à jour a été faite, puis j'ai supprimé la base de donnée.
J'ai relancé l'installation à partir du navigateur et là j'ai eu la page d'installation.

Je serais très intéressé de savoir ce que tu as changé (après avoir passé une bonne semaine à chercher :) )

Un grand merci à toi en tout cas !!

**Comment by ldleman** [comment]
Le problème semble venir d'une amélioration du système d'inclusion des fichiers que j'ai faite il y a quelques semaines qui était incompatible avec ma redirection d'install.
Bref entièrement de ma faute j'en ai peur :), désolé pour la perte de temps.

**Comment by Raph94** [comment]
Ce n'est jamais une perte de temps ! J'en ai profité pour parcourir le code et tenter de comprendre un peu son fonctionnement.
C'est toujours intéressant et sera utile pour plus tard ;)

**Comment by ldleman** [comment]
Les utilisateurs vont finir par être plus calés que moi sur le code :D, je clos l'issue, n'hésite pas a en ouvrir une autre si le problème réaparrais.

Merci pour le signalement.

**Comment by Tony13680** [comment]
Bonsoir,

Je me permets de réouvrir ce sujet car je n'arrive pas à terminer l'installation de YANA....
J'ai installé il y a quelques semaines Domoticz qui me sert d'interface pour diverses applications (allumer des prises à distance, utilisation de capteur de mouvement... etc.)

Ce soir, j'ai installé YANA, à la fin de l'installation, il est précisé de se rendre sur l'adresse IP de son Raspberry suivi de /yana-server. 
Je ne peux pas y accéder car une page se charge et il y est marqué : DOMOTICZ OFFLINE.

J'utilise l'adresse de mon raspberry afin d'accéder à l'interface de Domoticz.
Il doit y avoir un conflit entre Domoticz et YANA.

Quelqu'un a t-il une piste ?

Je vous remercie par avance :)
