### ISSUE TITLE
erreur "parse data" à la connection de yana V2

### ISSUE THREAD

**Issue by match44** [ldleman/yana-server#216]
Bonjour, 
j'ai un pb de connexion avec yana V2
j'arrive bien à me connecter au socket en mode root, j'ai le message "Server started on 0.0.0.0.0:9999"
par contre ça ne fonctionne pas, que ce soit avec l'appli android ou YANA v2 pour windows.
j'ai la même erreur quand je lance "FACE", "EAR", ou "MOUTH".

![erreur yana](https://cloud.githubusercontent.com/assets/18581580/14718300/2c2a4010-07f6-11e6-9e03-cbd802b4f12c.png)

une idée sur le pb ?
d'avance merci de votre aide.

**Comment by match44** [comment]
bonjour, 
j'ai fais une réinstalle complète, raspbian et yana-server, maintenant tout semble fonctionner, super :-)
je vais maintenant pouvoir concrétiser mon projet de domotique.
Merci idleman !

**Comment by ldleman** [comment]
@match44 Etrange comme pb, peut être un caractère qui se glissait avant la chaine json.
Content que ça se soit résolue de sois même, j'aime ce genre de bugs ^^.
Bonne continuation :p
