### ISSUE TITLE
STORY: mélange des éléments à exécuter au delà de 10

### ISSUE THREAD

**Issue by juliendiotworldtour** [ldleman/yana-server#217]
Bonjour Idleman, ça faisait un bout de temps! j'ai refais l'installation complète de Yana sur une nouvelle carte mémoire et pfiou, bravo pour le gain de temps à l'installation!

Je t'écris aujourd'hui car j'aimerai pouvoir réaliser des scénarios un peu plus complexes et avec un plus grand nombre d'éléments à exécuter (utilisation de 3 GPIO et lorsque certain passe à 0, d'autre passe à 1, etc). Toutefois, bien que mes actions GPIO/Pause soit correctement entrées lors de la création du scénario, leur exécution ne se font pas dans le bon ordre et ça me met un basard monstrueux, avec des éléments qui changent de positions dans la chronologie!
Aurais tu une petite idée d'ou pourrait venir mon problème? 

Merci Beaucoup!

P.S. ce soir, une belle vidéo sera présente sur YOUTUBE!

**Comment by ldleman** [comment]
Je pense que le gain de temps tu le dois a @maditnerd , moi j'ai rien fait ^^ (mais j'aime recevoir les remerciements immérités, c'est encore plus jouissif :D)

Peux tu m'envoyer l'export de ton scénario que j'essaye de reproduire le problème ?

**Comment by juliendiotworldtour** [comment]
J'ai contourné le problème en divisant mon gros scénario en 2 comme ça je n'exécute pas plus de 10 élément par scénario !

**Comment by ldleman** [comment]
Dommage, ça m'aurait aidé a reproduire le problème d'avoir le scénario de base, bon ben je vais essayer en placant + de 10 elements voir ce que ça donne

**Comment by ldleman** [comment]
j'ai update le plugin de scénario tu peux réésayer ?

**Comment by ldleman** [comment]
Corrigé et testé approuvé, voir  https://github.com/ldleman/yana-server/issues/238
