### ISSUE TITLE
Suggestion : GPIO en entree de scenario

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#219]
Je suis en train de jouer avec Cerber. Merci Alexandre et Idleman, superbe réalisation.
Sauf que je n'ai pas free mobile et que c'est mon fils qui va criser à force de recvoir des sms signalant des attaques rebelles autour de la maison (lui il a tout compris). Il faut bien tester !
D'ou la suggestion suivante : 
Est il envisagable de déclencher un scénario (Story) a partir d'un gpio ? Simplement sur le passage de 0 à 1, comme dans Cerber.
La combinaison Story/Cerber pourrait permettre un paquet de trucs amusants.

**Comment by ldleman** [comment]
Oui c'est pas faux ^^, faudrait que je pique son code d'interrupt a @Charal pour catcher les événement de GPIO, ça fait un moment que j'y pense mais je me disperse dans pas mal de trucs ^^, je met ton post en suggestion histoire de m'en rappeller, vais essayer de faire ça au plus rapide (pas plus d'un an ou deux d'attente :D)

**Comment by moebius911** [comment]
C’est une excellente idée. Actuellement tous mes scénarios se déclenchent via l’état d’un GPIO ou ping d’un équipement. Malheuresement yana ne le gérant pas, je suis obligé de passer par des scripts annexes.
Petite idée pour simplifier l’intégration, ne serait-il pas plus simple d’utiliser la date/heure de la CAUSES pour indiquer une période de lecture du GPIO. Ca évitera d’utiliser les interruptions.

Bonne journée

**Comment by ingfred** [comment]
Pas moins de deux ans ! J'aurais l'impression que tu bacles !

**Comment by ldleman** [comment]
@moebius911 oui ça faciliterait de lire les gpio uniquement toutes les minutes mais ça réduit la granularité à la minute justement ce qui est bof bof :), de plus une bonne gestion des interruption serait peut être plus optimisée qu'une grosse lecture générale de tous les gpio a chaques minutes.

@ingfred challenge accepted !!

**Comment by ldleman** [comment]
C'est fait donc je clos
