### ISSUE TITLE
Pb dashboard Warning: Cannot modify header information

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#220]
Hello,

J'ai eu un bug en voulant me connecter au dashboard yana ce soir

Warning: Cannot modify header information - headers already sent by (output started at /var/www/yana-server/classes/Event.class.php:1) in /var/www/yana-server/action.php on line 62

et en me deconnectant : 

Warning: Cannot modify header information - headers already sent by (output started at /var/www/yana-server/classes/Event.class.php:1) in /var/www/yana-server/classes/Functions.class.php on line 200

en fait je sait d'ou vient le probleme. il vient du fait que j'ai du, pour une autre utilisation que yana, modifier le php.ini dans etc/php5/apache2 et passer le "output_buffering" à "off" . Sauf que du coup ça me plante yana... est-il possible de forcer yana à passer outre ce parametre du php.ini ?

merci d'avance.

**Comment by ldleman** [comment]
Salut :)
Pour faire court, non :)

Le output buffering semble plus ou moins protégé de sorte qu'on ne peux le modifier via le code (par exemple avec un ini_set) sans mettre en place de l'usine a gaz (instructions htacess, bidouillage .ini dans tous les sens etc).

Je ne vois pas d'issues a ce problème excepté replacer le output buffering en position standard..
