### ISSUE TITLE
Erreur dans les relais filaires existants

### ISSUE THREAD

**Issue by DanChaltiel** [ldleman/yana-server#221]
J'ai cette erreur dans mes relais filaires existants :
Fatal error: Call to a member function getName() on a non-object in /var/www/yana-server/plugins/wireRelay/wireRelay.plugin.php on line 431

Screenshot :
![sans titre](https://cloud.githubusercontent.com/assets/15105152/14936539/b21a2dca-0eef-11e6-847e-4bb1167300bf.png)

Je crois que c'est parce que j'ai supprimé une pièce sans supprimer tous les relais associés. Du coup je ne peux plus ajouter de relais ni retirer celui-ci :-(

**Comment by ldleman** [comment]
Effectivement, je balance un patch rapide mais il faudra que j’empêche la suppression définitive des pièces pour éviter le pb

**Comment by darkpisto** [comment]
@ldleman , petite suggestion pour une "correction propre" : 
Lors de la suppression d'une pièce, ajouter une petite checkbox "Supprimer également tous ses relais ?" qui ajouterait un DELETE ON CASCADE et permettrait la suppression définitive. 
Si elle n'est pas cochée, on reste sur une "fausse suppression".
Et pareil lors de la suppression de plusieurs pièces à la fois : "Supprimer également tous leurs relais ?"

**Comment by ldleman** [comment]
Ça me parait compliqué, car il n'y a pas que les relais qui peuvent se greffer aux pièces il faudrait donc supprimer tous les périphériques sur chaque plugins qui viennent se greffer aux pièce ce qui est impossible étant donné que les plugins ne sont pas tous de moi et ne fonctionnent pas tous pareils, et les relais étant un plugin dissocié des pièces, il est tout a fait possible de ne pas avoir de plugin relais actif lors de la suppression d'une pièce.

Bref le plus simple me semble être de faire de la suppression logique

**Comment by darkpisto** [comment]
Effectivement, je n'avais pas la vision d'ensemble ^^
Merci pour l'explication Idleman :)

**Comment by ldleman** [comment]
Yapadkoi :D ! Bon normalement j'ai foutu la suppression en logique, j'ai mis a jour radiorelay, wirerelay et propyse pour gerer ce nouvel etat de suppression et j'en ai profité pour tester mon système d'update de base automatique, tenez moi au jus si ça pète de partout ^^, je clos l'issue
