### ISSUE TITLE
erreur commande vocale sur le serveur 

### ISSUE THREAD

**Issue by match44** [ldleman/yana-server#223]
Bonjour, 
j'ai un autre pb avec les commandes vocales, qui doivent exécuter une action "irsend" sur le server.
![erreur yana2](https://cloud.githubusercontent.com/assets/18581580/15015261/16a2bde8-120b-11e6-9fe2-5c9afde0c7a6.png)

un idée du pb ? 
d'avance merci

**Comment by ldleman** [comment]
Visiblement le plugin irsend n'envois aucune réponse, j'ai ajouté un correctif pour prendre en compte les non réponses de plugins.

**Comment by ldleman** [comment]
Si tu peux réessayer et me dire si c'est bon :)

**Comment by match44** [comment]
il ne semble plus y avoir d'erreur, mais la commande n'est toujours pas lancé
![erreur yana2 1](https://cloud.githubusercontent.com/assets/18581580/15092257/6e6fcfba-1464-11e6-8943-0de32cd42f92.png)

j'ai essayé manuellement la commande "sudo irsend SEND_ONCE lg_hifi KEY_HOME" et ça fonctionne

**Comment by match44** [comment]
oups c'est de ma faute, j'ai enlevé le sudo de la commande et ça fonctionne !
merci idleman

**Comment by ldleman** [comment]
Parfait :), je clos
