### ISSUE TITLE
Widgets disparu

### ISSUE THREAD

**Issue by Le-Raspinaute** [ldleman/yana-server#225]
Bonsoir, 

je tiens tout d'abord à féliciter tout ceux ayant contribué à YANA, c'est du très bon boulot !
Je viens maintenant m'adresser à vous, car jusqu'ici pas de problème majeurs, mais depuis aujourd'hui, lorsque que j'accède à l'interface web, une partie de la page (habituellement là où sont les widgets), est maintenant vierge.
Tous les autres onglets fonctionnent normalement.
Quel(s) élément(s) aurai(en)t pu provoquer un tel changement ?

Je vous remercie par avance.

**Comment by ldleman** [comment]
Yop ! Des logs d'erreur quelque part ? :)

**Comment by Le-Raspinaute** [comment]
Heu ... doivent-ils apparaitre à la place des widgets ou dans un fichier ?

**Comment by ldleman** [comment]
Ils peuvent apparaitre soit dans les widget, soit dans /var/log/tonserveurhttp/error.log soit dans yana-server/logs

**Comment by splatpope** [comment]
Pareil ici, après avoir ajouté mon plugin. J'utilisais un bouton sur le menu principal pour afficher sa page de préférence et l'ai déplacé vers la section préférences en pensant que le problème venait de la mais non, la page d'accueil reste vierge tant que mon plugin est activé.

**Comment by ldleman** [comment]
Il me faut des logs pour comprendre l'erreur, essaye de regarder dans /var/log/tonserveurhttp/error.log il doti y avoir quelque chose au moment ou tu tente d'afficher ta page blanche

**Comment by splatpope** [comment]
Y'a pas d'erreurs.

**Comment by splatpope** [comment]
Voici l'archive contenant mon plugin : https://drive.google.com/open?id=0BypdRN_TGzj2U2swNzl4b3JBSFU

Tu constateras la qualité extrême du code, hehe

La plupart des lignes commentées proviennent de l'ancienne version où on essayait de le faire fonctionner sur la page d'accueil, ce qui a été changé pour les raisons que j'ai expliquées.

**Comment by ldleman** [comment]
@splatpope ton pb viens de ton fichier plugin dans lequel tu a placé une en-tete doctype  html au mauvais endroit :   
![2016-05-17 17_32_37-c__workspace_php_perso_yana-server_plugins_chacon_chacon_managers plugin php](https://cloud.githubusercontent.com/assets/2620979/15328548/8aa46d5a-1c55-11e6-8495-5c37e743aad5.png)
A cet emplacement, l'en tete vas se repeter sur toutes les requettes même les requetes ajax faisant ainsi planter le json.

Supprime ce doctype et les espaces associés et tu ne devrais plus avoir de problèmes.

@Le-Raspinaute en attente de tes logs pour pouvoir te répondre :)

**Comment by splatpope** [comment]
Doux jésus, je ne me rappelle plus pourquoi j'avais été obligé de mettre ca, mais apparemment ca marche sans, merci ô grand prêtre du yana !

**Comment by Le-Raspinaute** [comment]
J'ai bien trouvé le fichier error.log dans le dossier /var/log/monserveurhttp, en effet il y a plein d'erreurs....

[error.log.txt](https://github.com/ldleman/yana-server/files/268670/error.log.txt)

**Comment by ldleman** [comment]
On dirait que ta base de donnée n'est pas disponible en ecriture, ça peux venir d'un problème de droit ou d'epsace disque.

Essaye déja de faire un 
`sudo chown -R www-data:www-data /var/www`
Ca devrait rendre les droits a ton serveur http sur tous les fichiers web

**Comment by Le-Raspinaute** [comment]
En effet, c'était simplement ça ...
Une simple erreur de droit !
Merci pour l'aide, j'aurais mis un bon siècle avant de trouver !

**Comment by ldleman** [comment]
Niquel je clos :) bonne continuation
