### ISSUE TITLE
Plugin Room Bug

### ISSUE THREAD

**Issue by theos10** [ldleman/yana-server#229]
Bonjour, 
suite a une mise a jour le plugin room n'affiche plus la liste des pieces, et impossible de modifier ou supprimer les pieces.

Ghislain

**Comment by ldleman** [comment]
Salut,
Peux tu spécifier ou la liste ne s'affiche plus ? Il te met quoi comme erreur dans les logs apache ?

**Comment by ldleman** [comment]
J'ai fait une petite modif préliminaire, peut tu faire un pull et reesayer ? :)

**Comment by theos10** [comment]
Salut,
C'est bon pour le plugin room, tout re fonctionne. Par contre je doit revoir le plugin doorV2 car j n'ai plus accès a la liste des pièces, la méthode d'accès a t'elle changé ?
et puis la sélection des icônes ne se fait plus, et je ne peux plus enregistrer des nouvelles portes.

**Comment by ldleman** [comment]
Normalement c'est toujours la même méthode, la différence c'est que les room ne sont plus supprimée complétement de la base, on passe en suppression logique pour  éviter que les objets liés a une pièce ne bugguent lors d ela suppression de celle ci.

**Comment by theos10** [comment]
C'est bon j'ai supprimé les rooms et recréé, et ça marche.
par contre mon plugin doorv2 n'enregistre plus rien dans la base.
il faut que je regarde ça.

**Comment by ldleman** [comment]
Oki doki :), je clos l'issue, n'hésite pas a rouvrir si tu constate une autre regression, merci pour le signalement :p
