### ISSUE TITLE
Modification pour compatibilité HTTPS

### ISSUE THREAD

**Issue by valentin8709** [ldleman/yana-server#230]
Salut idleman!
Juste un petit détail, quand Yana est en HTTPS, il y a le widget "commandes vocales" qui ne fonctionne plus: lorsqu'on clique sur une commande disponible pour l'activer, il envoie l'url en dure "http://XXX". Je propose cette modif dans le fichier plugins/dashboard-monitoring/dashboard-monitoring.plugin.php entre la ligne 196 et 197:

if (isset($_SERVER['HTTPS'])) { $ssl="https"; } else {$ssl="http"; }

Et remplacer la ligne 197:
$actionUrl = 'http://'.$host.':'.$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];
Par
 $actionUrl = $ssl.'://'.$host.':'.$_SERVER['SERVER_PORT'].$_SERVER['REQUEST_URI'];

Y'a ptêtre moyen de faire plus simple, je suis pas un maître de PHP mais ça m'a l'air propre, et ça marche (testé en http et en https).

Voili voilou =)

**Comment by ldleman** [comment]
La forme est plutot bien, ya juste moyen de simplifier en : 
$ssl= 'http'.(isset($_SERVER['HTTPS']))?'s':'');
Normalement c'est corrigé, merci pour l'info, n'hésite pas a rouvrir si problème :)
