### ISSUE TITLE
Widget probléme nom avec guillemet

### ISSUE THREAD

**Issue by Charal** [ldleman/yana-server#232]
Concernant les Widget, les Widget qui ont un une guillemet comme "chambre d'amis" ne s'affiche pas, j'ai regardé, avec toute les fois où tu fais des conversion, ça ressemble à ça dans ta bdd Dashboard "Chambre d&amp;amp;#039;amis".
@lex

**Comment by ldleman** [comment]
Tu veux dire une apostrophe ? Je ne parviens pas a le faire buger de mon coté, comme tu procède ?
![2016-05-17 10_45_42-yana server 3 0 6](https://cloud.githubusercontent.com/assets/2620979/15316347/cf4059a8-1c1c-11e6-9e0e-18ee4a3356ea.png)
