### ISSUE TITLE
Client v2 Problème de parse

### ISSUE THREAD

**Issue by Charal** [ldleman/yana-server#233]
Pour la partie vocale, j'ai pu voir que ça plante toujours lors de l'affichage des commandes, avec des problèmes de parse. (J'ai pris la version dont le lien est sur ton article sur le client v2).
Toutes les commandes ou y a un problème de parse sont bugger, il ne cherche même pas a les reconnaître.

J'ai pensé à faire une liste des commandes buger, mais je suis sûr que ça vient d'autre chose, juste par la récurrence des problèmes de parse, en fait il a l'air stable et récurent, le premier problème arrive à a 10éme commande, et tous les suivantes s’enchaînent toutes les 9 commandes vocales.
Tu dois avoir un problème d’extension de buffer ou un truc comme ça non ?

**Comment by ldleman** [comment]
Qu'est ce qui plante ? mouth, ear, face ou le serveur ?
Il te met quoi comme message d'erreur et sur quelle commande ?
Tu dis que le pb arrive a la dixième commande, c'est a dire a la dixième diction de la même commande ou lorsqu'il y a plus de 10 commandes disponibles dans yana ?

Je déporte ton soucis sur le ctrl+c qui est un bug a part a mon avis

**Comment by ldleman** [comment]
Reformulation pour moi même : 
Le programme **ear.exe** plante lorsqu'il fait un Get_Vocal_Command  sur le 10 éme traitement d'une commande complète ou il fait sa première erreur de parse puis toutes les 8 ou 9, Toutes les commandes vocales fonctionnent sauf celle ou il a eu une erreur de parse.

La récurrence des erreur pourrait indiquer un problème de buffer
les logs d'erreur : [logs.txt](https://github.com/ldleman/yana-server/files/269777/logs.txt)

**Comment by ldleman** [comment]
bug résolu
