### ISSUE TITLE
Yana android

### ISSUE THREAD

**Issue by ruf147** [ldleman/yana-server#236]
Salut @ldleman,

je cherche désespérément à récupérer le fichier.APK de la dernière version de Yana android sans à avoir à passer par le play store...

Serait-il possible de les avoirs?
Ou sont il disponible sur Github, auquel cas je serais passé à cote.

J' aurai de belles surprises à vous montrer, mais je ne peux pas encore en dire plus.

Merçi :)

**Comment by ldleman** [comment]
J'ai transféré à Alexandre roland qui s'occupe de l'APK pour lui demander de te contacter :)

**Comment by ruf147** [comment]
Merçi bien :D

**Comment by rol25** [comment]
Salut @ruf147,

Voici un lien pour obtenir le fichier apk: https://www.dropbox.com/s/q4vrslvsa5dcq1n/com.roland.yana-1.apk?dl=0

Si jamais cela ne te convient n'hésite pas à me contacter.

Amicalement,
Alexandre.

**Comment by ruf147** [comment]
Merci @rol25 , je vais pouvoir passer à la vitesse supérieure.

**Comment by valentin8709** [comment]
Au passage, ce serait cool de mettre Yana4All sur le market F-Droid, qui est un store full open source, et correspond bien aux valeurs du projet =)

**Comment by ldleman** [comment]
Et un dépot github la ce serait le top du top @rol25  :D

**Comment by valentin8709** [comment]
Ah oui j'approuve complètement l'idée d'un dépot github =D

**Comment by darkpisto** [comment]
je plussoie également pour le dépot github ! :)

**Comment by ruf147** [comment]
+1 pour git. Ca serait un gain de temps considérable.

**Comment by ldleman** [comment]
Bon ben @rol25 t'as la pression maintenant, plus le choix ^^ , en attendant je clos ce topic :p
