### ISSUE TITLE
Suggestion aide et installation

### ISSUE THREAD

**Issue by valentin8709** [ldleman/yana-server#240]
Je me permet de faire une petite suggestion, histoire de te donner un peu de boulot (pcq t'en as certainement pas assez je suppose ^^). Je trouve personnellement que les rubriques d'aide / d'installation, bien que très pratiques, gâchent un peu la mise en page. Du coup ce que j'ai fais dans mes plugins, c'est simplement un lien clickable qui affiche / cache l'aide de la manière suivante:

        <div><a onClick="this.nextSibling.style.display=((this.nextSibling.style.display=='none')?'':'none');" href="javascript:;"><legend>Installation</legend></a><span style="display: none;">
        <p> Ici l'aide et / ou les instructions d'installation </p>
        </span></div></p>

Voilà du coup ça cache un truc utile mais souvent pas très jolie. Ce serait cool de les intégrer dans les plugins story ou speechcommands par exemple. Bon c'est juste une suggestion, tu en fais ce que tu veux et quand tu veux hein =)

**Comment by ldleman** [comment]
J'ai séparé en deux pages, histoire de pas faire un slide de 2 km si ya bcp de doc ^^, merci pour la suggestion, je clos.
