### ISSUE TITLE
Suggestion plugin Story

### ISSUE THREAD

**Issue by valentin8709** [ldleman/yana-server#241]
Encore moi, je suis dans ma lancé alors je m'arrête pas... =/ Serait-il envisageable de pouvoir déplacer les effets dans le plugin Story? Genre je programme un petit scénario, je le joue puis je me rend compte que j'ai oublié un effet au début, du coup faut que je le supprime et que je refasse tout, vu que je ne peux pas rajouter une action et la déplacer au début. C'est pas vraiment critique mais ça peut être redondant lors de différents tests.

Voilà encore une fois c'est une suggestion parmi d'autres, tu fais ce que tu veux avec =)

Merci pour tout le travail que tu fais en tout cas =D

**Comment by ldleman** [comment]
C'est prévu mais j'essaye d'abord de stabiliser le plugin et de terminer les ajouts de fonctionnalités bloquants :)

**Comment by ldleman** [comment]
C'est fait ! :) Je clos, n'hésite pas a rouvrir si pb constatés :p
