### ISSUE TITLE
yana-server sur windows 8: impossible de définir la voix.

### ISSUE THREAD

**Issue by stephito** [ldleman/yana-server#243]
bonjour à tous,

Je n'arrive pas à faire parler YANA sur mon PC. Lorsque je lance une commande vocal, du genre "yana, quelle heure est il" , l'objet mouth de yana server for all me répond ceci: 
_impossible de définir la voix, Aucune voix correspondante n'est installée ou la voix a été désactivée_.
La voix virginie est  installé, malgré cela, la synthèse vocale de mon Windows 8 me sélectionne celle de Microsoft Hortense. 
Avez vous déja rencontré ce problème et avez une piste ?

Bonne soirée à tous.

**Comment by ldleman** [comment]
Ça ressemble beaucoup a un conflit 32/64 bits.
Windows étant ce qu'il est les vois installées pour 64bits n'apparaitrons pas/ne seront aps utilisables pour les programmes bits et inversement.

Si tu lance le manager de voix 32 bits via  
`C:\Windows\SysWOW64\Speech\SpeechUX\sapi.cpl`
Tu vois quoi ?

**Comment by stephito** [comment]
Alors, quand je lance sapi.cpl, je vois bien la voix de virginie qui est installée, alors que si je passe par le panneau de configuration WINDOWS,elle n'apparait pas.
Du coup, ça fonctionne en passant par sapi.cpl,

Merci.

**Comment by ldleman** [comment]
Okay donc c'est bien un pb de 64/32 bits, il te faut installer une voix compatible avec le 32 bits

**Comment by bartounet16** [comment]
Bonjour.
J'ai le même problème sous windows 10 64 bits:
Impossible de définir la voix. Aucune voix correspondante n'est installée ou la voix a été désactivée.
YANA V2.0
Comment installer les 32 bits? 
Il n'est pas prévu de compiler un yana 4 all 64 bits ?
