### ISSUE TITLE
Bug: Story - ajout d'effets

### ISSUE THREAD

**Issue by valentin8709** [ldleman/yana-server#244]
Salut Idleman, encore moi avec quelques problèmes sur le plugin Story. J'ai mis à jour le plugin depuis le dépôt git, et il y a un nouveau bug: lorsqu'on ajoute une cause / un effet dans un scénario, celui-ci ne peut être ajouté qu'en début de liste. Du coup il faut déplacer tous ceux d'après si on veut le placer à la fin...

Je ne sais pas si je suis très clair, alors je t'ai mis un screen, en essayant de rajouter un effet à la fin d'un scénario. Je ne pense pas que ce soit très compliqué à corriger, si t'as besoin de plus d'infos, n'hésite pas =)

![screenshot from 2016-05-26 18-42-54](https://cloud.githubusercontent.com/assets/6785619/15582595/11c47b22-2372-11e6-9551-a286847f60b6.png)

**Comment by valentin8709** [comment]
Est-ce que je suis le seul à avoir ce bug? J'ai bien essayé de supprimer le plugin et de le réinstaller en prenant le répertoire du git, mais même résultat...

**Comment by ldleman** [comment]
Non tu n'ets pas le seul, le correctif est en cours (en fait il est terminé mais j'ai pas trouvé la motive de récuperer le pc sur lequel il est pour push ^^)

**Comment by ldleman** [comment]
c'est corrigé, peux tu restester ? :)

**Comment by valentin8709** [comment]
Idle t'es vraiment une machine, t'es hyper réactif! C'est super cool pour la communauté, puis du coup le projet avance bien! =D

Sinon le bug est résolu! Seul léger "problème" est le fait qu'il y ait 2 espaces vides (les rectangles en pointillés) entre chaque effets / actions (sauf pour le tout premier et le tout dernier qui sont corrects). Bon c'est pas dérangeant, ça fait juste des espaces dans le vide quoi.

**Comment by ldleman** [comment]
T'habitue pas trop à la réactivité quand même, j'ai mes périodes de branlage absolus ^^
Oai j'ai vu ça pour le double espace, je me suis dis que c'était acceptable dans le sens ou ça me demande une usine a gaz de javascript pour faire disparaitre/apparaitre les blocs :)

**Comment by valentin8709** [comment]
Oèp pas de soucis, autant je suis maniaque la plupart du temps autant ça ne pose vraiment pas de problème ici. Sinon pour la réactivité je suis pareil je comprend tout à fait! Mais c'est quand même sympa de voir comment Yana avance en un mois, ça me motive à développer / mettre à jour mes plugins et donc continuer mes projets en cours, et c'est chouette =)

**Comment by ldleman** [comment]
Content que ça te motive :), c'est un peu la même chose de mon coté, sans les contributeurs pour me botter les fesses yana n'en serait pas ou il est aujourd'hui ^^.

**Comment by ldleman** [comment]
Je clos histoire de faire un peu de ménage
