### ISSUE TITLE
revision inconnue rpi2 B

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#245]
bonjour,

Apres réinstall du rpi et de yana après une attaque de bot ma révision devient inconnue : 
"Votre RPI dispose d'une révision (2a01041) inconnue de yana"

merci

**Comment by ldleman** [comment]
Peux tu faire un pull et réésayer ? normalement c'est corrigé

**Comment by zb2oby** [comment]
Salut, 
Yes ca fonctionne ! Merci à toi.

Petite suggestion au passage au vu de ce qu'il m'est arrivé. (piratage)
Il serait intéressant de prevoir sur le blog ou le wiki une petite rubrique sur la sécurisation d'un serveur avec les iptable fail2ban portsentry et compagnie pour les noobs comme moi. 

J'imagine par ex une simple entrée en matière avec redirection sur des tutos sérieux déjà existant s pour t'éviter trop de taff.
Cela sensibiliserais les néophytes et completeraient encore tes tutos

Cela dit pour ma part cela m'a permis d'apprendre de mes erreurs ;-) 

Encore merci pour la maj :-D

**Comment by ldleman** [comment]
Yapadkoi ! 

Pour la sécurité linux, l’ennui c'est que c'est un peu hors cadre, je pars du principe que les utilisateurs ont les connaissances de bases linux tout en sachant que ce n'est pas forcement le cas car je n'ai pas le choix, je manque de temps pour documenter correctement les fonctionnalités spécifiques à yana du coup je suis moins chaud a documenter des fonctionnalités linux sur lesquelles ont peux déjà trouver pas mal de doc sur le web.

Par contre si ça t’intéresse d'écrire une petite page wiki la dessus n'hésite pas a me la transmettre je la placerais sur le wiki yana :) 

Je clos n’hésite pas a rouvrir si pb
