### ISSUE TITLE
 Erreur l'accès au chemin d’accès C:\WINDOWS\system32\conf.json est refusé.

### ISSUE THREAD

**Issue by Gardaux** [ldleman/yana-server#251]
Lorsque je lance le launcher, j'ai bien l'écran "Bienvenue sur l'assistant de lancement YANA v2.0 !"
Je clique droit dans la barre de tache Windows (10), je clique sur Yana Launcher, j'ai l'écran "Bienvenue sur l'assistant d'installation YANA v2.0 !"
Je saisie les infos de la 1ere page, Adresse serveur, port, Token. Jusque là aucun soucis
A la 2eme page voix utilisée, localisation du client, au clique sur terminé j'obtiens une erreur dont je vous colle le log ci dessous : 
System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\WINDOWS\system32\conf.json' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   à System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   à System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   à System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   à System.IO.File.WriteAllText(String path, String contents)
   à launcher.MainForm.label26_Click(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnClick(EventArgs e)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.Label.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Vous avez une idée du probleme ?

Merci par avance

**Comment by ldleman** [comment]
C'était quoi le pb du coup ?

**Comment by Gardaux** [comment]
Le même problème qu'[ici ](https://github.com/ldleman/yana-windows/issues/22)ou [là](https://github.com/ldleman/yana-windows/issues/20) 
Une exception non géré
Le soucis doit venir de la décompression du fichier Winrar et 7Zip me signalent des noms de fichier trop long (supérieur à 256 caractères), ça viendrait de l'arborescence qui est très longue.
