### ISSUE TITLE
Ajout widget Evenements

### ISSUE THREAD

**Issue by moebius911** [ldleman/yana-server#252]
Bonjour

Est-ce que ça serrai possible d’ajouter un widget évènements qui synthétise ce qu’on a rentré dans la gestion des événements ?

Ce widget regroupera tout les évènements enregistré sous le format :
Nom eVenement 1	etat (actif / inactif)
Nom eVenement 2	etat (actif / inactif)
…..

Merci d’avance

**Comment by moebius911** [comment]
Tout compte fait c’est beaucoup plus facile que je ne le pensais. Puis, je pense qu’idleman à des choses plus urgentes à traiter. Comme le rafraîchissement auto des widgets par exemple :D
Perso j’ai abandonné, beaucoup trop complexe pour moi :’(

Pour ceux que ça intéresse il faut copier le code suivant à partir de la ligne 333 du plugin « eventmanager.plugin.disabled ».
Ca va ajouter un widget « Evénements » qui contient le nom de tous les évènements et le statut (actif/inactif). La couleur passe au rouge quand c’est inactif.

`// Action Widget Dashboard

function dash_widget_plugin_load(){
	global $myUser,$_,$conf;
	switch($_['action']){
		case 'dash_widget_plugin_load':
			header('Content-type: application/json');
			$response = array();
			$response['title'] = 'Evénements';
			    	$eventManager = new Event();
			    	$events = $eventManager->populate();

					foreach($events as $event){ 
			    		$action = $event->getContent();
			    		$recipients = $event->getRecipients();
						$nom = $event->getName();
						$etat = $event->getState()=='1'?'Actif':'Inactif';
						$couleur = $event->getState()=='1'?'#000000':'#FE0000';
						$response['content'] .= '<ul class="yana-list"> 
												<li style="font-size:14px;color:'.$couleur.'"> <strong class="badge"> '.$nom.' </strong>  STATUS : '.$etat.'  </li> 
												</ul>';
					}
					
					echo json_encode($response);

		break;
	}
}

// Desc Widget Dashboard

function dash_widget_plugin(&$widgets){
	// Affiche le widget
	$widgets[] = array(
		    'uid'      => 'dash_widget',
		    'icon'     => 'fa fa-file-text-o',
		    'label'    => 'Evénements',
		    'background' => '#A4A4A4',
		    'color' => '#ffffff',
		    'onLoad'   => 'action.php?action=dash_widget_plugin_load'
		);
}

Plugin::addHook("action_post_case", "dash_widget_plugin_load");
Plugin::addHook("widgets", "dash_widget_plugin");`

**Comment by ldleman** [comment]
Coucou :), je serais toi je ne perdrais pas trop de temps la dessus, le plugin event manager est voué a disparaitre, remplacé par le gestionnaire de scénario (qui permet plus de combo d'evenement / effets)

**Comment by moebius911** [comment]
Merci pour l’info
A ce moment-là je vais travailler directement sur ce plugin.
Bonne journée
