### ISSUE TITLE
erreur connexion serveur socket Scenario

### ISSUE THREAD

**Issue by moebius911** [ldleman/yana-server#254]
Bonjour

A chaque fois que je veux exécuter un scenario j’ai le message suivant :
Erreur connexion au serveur socket depuis yana-server, le serveur est-il allumé ? Connection refused

J’ai relancé yana, desactivé/activer le plugin story mais pas de changement.
J’ai fini par me rendre compte que je devais lancer manuellement la commande suivante dans un terminal pour que Scenarios exécute les commandes  : 
php /var/www/yana-server/socket.php

Est-ce que c’est normal ?

Merci d'avance

**Comment by zb2oby** [comment]
Hello.

Oui c'est normal. Si tu veux que la commande soit automatisée il faut creer un cron.
Sinon si tu utilise l'utilitaire d'installation de maditnerd il me semble qu'il se charge de le faire tout seul.

**Comment by moebius911** [comment]
Merci pour l'info
Dommage que ça ne soit pas noté dans la documentation de Scénarios.

Bonne journée

**Comment by ldleman** [comment]
Ben en fait ça l'est ....
![2016-06-16 15_29_17-yana server 3 0 6](https://cloud.githubusercontent.com/assets/2620979/16118405/35314bd8-33d7-11e6-90db-26722bbcbcc2.png)
![2016-06-16 15_29_29-yana server 3 0 6](https://cloud.githubusercontent.com/assets/2620979/16118406/3535f372-33d7-11e6-95a7-16614229a0e9.png)

**Comment by moebius911** [comment]
Je peut être mal détaillé mon problème.

Toutes les commandes ci-dessous sont dans le cron mais rien
ne se passe dans les scenarios.

Par contre quand j’ouvre une connexion putty et que je
lance la commande « php
/var/www/yana-server/socket.php » à ce moment-là ça fonctionne.

 

Si je lance la commande http://192.168.1.252/yana-server/action.php?action=crontab
sans lancer la commande « php /var/www/yana-server/socket.php »
voici le message d’erreur :

 



Fatal error:
Uncaught exception 'Exception' with message 'Erreur connexion au serveur socket
depuis yana-server, le serveur est il allumé ? Connection
refused' in /var/www/yana-server/classes/Client.class.php:19 Stack trace: #0
/var/www/yana-server/plugins/story/Story.class.php(158): Client->connect()
#1 /var/www/yana-server/plugins/story/Story.class.php(130): Story::execute(2)
#2 /var/www/yana-server/plugins/story/story.plugin.php(38): Story::check() #3
[internal function]: plugin_story_check() #4 /var/www/yana-server/classes/Plugin.class.php(191):
call_user_func_array('plugin_story_ch...', Array) #5
/var/www/yana-server/action.php(223): Plugin::callHook('cron', Array) #6 {main}
thrown in /var/www/yana-server/classes/Client.class.php on
line 19

 

 

Merci d’advance pour ton aide
Date: Thu, 16 Jun 2016 06:30:17 -0700

**Comment by zb2oby** [comment]
Hello.
Une histoire de droits peut-être ?

**Comment by moebius911** [comment]
Bonjour
Je reviens vers vous car malheureusement mon problème n’est toujours pas résolu proprement.
Actuellement je lance la commande suivante  dans le cron du raspberry : 
@reboot php /var/www/yana-server/socket.php 
Ça me corrige le problème, mais comme ce n’est pas noté dans la procédure d’installation, je dois avoir un problème quelque par.
Est-ce que quelqu’un sais comment est lancé le fichier « socket.php » ?
Ça m’aidera beaucoup pour trouver le point de blocage dans mon installation.
Merci d’avance

**Comment by SebNania** [comment]
Bonjour,
Je ne sais pas si c'est normal, mais de mon coté, j'ai installé Yana avec l'installer de maditnerd et il n'a pas ajouté l'entrée dans le cron.
Voici ce que j'ai en référence a Yana : 
 */1 * * * * wget http://localhost/yana-server/action.php?action=crontab -O /dev/null 2>&1
@reboot /var/www/yana-server/nerve /var/www/yana-server/action.php -O /dev/null 2>&1
Pourtant, le processus se lance de lui même au boot, peut être une de ces lignes qui le fait, j'avoue que j'ai pas fouillé le code pour aller voir.
Le fait est qu'au bout d'un moment, l'accès via Yana4All windows et/ou Android (j'ai testé sans utiliser le client Android pendant un certain temps au cas oui il mettrait le processus en croix) devient impossible et le port 9999 n'est plus écouté par php.
Je relance manuellement php /chemin/vers/socket.php et ça fonctionne de nouveau jusqu'a la prochaine fois.
je viens d'ajouter a mon cron :
@reboot php /var/www/yana-server/socket.php
je vais voir si c'est mieux, mais si je ne dis pas de bêtise, il ne relance pas le processus s'il se ferme avec cette méthode.

**Comment by ldleman** [comment]
@moebius911 Le fichier socket.php étant plutôt récent, il 'nexiste pas encore de lanceur automatique au démarrage de la machine, le cron @reboot php /var/www/yana-server/socket.php est donc une bonne solution. De souvenir madit l'a intégré aux dernière version de son installateur.

Dans l'idéal il faudrait donc dans ton crontab (avec les bons chemins vers yana) : 

> */1 * * * * wget http://localhost/yana-server/action.php?action=crontab -O /dev/null 2>&1
> @reboot /var/www/yana-server/nerve /var/www/yana-server/action.php -O /dev/null 2>&1
> @reboot php /var/www/yana-server/socket.php

Le premier active le système de cron php (utilisé par les plugins et notamment par scénario)
Le second active "nerve" qui détecte les changement en temps réel sur les gpio et les transmet a php (et aux plugins)
Le troisième active le serveur socket utilisé pour communiqué avec le(s) client(s) vocaux.

@SebNania  Étrange ton pb, il s’arrête au bout de cb de temps ? ya un message d'ereur quelque part dans les logs ? Por répondre a ta question/affirmation, @reboot permet seulement un lancement de la commande au démarrage de linux, donc si le programme plante, il ne se relancera pas.

Tu peux essayer de lancer la commande  
`php /var/www/yana-server/socket.php`
 manuellement et de faire tourner un moment comme ça tu verra les logs du serveur socket et donc potentiellement le problème qui survient.

**Comment by ldleman** [comment]
**nb:** je viens de mater l'installateur de madit, c'est encore mieux de passer par celui ci.

En effet madit n'utilise pas le cron @reboot pour lancer le serveur socket au d"marrage mais el programme supervisor, qui permet de faire la même chose ne mieux (puisqu'il redémarre le serveur en cas de plantage), de plus il définit un fichier de log dans 
`/var/log/yanaSocket.log`
Je vous conseille donc vivement de passer par l'installateur de madit.

Si vous voulez vous assurer que l'installateur de madit a bien configuré supervisor, vérifiez la présence et la cohérence du fichier 
`/etc/supervisor/conf.d/yana.conf`
Sur votre système

**Comment by SebNania** [comment]
Ah cool, merci pour ta réponse, je cherchais justement comment il se lançait (parce que j'ai installé yana avec l'installateur de madit, du coup je vais aller farfouiller le fichier log :) et j'ai pu vérifier que j'ai bien le script de lancement, je vais virer ma tache dans le cron du coup pour éviter un doublon.
Je vais refaire des tests et dès que ça ne répond plus j'irais récupérer ce qu'il y a dans les logs.

**Comment by SebNania** [comment]
Resalut,
Je suis allé fouiller dans les logs pour le plantage d'hier, tu peut voir que quelques heures avant on voit la fin d'une session depuis le client Android, puis un début de session de YANA4All windows qui fini sur 
> PHP Fatal error:  Call to a member function getLogin() on null in /var/www/yana-server/socket.php on line 109

D'ailleurs dans ces cas là, il est impossible de relancer tout de suite le socket.php, on a une erreur qui dit que le port est déjà utilisé, killall php dit que le processus est introuvable mais port toujours utilisé pendant quelques minutes, ensuite c'est ok.

Voici le morceau de log complet (au besoin dis moi je peut te filer le fichier complet si ta besoin) :
[26/08/2016 14:57:30] Client disconnected: Resource id #484
[26/08/2016 14:57:30] speak - GT-S7560M disconnected
[26/08/2016 18:29:32] New client connected: Resource id #510 (192.168.0.XYZ)
[26/08/2016 18:29:32] New client connected: Resource id #510
[26/08/2016 18:29:35] Try to parse received data : {"action":"CLIENT_INFOS","type":"listen","version":"2","location":"Salon","token":"MY TOKEN"}
[26/08/2016 18:29:35] Parsed action : CLIENT_INFOS
[26/08/2016 18:29:35] setting infos listen - Salon for Client 5 with user:MYUSER
[26/08/2016 18:29:35] Try to parse received data : {"action":"GET_SPEECH_COMMANDS"}
[26/08/2016 18:29:35] Parsed action : GET_SPEECH_COMMANDS
[26/08/2016 18:29:36] New client connected: Resource id #512 (192.168.0.XYZ)
[26/08/2016 18:29:36] New client connected: Resource id #512
[26/08/2016 18:29:36] Try to parse received data : {"action":"CLIENT_INFOS","type":"speak","version":"2","location":"Salon","token":"MY TOKEN"}
[26/08/2016 18:29:36] Parsed action : CLIENT_INFOS
[26/08/2016 18:29:36] setting infos speak - Salon for Client 6 with user:MYUSER
[26/08/2016 18:29:52] New client connected: Resource id #513 (192.168.0.XYZ)
[26/08/2016 18:29:52] New client connected: Resource id #513
[26/08/2016 18:29:52] Try to parse received data : {"action":"CLIENT_INFOS","version":"2","type":"face","location":"Salon","token":"MY TOKEN"}
[26/08/2016 18:29:52] Parsed action : CLIENT_INFOS
[26/08/2016 18:29:52] setting infos face - Salon for Client 7 with user:Seb
[26/08/2016 18:29:52] Try to parse received data : {"action":"GET_CONNECTED_CLIENTS"}
[26/08/2016 18:29:52] Parsed action : GET_CONNECTED_CLIENTS
PHP Fatal error:  Call to a member function getLogin() on null in /var/www/yana-server/socket.php on line 109

Fatal error: Call to a member function getLogin() on null in /var/www/yana-server/socket.php on line 109
 [26/08/2016 18:29:53] Launch Program
[26/08/2016 18:29:53] Could not bind to socket : #98 Address already in use

**Comment by ldleman** [comment]
Okay, voilà qui nous aide grandement !
A mon avis le problème viens du fait que tu perds la session (les serveur apache ayant un temps limite de sessions (1440 secondes par défaut soit 24 minutes), le client n'étant prévu que pour se logguer une fois et le serveur cherchant bêtement a récupérer le login sur un utilisateur qui a été vidé par la session ça cause l'erreur.

Mea culpa, j'ai jamais eu le problème parce que j'ai réglé mon temps de session serveur à 365 Jours :D !
Essaye de voir si ça plante toujours en augmentant ton temps de sessions sur le serveur (parametre session.gc_maxlifetime de /etc/php5/apache2/php.ini, penser a restart apache avec un sudo service apache2 restart après l'enregistrement du fichier).

Je corrigerais le problème plus proprement et sans besoin de reconfig du temps de sessions si le problème viens bien de là.

**Comment by SebNania** [comment]
Merci pour ta réponse,
a priori c'est lighthttpd qui officié sur mon raspberry (j'avoue que j'ai installé une image domoticz sans vraiment le soucier de regarder lol).
J'ai trouvé le fichier php.ini dans /etc/php5/cgi/php.ini
Je sais pas trop si il sera pris en compte je vais fouiller un peu, je connais pas du tout lighthttpd a vrai dire

**Comment by SebNania** [comment]
Salut,
Désolé en ce moment assez peu de temps pour réaliser réellement des tests, là je viens de me faire un petit test rapidement avec l'application Android et je pense qu'elle a clairement un souci, elle ne cesse de me dire que Yana-Server n'est pas a jour.
Bon du coup je me suis quand même connecté au raspberry et netstat -tanpu | grep 9999 donne une réponse vide, le socket.php n'est plus lancé (pourtant j'ai toujours le script de madit mis en place pendant l'installation pour le lancement.
J'ai donc relancé manuellement le socket.php, mais cette fichu application Android continue de me mettre son erreur a la noix.
Du coup je verrais pour faire des tests ce week-end car j'ai pas de pc windows sous la main.
En fait je m'interroge, est-ce que ce pb de socket.php qui fini par ne plus écouter est isolé chez moi ou est-ce que d'autres ont le pb, j'arrive pas a voir ce qui cause ça.
Edit : en fouillant les logs on dirait qu'au de la du fait que socket.php n'était pas lancé, il y a comme un souci quand je demande l'heure, je pensais que c'était l'appli Android qui envoyait rien au serveur mais a priori si : 

>  [02/09/2016 09:36:29] Call listen hook (v2.0 plugins) with params YANA quelle heure est il >  > 0,95
> 
> diction de la commande : YANA quelle heure est il
> Test de comparaison avec 75 commandes
> Commande ancien format trouvée, execution de l'url http://127.0.0.1:80/perso/yana-server/action.php?action=vocalinfo_hour&token=PHP Warning:  file_get_contents(http://127.0.0.1:80/perso/yana-server/action.php?action=vocalinfo_hour&token=): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
>  in /var/www/yana-server/common.php on line 141

Sebastien

**Comment by SebNania** [comment]
Je viens de tester de nouveau -> connexion impossible depuis l'android.
Le lance donc supervisorctl qui me dit :
> yana                             FATAL      Exited too quickly (process log may have details)
Je restart : 
> supervisor> restart yana
> yana: ERROR (not running)
> yana: started
> yana                             RUNNING    pid 12016, uptime 0:01:13
> tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      12016/php 

J'ai ajouté un nombre de tentative de lancement dans le fichier /etc/supervisor/conf.d/yana.conf :
startretries=3

Je ne sais pas si ça va changer quelque chose.

Le fichier log ne montre rien entre la dernière commande envoyée avant d'arrêter mon test ce matin vers 10h et le moment ou j'ai relancé le processus avec supervisor

**Comment by ldleman** [comment]
Merci pour ces retours malgrès ton temps limité tu me trouve pas mal de ptits bugs bien caché, notamment ce pb de /perso/  qui est entièrement de ma faute et que j'ai corrigé pour les prochains pull

j'ignore comment on augmente le temps de session sur lighttpd mais étant donné que c'est une config de php je suppose que c'est toujours dans le php.ini, il faut juste faire attention a trouver le bon php.ini (souvent yen a plusieurs qui trainent sur le système et un seul est pris en compte par ton serveur http)

**Comment by SebNania** [comment]
Pas de souci, j'aime bien Yana :) alors il faut aussi que je fasse mon possible pour filer de l'aide autant que possible a défaut d'avoir assez de connaissances pour faire des plugins etc.
Après un petit locale php.ini j'en ai 2, je viens d'augmenter le temps de session dans les deux (2592000), j'ai archivé le fichier log actuel pour repartir a vide et y voir facilement plus clair, petit reboot et je reviens vers toi si je vois quelque chose.

**Comment by SebNania** [comment]
C'est re moi, j'avoue j'y ai cru, cet après midi j'ai lancé a plusieurs reprises le client Android, aucun pb a chaque fois, toujours joignable sans pb.
Ce soir, je vais pour tester le client windows -> le serveur a refusé la connexion.
Netstat me montre que la connexion avec le client Android apparait en double et en statut finwait.
Par contre php n'écoute plus le port.
Je relance manuellement php /chemin/vers/yana/socket.php -> le lancement se fait et là, le client windows fonctionne.
Puis au bout de 2/3 commandes, sans raison -> ear.exe ne répond pas, je regarde php n'écoute plus le port, je n'ai rien qui puisse expliquer cela dans le fichier log.
A vrai dire dans le fichier log je ne vois que les échanges entre le client et le server yana mais pas d'erreur.
Voila pour le coup je suis pas plus avancé 
De ton coté ça marche? je suis un cas isolé? ça pourrait venir de lighthttpd a ton avis?

**Comment by SebNania** [comment]
voici ce qu'on peu trouver dans le fichier log, le "début" est la dernière session de test que j'ai faite avec le téléphone et Yana4All Android, ensuite on voit que c'est lorsque j'ai tenté la connexion de Yana4All windows que ça a planté et le supervisor ne semble pas avoir relancé le processus :

> [02/09/2016 16:31:56] New client connected: Resource id #192
> [02/09/2016 16:31:56] Try to parse received data : {"action":"TALK","parameter":"Il est 16:31"}
> [02/09/2016 16:31:56] Parsed action : TALK
> [02/09/2016 16:31:56] TALK ANIMATION : Try to send  to 0 clients
> [02/09/2016 16:31:56] TALK : Try to send Il est 16:31 to 2 clients
> [02/09/2016 16:31:56] send {"action":"talk","message":"Il est 16:31"} to Client 3
> [02/09/2016 16:31:56] send {"action":"talk","message":"Il est 16:31"} to Client 4
> [02/09/2016 16:31:56] Client disconnected: Resource id #192
> [02/09/2016 16:31:56]  -  disconnected
> [02/09/2016 16:31:56] Client disconnected: Resource id #168
> [02/09/2016 16:31:56] speak - Optimus G disconnected
> [02/09/2016 16:32:29] Client disconnected: Resource id #186
> [02/09/2016 16:32:29]  -  disconnected
> [02/09/2016 20:22:48] New client connected: Resource id #193 (192.168.0.IPLocal)
> [02/09/2016 20:22:48] New client connected: Resource id #193
> [02/09/2016 20:22:50] New client connected: Resource id #194 (192.168.0.IPLocal)
> [02/09/2016 20:22:50] New client connected: Resource id #194
> [02/09/2016 20:22:50] Try to parse received data : {"action":"CLIENT_INFOS","version":"2","type":"face","location":"Salon","token":"MYTOKEN"}
> [02/09/2016 20:22:50] Parsed action : CLIENT_INFOS
> [02/09/2016 20:22:50] setting infos face - Salon for Client 4 with user:MyUser
> [02/09/2016 20:22:50] Try to parse received data : {"action":"GET_CONNECTED_CLIENTS"}
> [02/09/2016 20:22:50] Parsed action : GET_CONNECTED_CLIENTS
> PHP Fatal error:  Call to a member function getLogin() on null in /var/www/yana-server/socket.php on line 109
> 
> Fatal error: Call to a member function getLogin() on null in /var/www/yana-server/socket.php on line 109

**Comment by ldleman** [comment]
J'ai oublié de te dire de faire un git pull, normalement tu ne devrais plus avoir cette erreur.
Après check dans le code sur cette ligne, le soucis ne viens pas de la session comme je le pensais, l'utilisateur de chaques interface est visiblement perdu au bout d'un moment j'ignore pourquoi, mais ça ne devrais plus faire planter le tout.

**Comment by SebNania** [comment]
Salut,
Le souci c'est que je suis déjà a jour et je l'étais lors des tests hier (git pull >
Already up-to-date.)
Je viens de faire a nouveau un pull dans le doute, je vais refaire des tests quand même au cas ou.

**Comment by ldleman** [comment]
@SebNania  des nouvelles de ton coté ?

**Comment by ldleman** [comment]
Je clos faute de réponses, n'hésitez pas a rouvir si le problème persiste.
