### ISSUE TITLE
Erreur à l'Installation 

### ISSUE THREAD

**Issue by sebaisnet** [ldleman/yana-server#255]
Bonsoir à tous,

D'abord bravo à Idle et merci à la communauté pour le travail accompli, je salive d'avance de pouvoir faire tourner le projet dans ma chaumière, seulement voilà...
A l'installation (automatique), tout se passe bien jusqu'au formulaire d'enregistrement :

"Notice: Use of undefined constant PROGRAM_NAME - assumed 'PROGRAM_NAME' in /var/www/yana-server/install.php on line 45 PROGRAM_NAME"

et quand je clique sur ce mauvais message, j'ai droit à :

Warning: require_once(__ROOT__/classes/Functions.class.php): failed to open stream: No such file or directory in /var/www/yana-server/common.php on line 55
Fatal error: require_once(): Failed opening required '__ROOT__/classes/Functions.class.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/yana-server/common.php on line 55

Vous l'aurez compris je suis un peu une quiche, mais j'ai cherché un peu du côté des pré-requis, et tenté l'installation de php sql, mais il me répond que les dernières versions sont installées, du coup je sèche...

Si une âme charitable avait une soluce...
Merci d'avance

**Comment by Gardaux** [comment]
Salut, 
Est ce que tu as correctement installer le serveur Apache ainsi que le module MySql et php ?
Au cas ou je te conseille de tout reprendre à zéro
1 : http://blog.idleman.fr/raspberry-pi-4-configurer-en-serveur/
2 : http://blog.idleman.fr/raspberry-pi-06-utiliser-le-gpio-et-interagir-avec-le-monde-reel/
          notamment la partie : Comment j’ai fait : 2. Partie programmation avec l'installation de La librairie se nomme [wiring PI](https://projects.drogon.net/raspberry-pi/wiringpi/download-and-install/)
3 : http://blog.idleman.fr/raspberry-pi-21-yana-un-nouveau-cur-domotique/

Voilà bon test

**Comment by ldleman** [comment]
@sebaisnet visiblement il te manque le fichier constant.php (https://github.com/ldleman/yana-server/blob/master/constant.php) car aucune de tes constantes n'as l'air déclarée, verifie qu'il est bien dans ton repertoir et que tu as bien téléchargé l'ensemble des sources yana.

**Comment by sebaisnet** [comment]
Merci messieurs pour ces précieux conseils, je m'y penche sur le champs et je vous tiens informés...

**Comment by sebaisnet** [comment]
Merci à vous deux, c'était bien cela le problème, j'avais procédé à l'installation automatique dans les pre requis et essayé seulement après d'installer le serveur...

Dans l'autre sens ça fonctionne du feu de Dieu !!

Bravo et merci 🙏
