### ISSUE TITLE
Yana et Domotics : Problème lors des requêtes http

### ISSUE THREAD

**Issue by kevinrolin** [ldleman/yana-server#262]
Bonjour,

Je suis entrain de réaliser une petite installation domotique et je souhaitais lier certaines actions à la voix grâce à Yana.

Pour ce faire, j'ai choisi la méthode http que nous propose domoticz.
Ex: http://192.168.0.19:8080/json.htm?type=command&param=switchlight&idx=5&switchcmd=On
Cette requête me permet d'allumer ma lampe sans aucun problème.

J'ai donc créer une reconnaissance vocale dans Yana pointant vers cette url.
Mais à chaque fois, le système me retourne { "status" : "ERR" }.
Pourtant si j'exécute l'url moi même cela fonctionne.

Petite précision, Yana et domoticz sont actuellement installé sur le même RaspBerry.
La requête exécutée "à la main" se fait sur un Windows7 du même réseau.

Auriez-vous une solution à me proposer ?

Merci

**Comment by SebNania** [comment]
Bonjour,
Est-ce que la commande passe manuellement (curl http://192.168.0.19:8080/json.htm?type=command&param=switchlight&idx=5&switchcmd=On) ?
Perso vu qu'on est sur la même machine j'aurais tendance a envoyer la commande sur le 127.0.0.1 directement, avez-vous testé?

Sebastien

**Comment by kevinrolin** [comment]
J'ai refait des tests directement en ssh depuis le raspberry:

curl http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1&switchcmd=On
ne fonctionne pas.

curl "http://127.0.0.1:8080/json.htm?type=command&param=switchlight&idx=1&switchcmd=On"
Fonctionne parfaitement.

**Comment by ldleman** [comment]
Yop !
Tu as quoi dans les logs de ton story ? Et dans les logs apache ? 
Qu'est ce qui te renvois le STATUS :ERR, c'est la variable url_result ?

Si tu créé un fichier php de test avec la ligne 
```php
<?php  echo file_get_contents('ton-url'); ?>
```
Ça donne quoi ?

**Comment by ldleman** [comment]
@kevinrolin  des nouvelles ? Je peux clore ?

**Comment by ldleman** [comment]
Sans réponses de ta part je clos le sujet, n'hésite pas a rouvrir si tu constate de nouveau le problème
