### ISSUE TITLE
suggestion story

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#263]
Bonjour Idle.
Petite suggestion : est-il possible d'ajouter dans story les heures de lever et coucher de soleil dans les scénarii ?
Je l'ai fait a l'arrache en ajoutant :
 '{SUNRISE}'=>date_sunrise(time(), SUNFUNCS_RET_STRING, 38.4, -9, 90, 1),
  '{SUNSET}'=>date_sunset(time(), SUNFUNCS_RET_STRING, 38.4, -9, 90, 1),
dans le story.class.php, mais il le faudrait parametrable en fonction des latitude, longitudes, etc. Et que cela sorte en format date.
L'idee est d'allumer les lampe au coucher du soleil. Ou de lancer le bruit de la poule ou du coq  au lever.
Ambiance bucolique assurée.

**Comment by ldleman** [comment]
C'est fait, par contre ça nécessite une reinstall complète de yana (car ajout de deux variables core pour la latitude et la longitude). Tiens moi au jus si ça fonctionne que je puisse clore :)

**Comment by ingfred** [comment]
Tu peux clore

Genial.merci.

**Comment by valentin8709** [comment]
Salut Idle! Merci pour cet ajout, et meri à ingfred pour la proposition =)
Cette petite fonctionnalité m'intéresse mais je ne voudrai pas réinstaller Yana (j'ai fais trop de modifs dessus, la flemme de sauvegarder / réintégrer). Est-il possible d'éviter ça et de faire une mise à jour à chaud? En gros comment ajouter les variables dans le core direct?

Merci bien =)

**Comment by ldleman** [comment]
C'est chaud sans faire de maj, de mémoire j'ai surtout modifié la classe système et certains fichiers du plugin story, tu peux donc essayer de copier uniquement class/System.class.php et plugs/story mais pas de garantie que ça fonctionne, j'ai du pas mal toucher aux fichiers depuis ta version. 

D'une manière générale si tu dois customiser ton code yana, essaye de passer par un plugin spécialisé au lieu de toucher direct au core, sinon tu sera sans arret emmerdé dès que tu voudra profiter des updates.
