### ISSUE TITLE
Yana4all ne marche plus depuis le dernier Git Pull

### ISSUE THREAD

**Issue by juliendiotworldtour** [ldleman/yana-server#265]
Salut @ldleman , je t'écris pour te signaler que depuis le dernier GitPull, Yana4all ne lance plus les commandes. Pourtant celles-ci s'affichent comme il faut. Il n'y a juste pas de réaction. Pourtant lorsque je passe par le server, ça marche. Le bug vient depuis la dernière MAJ. Une petite idée??

Merci beaucoup!

**Comment by ldleman** [comment]
Salut Julien, quand tu parles de yana4all tu parles du client Android ou de windows? 
Le 11 juil. 2016 3:33 PM, juliendiotworldtour <notifications@github.com> a écrit :Salut @ldleman , je t'écris pour te signaler que depuis le dernier GitPull, Yana4all ne lance plus les commandes. Pourtant celles-ci s'affichent comme il faut. Il n'y a juste pas de réaction. Pourtant lorsque je passe par le server, ça marche. Le bug vient depuis la dernière MAJ. Une petite idée??

Merci beaucoup!

**Comment by juliendiotworldtour** [comment]
Il s'agit du client Yana4all Android. Pourtant, quand je rebascule vers mon ancienne sauvegarde de Yana Server, le client Android marche. J'ai essayé de redémarrer mon smartphone ou bien le Rpi mais, bien que mes commandes vocales apparaissent, elle ne réagissent pas lorsque je clique dessus.

**Comment by ldleman** [comment]
Malheureusement je ne gère pas la partie Android, je maintient 
uniquement le client windows et le serveur, il faut demander a Alexandre 
Roland 
<https://play.google.com/store/apps/developer?id=Alexandre+Roland> , 
l'auteur de l'application :)

Amicalement,
Idle

**Comment by juliendiotworldtour** [comment]
Je me doutais bien de la réponse mais je ne pense pas que cela vienne du client Android, car avant de mettre a jour Yana Server, ça fonctionnait.

**Comment by ldleman** [comment]
Techniquement ça ne peux pourtant venir que de là dans le sens ou le 
serveur et le client yana windows fonctionnent bien ensemble, je pense 
donc qu'il s'agit

d'une mise à jour du serveur qui n'a pas été prise en charge par le 
client android ce qui est tout a fait possible car je ne communique par 
particulièrement avec Alexandre roland (je sais, c'est pas bien mais on 
est pas mal chargé tous les deux ^^)

Du coup il faut voir avec lui ce qui plante dans son code, ça ne doit 
pas être grand chose car je n'ai pas fait de modif conséquentes sur le 
serveur récemment.

Amicalement,
Idle

**Comment by juliendiotworldtour** [comment]
Merci beaucoup @idleman! Est ce que l'erreur peut venir du port et du socket que j'utilise ? Je suis en port 80 et socket 9999.

**Comment by ldleman** [comment]
C'est peut probable, ces ports sont ceux préconisés pour une bonne 
utilisation de yana.

Il faut voir avec Alexandre pourquoi le lancement d'une commande ne fait 
plus rien, j'ignore si il y a des logs sur son application et comme je n'ai

pas les sources je ne peux pas tenter le debug moi même.

Quand tu lance socket.php manuellement sur ton serveur tu vois la 
commande arriver dans la console ou même pas ?

Amicalement,
Idle

**Comment by rol25** [comment]
Bonjour juliendiotworldtour, 
Je ne sais pas si tu as résolu ton problème depuis le temps mais je te conseil de faire une clean installe avec la nouvelle version du serveur sans utiliser "git-pull", cela devrai résoudre ton problème si ce n'est déjà fait. Sinon n'hésite pas à me contacter directement via le mail disponible dans le fiche du playstore.
Amicalement,
Alexandre Roland.

**Comment by ldleman** [comment]
Oaip normalement c'est résolu, je clos, n'hésite pas à rouvir si tu constate de nouveau le problème
