### ISSUE TITLE
probleme d'installation de YanaServer

### ISSUE THREAD

**Issue by Gardaux** [ldleman/yana-server#267]
Lorsque je lance l'installation en mode automatique, via la commande : curl -L yana.madnerd.org|sudo bash

J'ai un message d'erreur : "Le gestionnaire de paquet apt-get est HS"
Vous avez une idée du problème ?
Merci par avance

**Comment by maditnerd** [comment]
Pourrais-tu essayer de mettre à jour apt-get ?
```
sudo apt-get update
sudo apt-get upgrade
```

**Comment by Gardaux** [comment]
Le problème venait de la version installée sur mon raspberry, je suis repassé à une wheezy.
Mais un problème subsiste sur le fonctionnement de Yana-All.
Un message d'erreur me dit que :" Aucune connexion n'a pu être établie car l'ordinateur cible l'a expressément refusée 192.168.0.202:9999"
je continue à chercher....

**Comment by Gardaux** [comment]
Le problème venait d'une mauvaise installation de base, difficile de faire fonctionner Yana Serveur et Yana all avec la version Jessie.
