### ISSUE TITLE
GPIO RPI 3 B inconnu

### ISSUE THREAD

**Issue by SebNania** [ldleman/yana-server#269]
Bonjour,
Voici le message retourné par Yana : Votre RPI dispose d'une révision (a22082) inconnue de yana, il n'est pas possible d'afficher ses pins.
Serait-il possible de voir pour intégrer le GPIO de ce modèle?
Merci d'avance
et encore bravo pour ce soft que je découvre depuis seulement quelques minutes mais qui semble génial :)

Sebastien

**Comment by SebNania** [comment]
Voici ce que j'ai pu trouver a ce sujet :
![raspberry-pi-3-gpio-layout-model-b](https://cloud.githubusercontent.com/assets/2053987/17858575/830573a0-6886-11e6-9695-ee6064c21857.png)

**Comment by ldleman** [comment]
Okay, c'est ajouté normalement, peux tu confirmer ?

**Comment by SebNania** [comment]
Hey, et ben oui je confirme que c'est ok après mise a jour, merci  beaucoup!! :)
