### ISSUE TITLE
config confidence ComboRelay et Dashboard

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#271]
Bonjour,

Mon problème vient de l'utilisation du plugin ComboRelay. En effet lorsque je modifie la confidence dans YANA celle-ci n'est pas prise en compte par ComboRelay. Je suis alors obligé de modifier la confidence en "dur" dans le code du ComboRelay.plugin  ce qui n'est pas très pratique. 
Je voulais donc savoir si l'un d'entre vous savait ou se situait (dans quel fichier, quelle ligne)  la liaison entre la config de confidence yana sur le dashboard et les plugins de relais dans le but de copier cette ligne de code dans le plugin ComboRelay pour ne plus avoir à modifier la confidence en dur dans ce plugin.

merci à vous

**Comment by zb2oby** [comment]
Bon ba en fait j'ai trouvé...il manquais le +$conf->get('VOCAL_SENSITIVITY')  après le 'confidence'=>('0.XX'  pi c tou... désolé du dérangement. si ça peut servir à quelqu'un... cela donne donc :
 
$response blablabla.... ,'confidence'=>('0.XX'+$conf->get('VOCAL_SENSITIVITY')));

**Comment by ldleman** [comment]
N'hésite pas a le signaler au créateur du plugin Cgsk854 depuis le market  :)
