### ISSUE TITLE
Module cerber ne repond plus ! 

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#273]
Bonsoir à tous.
Plus moyen de valider les données pour parametrer cerber.
Cliquer sur enregistrer ne donne plus rien.
Je passerais bien par les scenarii dont je suis friand mais gpio<3 et le capteur est branche sur le 25 !

**Comment by ldleman** [comment]
Le plugin étant contributeur, il faut contacter direct @Charal via le market : [http://market.idleman.fr/index.php?module=packet&block=contact_owner&id=86](http://market.idleman.fr/index.php?module=packet&block=contact_owner&id=86)

**Comment by ingfred** [comment]
Bonjour à tous.
Idle : on peut clore.
Il y un un petit pb dans les arborescences et l'install à modifier. Alex m'a dit s'en occuper dès qu'il en aura le temps.

**Comment by ldleman** [comment]
Okay :)
