### ISSUE TITLE
impossible de se connecter sur yana.local/yana-server sur un autre PC que la rapsberry

### ISSUE THREAD

**Issue by shobu13** [ldleman/yana-server#275]
Bonjour a tous, comme le dit le titre du message, j'ai fait l'installation de yana en utilisant apache et j'ai installer php5, mysql et phpmyadmin séparément. J'ai tester chaque composant (y compris le yana-server) séparément sur la raspberry et tout fonctionnait bien, mais voila, impossible d'accéder a l'interface via Windows et google chrome, cela dit, je ne peut pas non plus accéder au fichier "index.php" de apache, alors le problème vient t'il de apache ou de la rapsberry ? Sachant que j'ai désinstaller apache par la suite, refait l'installation de yana, en utilisant cette fois lighttpd, et paf, ça ne marche toujours pas. 
Je précise que j'ai nommer yana... "yana" lors de l'installation.

**Comment by SebNania** [comment]
Salut
effectivement je pense que ton pb est plus global, si tu mets l'adresse du RPI brut tu devrais avoir la page par défaut de apache2/lighttpd, si tu ajoute /yana-server tu tombe sur yana
si tu envoi un netstat -tanpu | grep 80 tu vois quoi?
Si rien alors ton serveur http n'écoute pas le port, il est peut être pas lancé?
Pour le vérifier tu peut faire un service --status-all | grep light
Tu dois avoir : [ + ]  lighttpd
quand tu dis que tu n'a pas accès a tout ça, depuis le raspberry ou depuis une autre machine?
tu a installé comment ton RPI? une raspbian, autre chose?

**Comment by shobu13** [comment]
Mon rasp' est sous raspbian, je l'ai installer avec NOOB (carte sd par défaut) et j'ai accès aux pages sur la raspberry effectivement, mais pas depuis une autre machine. (Je parle avec apache je n'ai pas tester avec lighttpd), je vais essayer tes commandes et je te redirait :)

**Comment by shobu13** [comment]
HELLOW ! Désoler du temps d'attente pour la réponse :p J'ai pas trop eu le temps de bosser sur ma rasp récament. Concernant mon problème, j'ai réussit a le résoudre tout seul et je me suis sentit bien con x). En fait, je n'utilisait que l'IP local de ma rasp, et non son IP sur le réseau, donc évidament que je ne pouvait y accéder x) Vous pouvez m'appeller "Boulet du jour" sur ce coup là :D
