### ISSUE TITLE
Installation sur un Ubuntu (non Raspberry)

### ISSUE THREAD

**Issue by Singman33** [ldleman/yana-server#277]
Bonjour,
Y at t'il une documentation pour l'installation sur autre chose qu'une Raspberry ?
Pour l'instant, que ce soit avec le script ou en manuel, le résultat est catastrophique :
le crontab pointe sur `localhost/<script>` alors que l'adresse est`localhost/yana-server/<script>`
un login me sort des erreurs de débutant dans le script PhP (`Switch statements may only contain one default clause in /var/www/yana-server/action.php on line 392`).
et j'en passe (erreur sur un include socket sur un script python).

A moins que le repository de yana-server soit vérolé ?
Je l'ai déjà installé une fois sous Windows et il me semble qu'a part quelques petits ajustements, tout était bien.

**Comment by ldleman** [comment]
Le dépôt n'est pas vérolé, l'install fonctionne correctement chez tous les utilisateurs, le problème doit donc venir de ton environnement ou de ta manip d’installation.

Globalement l'installation de yana-server sur rpi ou sur ubuntu ne doit pas differer.
Tu peux installer manuellement une solution LAMP (sans mysql) + sqlite et installer le cron à la main.

Je testerais le script d'install auto sur un ubuntu dès que j'aurais un peu de temps mais sur mes derniers tests ça fonctionnais niquel.

**Comment by Singman33** [comment]
Est ce qu'il y a une marche a suivre spéciale ? Le problème n'est pas que dans le cron, mais dans tout le reste qui s'installe n'importe comment. Un pré requis PhP peut être ? Je suis en version 7.0.8

**Comment by ldleman** [comment]
Ca explique pas mal de choses, yana est développé en 5.3 et n'a jamais été testé en php 7.0.8.
Visiblement php 5.3 acceptait les double default sans raler (curieux d'ailleurs), 7.0.8 est plus logique ^^, peux tu faire un pull j'ai corrigé cette erreur

**Comment by ldleman** [comment]
@Singman33  des nouvelles ? Je peux clore le sujet ?

**Comment by Singman33** [comment]
je teste ce week-end :)

**Comment by Singman33** [comment]
L'nstallation s'est déroulée correctement, il n'y a plus d'erreur. Je ferme ce ticket, et je regarde si tout fonctionne correctement.
