### ISSUE TITLE
probleme communication sumsung et windows

### ISSUE THREAD

**Issue by ammous** [ldleman/yana-server#279]
Bonjour
j'ai ce message sur windows lorsque j’exécute une commande depuis mon portable Samsung
Connection refused in /var/www/yana-server/common.php on line 140
est ce que vous pouvez m'aider
merci

**Comment by ingfred** [comment]
Bonjour Ammous.
As tu regardé les droits sur ton dossier yana-server ?
cd /var/www/yana-servre
ls -ail.

**Comment by ldleman** [comment]
Tu as visiblement un problème de connexion au socket, as tu bien lancé ton serveur socket.php ? As tu débloqué le port 9999 sur tes firewalls / routeurs en interne ?

**Comment by ldleman** [comment]
Sans réponses de ta part je clos le sujet, n'hésite pas a rouvrir un topic si le problème persiste.

**Comment by ammous** [comment]
c'est ok merci
