### ISSUE TITLE
yana  commande vocale execution serveur

### ISSUE THREAD

**Issue by jbouziat** [ldleman/yana-server#280]
Je n'arrive pas à executer une commande sur le serveur.
Au niveau du client la phrase est bien reconnue

Dans la log je trouve ceci : action=speechcommands_execute&commande=1
response : {}
Version yana serveur 3.0.6
Version client windows 1.0.4
Merci pour votre aide

**Comment by ldleman** [comment]
Peux tu préciser la commande énoncée ? quel fichier de log tu regarde, celui du serveur ou celui du client ?

**Comment by ldleman** [comment]
Sans réponse de ta part je clos le sujet, n'hésite pas a rouvrir si tu as de nouveaux le problème.
