### ISSUE TITLE
Gros joli plantage de la base

### ISSUE THREAD

**Issue by ingfred** [ldleman/yana-server#282]
Bonjour à tous .
J'ai eu un beau plantage de base avec gros message d'erreur que j'ai bien entendu oublié de copier.
J'ai copié la base .database.db sur mon pc, viré quelques lignes de cmd_result dans la table yana_configuration a l'aide de sqliteman, recopié sur raspi et cela est reparti. Puis replantage. Puis re-nettoyage et ok pour l'instant.
Il semble que la table yana_configuration se peuple de cmd_result (jusqu'à 1019 lignes) puis plante le jouet. Une idée?

**Comment by ldleman** [comment]
Salut :)
cmd_result est une valeur de conf qui récupère le retour de la dernière commande système envoyée depuis un scénario, normalement elle est sencée être unique.

Tu as fait un scénario particulier pour arriver a ce résultat?

**Comment by ingfred** [comment]
Salut Idle.
Je ne pense pas. Je les ai relus pour voir si je n'ai pas fait d'anerie et n'ai rien trouvé.
Si tu me promets de ne pas faire clignoter ma lampe de chevet je peux t'envoyer une copie du dossier avec la base.

**Comment by ldleman** [comment]
Pourquoi pas, ce qui m'ennuie c'ets que je n'arrive pas a reproduire le pb de mon coté quel que soit le scénar.
As tu bien la derniere version en date de yana ?

**Comment by ingfred** [comment]
Bonjour Idle.
Oui j'ai la dernière version.
Ceci dit le pb n'est pas réapparu à ce jour.
Si tu veux cloture l'issue. On se penchera dessus sérieusement si cela réapparait

**Comment by ldleman** [comment]
Okay n'hésite pas si ça se reproduit :)
