### ISSUE TITLE
Problème installation "fraîche" sur RPI3

### ISSUE THREAD

**Issue by Pigloox** [ldleman/yana-server#283]
Bonjour,

Lors d'une toute nouvelle installation sur un RPI3 (Jessie Pixel) à partir de l'installateur, tout se passe bien, jusqu'au moment où l'on doit se connecter avec un navigateur.

J'ai ces alertes : 
Warning: include(classes/GPIO.class.php): failed to open stream: No such file or directory in /var/www/yana-server/install.php on line 16

Warning: include(): Failed opening 'classes/GPIO.class.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/yana-server/install.php on line 16

Fatal error: Class 'GPIO' not found in /var/www/yana-server/install.php on line 211

Est-ce une erreur de ma part ou un bug ?

**Comment by Thetortuga** [comment]
Bonjour,

Même problème de mon côté ! Sur une installation toute fraîche sur une RPI3. 

> Warning: include(classes/GPIO.class.php): failed to open stream: No such file or directory in /var/www/yana-server/install.php on line 16

> Warning: include(): Failed opening 'classes/GPIO.class.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/yana-server/install.php on line 16

> Fatal error: Class 'GPIO' not found in /var/www/yana-server/install.php on line 211

Merci de votre aide !

**Comment by ldleman** [comment]
Effectivement c'est ma faute, petite régression lors du dernier commit, pouvez vous réessayer ? :)

**Comment by Pigloox** [comment]
Merci de votre réactivité mais j'ai maintenant un autre problème, mon navigateur affiche ceci ;

> Not Found
> 
> The requested URL /yana-server/ was not found on this server.
> 
> Apache/2.4.10 (Raspbian) Server at 192.168.1.27 Port 80

**Comment by Pigloox** [comment]
Pour moi, c'est fonctionnel, installation réussie
Merci ;-)
