### ISSUE TITLE
Problème install yana - apt-get

### ISSUE THREAD

**Issue by Blacksly** [ldleman/yana-server#284]
Salut a tous ! 

J'essaye d'installer yana depuis ce matin avec la commande : curl -L yana.madnerd.org|sudo bash

Cependant a chaque fois qu'il essaye d'installer les paquets j'ai cette erreur : 
 Le gestionnaire de paquet apt-get est HS                                │
│ * Soit celui-ci a été interrompu                                        │
│ * Soit il est en cours d'utilisation par un autre programme             │
│ Supprimer le fichier de verrou est probablement la solution             │
│                                                                         │
│ Voici le message d'erreur:                                              │
│  E: L'option « s » de la ligne de commande [d'origine -s] est inconnue. 

Une idée ? merci 

Je précise que je suis sur un rpi 2 avec la dernière version de raspbian

**Comment by Blacksly** [comment]
D'ailleurs il y a un bug sur install.php ligne 211 : 
require_once(__DIR__.'classes/Gpio.class.php');
Il manque un "/" : 
require_once(__DIR__.'/classes/Gpio.class.php');

**Comment by marsho94** [comment]
Bonjour. Je confirme. 

J'ai tenté d'installer Yana sur Wheezy, Jessie et Jessie Lite impossible de lancer Yana...

Je déprime ! Sniff...

**Comment by Blacksly** [comment]
J'ai réussi a l'installer avec les commandes données plus bas, mais pas en les lançant toute d'un coup. Et pas oublié d'installer apache2

**Comment by marsho94** [comment]
Désolé je débute... DIR je dois mettre la direction ou juste marquer DIR ?

**Comment by Blacksly** [comment]
C'est pour un Raspberry ? Et c'est avec la commande curl que tu a ça ?

**Comment by marsho94** [comment]
Oui un rasp. Non, c'est à la suite d'un 

sudo aptitude update
sudo aptitude upgrade

**Comment by marsho94** [comment]
Aussi à l'installation de Yana server il me demande si je veux installer lighttpd comme serveur par défaut car il a détecté apache. Ca te parle ? Dois l'installer ou continuer sans ?

**Comment by Blacksly** [comment]
Ha OK je comprend, tu peux appuyer direct sur entrer, qui correspond a N le choix par défaut, en général c'est la bonne solution ^_^

**Comment by Blacksly** [comment]
Si il détecte apache pas besoin de mettre Light tp. 
A la fin de l'instal, surtout du gît clone, il faudras que du déplace le dossier du serveur qui est dans /var/www/yana-server dans /var/www/html

**Comment by maditnerd** [comment]
Je confirme pour le problème avec la ligne 211.

![image](https://cloud.githubusercontent.com/assets/2841495/20152115/3ebb39bc-a6bd-11e6-929b-cc3ec56474ae.png)

Pour le script, c'est mon système qui est censé faire remonter l'erreur d'apt-get qui marche pas, j'utilisais l'option -s (simulation) pour simuler un apt-get update et retourner l'erreur mais il se trouve que cette option n'est pas valide avec apt-get update.
Depuis chez Debian ils ont fait une mise à jour pour bien préciser que ça marche pas (avant il ignorait l'option) ce qui fait que ça marchait quand même.

TL;DR : J'ai foiré ma gestion des erreur apt dans le script, je vais corriger ça mais je garantis rien c'est un peu tordu.

Normalement c'est corrigé , je teste ça et je vais voir si j'ai des soucis

**Comment by marsho94** [comment]
Il m'a mis ca par la suite. J'ai fait le sudo apt-get install sqlite3 php5-sqlite et rafraichit la page mais rien ne change. Je précise qu'il a détecté la dernière version de sqlite.


 Warning: include(classes/SQLite3.class.php): failed to open stream: No such file or directory in /var/www/html/yana-server/install.php on line 16

Warning: include(): Failed opening 'classes/SQLite3.class.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/yana-server/install.php on line 16
error: Le pré-requis SQLITE3 n'est pas installé. 
Pour résoudre ce problème, merci de taper la commande suivante dans le shell sudo apt-get install sqlite3 php5-sqlite
warning: Le chemin de l'executable de wiring pi est à modifier dans classes/Gpio.class.php, remplacer /usr/local/bin/gpio par gpio: /usr/bin/gpio /usr/local/bin/gpio.

**Comment by maditnerd** [comment]
Bizarre pour sqlite3, ça doit vouloir dire que c'est installé mais pas activé dans apache2 (ce qu'il devrait faire lors de l'installation à priori

Tu peux de faire ça manuellement:
```
ln -sv /etc/php5/mods-available/sqlite3.ini /etc/php5/apache2/conf.d/20-sqlite3.ini
service apache2 restart
```

**Comment by ldleman** [comment]
Désolé pour la L211 j'ai fait un commit un peu rapide :p .
J'ai pu constater ça pour le -s, ils sont fourbes quand même chez debian ;o) 
Content de constater que mon warning sur le chemin gpio fonctionne, ça au moins ça devrait régler pas mal de pb utilisateurs.

**Comment by ldleman** [comment]
Du coup @maditnerd tu pense avoir le temps de corriger cette histoire de -s ?

**Comment by marsho94** [comment]
Bon en attendant je m'occupe de Jeedom + Sarah. 

En tout cas les gars c'est vraiment un plaisir d'apprendre avec et grâce à vous !

**Comment by maditnerd** [comment]
J'ai fait un commit qui devrait régler le problème
https://github.com/ldleman/yana-server/commit/487acf40d70ba10048a0d7aaeae88684c01ea433

Si apt-get a un problème , il devrait simuler la reprise de l'installation précédente et sortir le message d'erreur dans /tmp/aptError.log puis l'afficher.

Après pour tester si ça marche, je dois faire planter apt-get.
Du coup à part faire un CTRL-Z pendant que apt-get tourne, c'est pas évident de vérifier que ça marche.

**Comment by ldleman** [comment]
Okay, l'essentiel c'est de pas être bloqué lors de l'install quand tout vas bien :) merci pour le correctif :).

@maditnerd  rien à voir mais je te préviens au cas ou :  je vais voir pour arrêter les améliorations et me concentrer sur les gros bugs histoire de pouvoir produire une version stable sur le master et de continuer mes améliorations sur une branche trunk afin que les nouveaux utilisateurs ne soient plus bloqués a chacun de mes commits (oui j'aurais pu y penser avant ^^).

**Comment by ldleman** [comment]
@Blacksly  @marsho94  si vous pouvez nous confirmer que tout roule qu'on puisse clore ça serait top :)

**Comment by Gardaux** [comment]
Petite question pour que tout le monde comprenne bien (et surtout moi !!).
quand vous dites : 
"warning: Le chemin de l'executable de wiring pi est à modifier dans classes/Gpio.class.php, remplacer /usr/local/bin/gpio par gpio: /usr/local/bin/gpio. "
Cela veut dire que dans le fichier Gpio.class.php à la ligne 11, on remplace : 
const GPIO_DEFAULT_PATH = '/usr/local/bin/gpio';
par
const GPIO_DEFAULT_PATH = gpio: /usr/local/bin/gpio
Si oui, manque t il des caractères dans la syntaxe que j'ai écrite ou pas ?

**Comment by ldleman** [comment]
Non c'est 
`const GPIO_DEFAULT_PATH = '/usr/local/bin/gpio';`
par
`const GPIO_DEFAULT_PATH = '/usr/bin/gpio';`

En gros le chemin de l'executable wiring pi change en fct de la version ou du système, pour savoir quel est le bon chemin il suffit de taper dans le terminal ssh : 
`whereis gpio`
et de coller le chemin retourné dans la variable GPIO_DEFAULT_PATH (généralement  '/usr/bin/gpio' ou '/usr/local/bin/gpio')

Je clos le topic sans réponse de la part de @Blacksly @marsho94 n'hésitez pas a rouvrir au besoin.

**Comment by Blacksly** [comment]
hello ! 
Désolé, j'ai été pas mal occuper c'est dernier temps ^^ 
pour le probleme poser dans ce topic, tout roule parfaitement ! Cepandant mtn j'ai une erreur : 

 Impossible de continuer sans apt-get
 ERREUR - Le gestionnaire de paquet apt-get est HS
* Soit celui-ci a été interrompu
* Soit il est en cours d'utilisation par un autre programme
Supprimer le fichier de verrou est probablement la solution

Voici le message d'erreur:
 Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

après je pense que mon raspi est un peu dans le mal ... je réinstalle tout ce soir, je vous tiens au courant ! 
Autre question, est-ce qu'il y a un client que l'on peux faire tourner sur le raspi ?? merci !

**Comment by Blacksly** [comment]
Voilà, ce coup si je reviens aux nouvelles rapidement : 

Sur un système propre, aucun soucis, l’installe se passe correctement :)
