### ISSUE TITLE
ERROR  Message With "sudo git pull"

### ISSUE THREAD

**Issue by ammous** [ldleman/yana-server#288]
Bonsoir

lorsque je fais la mise à jour j'ai ce message; sachant que lorsque je lance la commande suivante"php /var/www/yana-server/socket.php" ca marche pour le serveur

est ce que il y a methode de resoudre ce message d"erreur.   merci

pi@homecontrol /var/www/yana-server $ sudo git pull
Updating a88d21b..941dbff
error: Your local changes to the following files would be overwritten by merge:
        .tool.sample.php
        apigen.neon
        apigen.phar
        classes/Action.class.php
        classes/Client.class.php
        classes/Device.class.php
        classes/Personality.class.php
        constant.php
        db.json
        doc.bat
        log/index.php
        plugins/dashboard-monitoring/css/style.css
        plugins/dashboard-monitoring/js/main.js
        plugins/dashboard/Dashboard.class.php
        plugins/dashboard/Widget.class.php
        plugins/dashboard/css/jquery.dashboard.css
        plugins/dashboard/dashboard.plugin.php
        plugins/dashboard/img/preloader.gif
        plugins/dashboard/install
        plugins/dashboard/js/main.js
        plugins/dashboard/uninstall
        plugins/domoDoor/DoorAccess.class.php
        plugins/domoDoor/DoorLog.class.php
        plugins/domoDoor/css/style.css
        plugins/domoDoor/domodoor.plugin.php
        plugins/domoDoor/i2c.py
        plugins/domoDoor/install
        plugins/domoDoor/js/main.js
        plugins/domoDoor/uninstall
        plugins/door/install
        plugins/door/uninstall
        plugins/ipcam/Camera.class.php
        plugins/ipcam/install
        plugins/ipcam/ipcam.plugin.php
        plugins/ipcam/js/main.js
        plugins/ipcam/uninstall
        plugins/modele/install
        plugins/modele/uninstall
        plugins/preference/js/main.js
        plugins/profile/css/style.css
        plugins/profile/js/main.js
        plugins/profile/profile.plugin.enabled.php
        plugins/propise/Data.class.php
        plugins/propise/Sensor.class.php
        plugins/propise/arduino.ino
        plugins/propise/install
        plugins/propise/js/main.js
        plugins/propise/propise.plugin.php
        plugins/propise/uninstall
        plugins/radioRelay/RadioRelay.class.php
        plugins/radioRelay/css/main.css
        plugins/radioRelay/install
        plugins/radioRelay/js/main.js
        plugins/radioRelay/radioEmission
        plugins/radioRelay/radioEmission.cpp
        plugins/radioRelay/radioReception
        plugins/radioRelay/radioReception.cpp
        plugins/radioRelay/uninstall
        plugins/room/install
        plugins/room/uninstall
        plugins/speechcommands/SpeechCommand.class.php
        plugins/speechcommands/cmd.json
        plugins/speechcommands/img/sample.png
        plugins/speechcommands/install
        plugins/speechcommands/js/main.js
        plugins/speechcommands/speechcommands.plugin.php
        plugins/speechcommands/uninstall
        plugins/story/Cause.class.php
        plugins/story/Effect.class.php
        plugins/story/Story.class.php
        plugins/story/css/main.css
        plugins/story/edit.php
        plugins/story/js/main.js
        plugins/story/list.php
        plugins/story/story.plugin.php
        plugins/temperature/install
        plugins/temperature/temperature.plugin.enabled.php
        plugins/temperature/uninstall
        plugins/vocal_infos/cmd.json
        plugins/vocal_infos/img/yana.jpg
        plugins/vocal_infos/install
        plugins/vocal_infos/js/main.js
        plugins/vocal_infos/uninstall
        plugins/vocal_infos/vocalinfo.plugin.php
        plugins/wireRelay/css/main.css
        plugins/wireRelay/install
        plugins/wireRelay/uninstall
        plugins/wireRelay/wireRelay.plugin.php
        plugins/wysiwyg/css/trumbowyg.css
        plugins/wysiwyg/img/icons-sa75ce98b2b.png
        plugins/wysiwyg/js/main.js
        plugins/wysiwyg/js/trumbowyg.min.js
        plugins/wysiwyg/wysiwyg.plugin.php
        socket.php
        templates/default/css/font-awesome.min.css
        templates/default/font/FontAwesome.otf
        templates/default/font/fontawesome-webfont.eot
        templates/default/font/fontawesome-webfont.svg
        templates/default/font/fontawesome-webfont.ttf
        templates/default/font/fontawesome-webfont.woff
        templates/default/js/chart.min.js
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by maditnerd** [comment]
Tu peux essayer de faire
```
git reset --hard HEAD
git pull
```
**Si tu as modifié le code de Yana par contre fait gaffe ça risque de virer tes modifications**
Mais ceci n'affectera pas les plugins/base de données (normalement) mais je te conseille de faire une sauvegarde au cas où

**Comment by ammous** [comment]
ok merci
