### ISSUE TITLE
Yana-server 3.0.6 sur raspberry pi B+

### ISSUE THREAD

**Issue by Foxies-CSTL** [ldleman/yana-server#290]
Bonjour Idleman,
D'abord bravo pour votre projet et plein de choses pour 2017!!
Me lancant dans la domotique, j'apprend à me servir des différents projets dont le votre, pour piloter la maison de ma fille à distance.
Aprés l'installation de votre serveur, celui-ci ne reconnais pas mon Rpi. voici les infos:
Raspberry pi B+ rev 1.2 (2014) avec 40 broches pour le GPIO comme code "1000010", le tout sur une Raspbian GNU/Linux 8 (jessie)/Domotics/Yana-server 3.0.8.
J'ai modifié votre System.class.php afin de le faire prendre en compte par:
> '1000010' => array('ram'=>'512','version'=>'1.2','type'=>'b+','revision'=>'1000010'),

mais il me manque quelques broches :) et aussi plus de modif dans votre fichier pour intégrer cette révision.
voilà, je reste à l'écoute pour d'autres information.
Merci.

**Comment by ldleman** [comment]
Salut Foxie et bonne année 2017 ! 

Ton pinmap de rpi à l'air similaire à la 1.0 B+, Essaye de rajouter (en
plus de ce que tu as déjà mis) 

$pins['b+1.2'] = $pins['b+1.0']; 

L 152 dans System.class.php 

Le 2017-01-01 17:23, Foxies-CSTL a écrit :

> Bonjour Idleman,
> D'abord bravo pour votre projet et plein de choses pour 2017!!
> Me lancant dans la domotique, j'apprend à me servir des différents projets dont le votre, pour piloter la maison de ma fille à distance.
> Aprés l'installation de votre serveur, celui-ci ne reconnais pas mon Rpi. voici les infos:
> Raspberry pi B+ rev 1.2 (2014) avec 40 broches pour le GPIO comme code "1000010", le tout sur une Raspbian GNU/Linux 8 (jessie)/Domotics/Yana-server 3.0.8.
> J'ai modifié votre System.class.php afin de le faire prendre en compte par:
> 
>> '1000010' => array('ram'=>'512','version'=>'1.2','type'=>'b+','revision'=>'1000010'),
> 
> mais il me manque quelques broches :) et aussi plus de modif dans votre fichier pour intégrer cette révision.
> voilà, je reste à l'écoute pour d'autres information.
> Merci. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/ldleman/yana-server/issues/290
[2]

**Comment by Foxies-CSTL** [comment]
Excellent, merci!!
