### ISSUE TITLE
DASHBOARD : bug widget reseau

### ISSUE THREAD

**Issue by zb2oby** [ldleman/yana-server#294]
hello,

après plusieurs semaines d'absence je replonge dans Yana. je reinstalle donc une image systeme contenant yana qui marchait du feu de dieu sur mon RPI. je tente une connection sur la page http et tadaa environ 4/5 minutes pour charger la page de monitoring.
les widget moulinent et ne chargent qu'apres un certains temps.
j'ai cherché partout dans ma conf et j'ai fini par trouver que le problème venait du seul widget "réseau". 

des que je supprime ce widget la page met quelques micro-seconde à s'afficher et les autre widget chargent instantanement. c'est donc lui le coupable ;-)  

Je ne voit pas d'où peut venir le probleme..un module apache  ? un blocage firewall ?(j'ai pourtant fureté de ce côté là et tout semble bon et d'ailleurs la requête fini par passer...mais c'est long quoi) un module php ? j'ai même cherché côté hardware tout fonctionne et semble comme avant.je ne voit plus..

il y à pourtant quelques semaines/mois je n'avait pas ce problème et je n'ai rien changé à la conf en réinstallant l'image système.

une idée ?

merci

**Comment by ldleman** [comment]
Salut :),
Globalement le widget réseau ne fait rien de plannant, vérifie que les commandes shells suivantes executées par le widget bne sont pas celle qui te ralentissent.
`/sbin/ifconfig eth0 | grep RX\ bytes`
et
`netstat -nta --inet | wc -l`

La cause la plus probable du ralentissement : 
Le widget fait appel a un site web externe pour récuperer ton IP (http://whatismyip.akamai.com puis http://ipecho.net/plain si le premier site est down) vérifie que ton rpi a le net et qu'il peut acceder a ces url sans lagger 10 ans ça viens probablement de là.

**Comment by zb2oby** [comment]
ouaip j'ai trouvé
c'etait bien firewall qui bloquais..
j'avais modifié le port de apache et yana pour qu'ils causent sur le 82 et plus sur le 80
du coup les sites comme http://whatismyip.akamai.com/ utilisent, eux le port 80 bien sûr. Il fallait juste autoriser les connexion sortantes sur le 80...wala...désolé du dérangement et merci de ta réponse.
