### ISSUE TITLE
RPI Inconnu, révision (900032)

### ISSUE THREAD

**Issue by ArnoStrasbourg** [ldleman/yana-server#295]
Bonjour,

J'ai ce message d'erreur : 

Votre RPI dispose d'une révision (900032) inconnue de yana, il n'est pas possible d'afficher ses pins.
Pour ajouter cette révision, merci de faire une demande sur github en précisant la révision, le nombre de pins, le modèle et la vesion de votre rpi.

J'avais déjà le souci pour lire les GPIO depuis Domoticz.

Une version exotique de mon Pi ? C'est un Pi 2;

Merci pour votre aide.

Arno.

**Comment by ldleman** [comment]
Coucou, 
peut tu mettre à jour ? Normalement c'est ajouté  :)

**Comment by ldleman** [comment]
Sans réponses de ta part je  clos le sujet, n'hésite pas a rouvrir si besoin.
