### ISSUE TITLE
problemes de permission

### ISSUE THREAD

**Issue by victor81000** [ldleman/yana-server#297]
bonjour, il semblerait que j'ai un probleme pour acceder aux dossiers de yana-server sur mon rasp.
j'ai essayé  avec chown , avec vnc...mais pas moyen, ca me met toujours accés denied.
auriez vous une solution? merci d'avance

**Comment by ldleman** [comment]
Salut victor,
Tu n'arrive pas a acceder au dossier via une requette navigateur ou via winscp (ou autre programme de ftp/scp) ? 

En ligne de commande tu as bien fait un :  
```
sudo chown -R www-data:www-data /var/www
sudo chmod -R 755 /var/www
```
Tu te logue avec quel utilisateur pour modifier les fichiers ? Avec root ? peux tu mettre un screenshot de l'erreur que je puisse t'aider ?

**Comment by victor81000** [comment]
amen! je me suis fourvoyé dans les commandes.
maintenant j'ai accés au repertoire de yana :).
je me connectais en normal et en root, mais ca me refusais l'acces, maintenant ca fonctionne 
mille mercis :)

**Comment by ldleman** [comment]
Ya pas de quoi :), bonne continuation !
