### ISSUE TITLE
YANA sur raspberry autonome 

### ISSUE THREAD

**Issue by tanou** [ldleman/yana-server#44]
Salut à tous! Je voulais savoir si quelqun avait du nouveau à propos des librairies de reconnaissance vocale à integrer au raspberry? Si il n'y a toujours pas de librairie correcte, quelle est la procedure pour utiliser google speech?
merci à vous!

**Comment by ldleman** [comment]
Petit ajout venant d'un lecteur qui a ajouté sa propse
