### ISSUE TITLE
le token impossible

### ISSUE THREAD

**Issue by Azuroca** [ldleman/yana-server#47]
14/02/2014 18:53:34 Chargement des configurations...
14/02/2014 18:53:34 Url API : http://192.168.1.35/yana-server/action.php
14/02/2014 18:53:34 Interval de vérification : 5 secondes
14/02/2014 18:53:34 Dossier son : sons/
14/02/2014 18:53:34 Lancement au démarrage : False
14/02/2014 18:53:34 Fichier d'erreur : error.log
14/02/2014 18:53:34 Voix utilisée : ScanSoft Virginie_Dri40_16kHz
14/02/2014 18:53:34 Voix - emphase : 0
14/02/2014 18:53:34 Voix - volume : 0
14/02/2014 18:53:34 Voix - vitesse : 0
14/02/2014 18:53:34 Initialisation du timer
14/02/2014 18:53:34 Lancement du timer dans 5 secondes
14/02/2014 18:53:35 Récuperation des configurations distantes...http://192.168.1.35/yana-server/action.php?action=GET_SPEECH_COMMAND
14/02/2014 18:53:35 Reponse :{"error":"invalid or missing token"}
14/02/2014 18:53:35Lancement de la reconnaissance...

Salut a tous, voila mon historique lors du lancement de YANA windows . Les commandes de base ne fonctionnent pas, meme apres plusieurs réinstallation. Le token est bien sur le meme ^^

Need help ..

**Comment by agentcobra** [comment]
bonsoir,
j'ai le même problème sur android et sur windows, il me dis que mon token n'est pas valide mais quand j'appel l'url manuelement avec le token, j'ai bien une réponse JSON

**Comment by oxy-flo** [comment]
Bonjour ,
J'ai le meme probleme que agentcobra sur android et windows , mon token n'est pas valide , j'ai essayer la solution de maditnerd (plusieur fois meme ) mais mon token ne change pas , 
quand tu dit se déconnecter de Yana tu parle d'avoir les appli fermer et de lancer la commande  "cd" ?

résultat du test : 
url test : http://192.168.1.57/yana-server/action.php?action=GET_SPEECH_COMMAND&token=0a78dc90dcbe46e119a9a85ed73ebcb8f751ef3c

réponse de la page : 

{"commands":[{"command":"YANA quelle heure est il","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_hour","confidence":0.88},{"command":"YANA on est le combien","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_day","confidence":0.88},{"command":"YANA quel temps fait-il","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_meteo&today=1","confidence":0.88},{"command":"YANA m\u00e9t\u00e9o semaine","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_meteo","confidence":0.88},{"command":"YANA ya quoi comme s\u00e9rie a la t\u00e9l\u00e9e","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_tv&category=S\u00e9rie","confidence":0.88},{"command":"YANA ya quoi comme documentaire a la t\u00e9l\u00e9e","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_tv&category=Documentaire","confidence":0.88},{"command":"YANA ya quoi comme com\u00e9die a la t\u00e9l\u00e9e","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_tv&category=Com\u00e9die","confidence":0.88},{"command":"YANA concours de pet","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_sound&sound=pet.wav","confidence":0.88},{"command":"YANA mode d\u00e9veloppement","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_devmod","confidence":0.88},{"command":"YANA concours de rot","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_sound&sound=rot.wav","confidence":0.88},{"command":"YANA fait la poule","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_sound&sound=poule.wav","confidence":0.88},{"command":"YANA liste des commandes","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_commands","confidence":0.88},{"command":"YANA diagnostique des G.P.I.O","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_gpio_diag","confidence":0.88},{"command":"YANA wikipedia exemple","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_wikipedia&word=exemple","confidence":0.7},{"command":"YANA comment vas-tu","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=vocalinfo_mood","confidence":0.88},{"command":"YANA dis bonjour","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=speechcommands_execute&command=1","confidence":0.8},{"command":"YANA, Allume le salon","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=1&state=1","confidence":0.9},{"command":"YANA, Eteinds le salon","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=1&state=0","confidence":0.9},{"command":"YANA, Allume la t\u00e9l\u00e9","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=2&state=1","confidence":0.9},{"command":"YANA, Eteinds la t\u00e9l\u00e9","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=2&state=0","confidence":0.9},{"command":"YANA, Ouvre les stores","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=3&state=1","confidence":0.9},{"command":"YANA, Ferme les stores","url":"http:\/\/192.168.1.57:80\/yana-server\/action.php?action=wireRelay_vocal_change_state&engine=3&state=0","confidence":0.9}]}
