### ISSUE TITLE
Problèmes YANA windows

### ISSUE THREAD

**Issue by Maxvi33** [ldleman/yana-server#71]
Bonjour tout le monde,
Le fonctionnement de YANA à marché chez moi une trentaines de secondes, j'ai pu lui demander l'heure et de faire un concours de pet (hihihih) mais après cela il me dit soit:
"08/04/2014 19:07:18 Yana quelle heure est il - reconnue à 0,8255241 sur 0,9 : Invalidée (En savoir plus) "

"08/04/2014 18:59:30 | <!> ERREUR: Timeout sur l'url :http://192.168.x.xx/yana-server/action.php?action=GET_EVENT&token=65b5e66cea882a47545cf4852ed5070ffe8629a9 (url invalide ou yana-server inactif)
08/04/2014 18:59:30 | <!> ERREUR: La demande a été abandonnée : La demande a été annulée.
 L: 0 |    à System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   à YANA.Control.receive(IAsyncResult result)"

(x.xx) correspond bien à mon adresse ip :)
ensuite cette erreure apparaît:

"
"************** Texte de l'exception **************
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'DebugWindow'.
   à System.Windows.Forms.Control.CreateHandle()
   à System.Windows.Forms.Form.CreateHandle()
   à System.Windows.Forms.Control.get_Handle()
   à System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   à System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   à System.Windows.Forms.Control.Show()
   à YANA.MainWindow.logsButton_Click(Object sender, HtmlElementEventArgs e)
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Delegate.DynamicInvokeImpl(Object[] args)
   à System.Windows.Forms.HtmlShim.FireEvent(Object key, EventArgs e)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.18444 built by: FX451RTMGDR
    CodeBase :file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
YANA
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Maxime/Documents/Raspberry_PI/ProjetYana/yana-windows/YANA.exe
----------------------------------------etc etc "

Si vous avez déjà rencontré cette erreur, je serais heureux de savoir la solution car je bug un petit peu la dessus..

Amicalement,
Maxime

**Comment by Huhra** [comment]
Bonjour Idleman,
Je suis développeur C# frontend/backend, est-ce que ça pourrait t’intéresser que je refactor la version C# de ton client pour passer à du WPF et rajouter un peu de modularité au client pour permettre une API aussi côté client ou tu as trop avancé dans la version C++ pour que ce soit utile ?
Merci en tout cas c'est top ce que tu fais :)

**Comment by ldleman** [comment]
Salut Huhra !! 

Merci pour ta proposition d'aide !! 

J'ai effectivement pas mal avancé sur la version C++, il ne reste qu'un
problème d'encodage a régler (l'encodage : ma némésis) et je devrais
pouvoir sortir la version beta pour windows. 

Ma contre si tu as quelques compétences en C++ c'est avec plaisir que
j'accepte ton aide :) 

Amicalement, 

idle 

Le 22.03.2015 15:52, Huhra a écrit : 

> Bonjour Idleman,
> Je suis développeur C# frontend/backend, est-ce que ça pourrait t'intéresser que je refactor la version C# de ton client pour passer à du WPF et rajouter un peu de modularité au client pour permettre une API aussi côté client ou tu as trop avancé dans la version C++ pour que ce soit utile ?
> Merci en tout cas c'est top ce que tu fais :) 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/ldleman/yana-server/issues/71#issuecomment-84625201

**Comment by Huhra** [comment]
Salut,

Objectivement je ne serais jamais aussi efficace en C++ que je ne le suis en C# mais je devrais pouvoir t'aider sans soucis. Il y a un autre repository pour la version C++ ?

**Comment by ldleman** [comment]
Non elle est encore en mode privé ^^, mais ça peux se faire si tu donne
un coup de pattes :). 

Envoie moi ton mail si t'es chaud je te ferais un résumé des avancées. 

Le 01.04.2015 13:17, Huhra a écrit : 

> Salut, 
> 
> Objectivement je ne serais jamais aussi efficace en C++ que je ne le suis en C# mais je devrais pouvoir t'aider sans soucis. Il y a un autre repository pour la version C++ ? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/ldleman/yana-server/issues/71#issuecomment-88444467

**Comment by Huhra** [comment]
mon email: etiennemagreault@gmail.com

Le 1 avril 2015 13:25, Idleman <notifications@github.com> a écrit :

>
>
> Non elle est encore en mode privé ^^, mais ça peux se faire si tu donne
> un coup de pattes :).
>
> Envoie moi ton mail si t'es chaud je te ferais un résumé des avancées.
>
> Le 01.04.2015 13:17, Huhra a écrit :
>
> > Salut,
> >
> > Objectivement je ne serais jamais aussi efficace en C++ que je ne le
> suis en C# mais je devrais pouvoir t'aider sans soucis. Il y a un autre
> repository pour la version C++ ?
> >
> > --
> > Reply to this email directly or view it on GitHub [1].
>
>
>
> Links:
> ------
> [1]
> https://github.com/ldleman/yana-server/issues/71#issuecomment-88444467
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ldleman/yana-server/issues/71#issuecomment-88445669>.
>



-- 
Etienne Magréault

Développeur logiciel chez Genetec

Promotion Epitech 2012
European Institute of Information Technology

etiennemagreault@gmail.com
Portable : +33 6 89 63 49 95
