### ISSUE TITLE
Module pour streamer la camera pi 

### ISSUE THREAD

**Issue by F0cks** [ldleman/yana-server#80]
Peut être un truc sympa à faire:
https://www.youtube.com/watch?v=SjEZ4y0vIUE

On pourrait créer un module pour afficher dans un onglet ou un bloc dans une fenetre ce qui se passe dans un pièce sans faire un screen capture.

Si quelqu'un se sent apte à monter ça... :D

**Comment by victor81000** [comment]
bonjour, je deterre le sujet parce que l'installation de stream pi me pose un probleme:
outre le fait que je n'arrive pas a voir l'image de la camera ( pourtant visible avec le pluggin camera), il me fait planter le socket, qui du coup ,ne veut plus demarrer ni s'installer ( en lancant une verification, ca me marque que l'adresse est deja utilisée) j, du coup plus de commande vocale sur yana4all...je suis obligé de reinstaller yana pour que tout remarche.
vous avez une idée du bug? help....
