### ISSUE TITLE
GPIO : pourquoi seulement 22 pins ?

### ISSUE THREAD

**Issue by thib3113** [ldleman/yana-server#96]
Bonjour, sur le widget gpio, il n'y à que 22 pins .
Le nombre de pins serais t'il écris en dur et n'aurais pas eu la mise à jour pour le raspberry b+ ?

Je vais farfouiller dans le code ce soir pour voir ce que je peux faire :)

**Comment by vouvrat** [comment]
Hello, désoler je réouvre cet issue mais j'ai toujours ce problème. 22 pins d'afficher sur les 40 dispo.

Pour info, je possède un raspi 2. je n'arrive pas à résoudre le problème malgré les différentes issue remonter.

**Comment by thib3113** [comment]
Car quand j'ai fais le code, le pi 2 n'étais pas sortie, et je ne sais pas si mon code avais était incorporé

**Comment by vouvrat** [comment]
Du coup maintenant c'est valable ou pas? car à partir du Pi B+ on est passez sur du 40 pins :s

**Comment by thib3113** [comment]
Oui, donc faudrait mettre a jour ... Soit en Mettant jour ma solution, soit
en faisant de l'automatique

**Comment by vouvrat** [comment]
Bonjour, bon j'ai fais des updates, Mais je n'ai pas plus de GPIO afficher sur l'interface. :s As tu une procédure pour cela? Désoler je débarque dans le monde du rasp et git.
