### ISSUE TITLE
Impossible d'installer YANA-Server avec git.

### ISSUE THREAD

**Issue by vouvrat** [ldleman/yana-server#99]
Bonjour,

J'essai d'installer YANA-Server sur un Rpi avec Qemu en lançant la commande suivante:

sudo apt-get install git-core && sudo apt-get install sqlite3 && sudo apt-get install php5-sqlite && cd /var/www/ && sudo git clone https://github.com/ldleman/yana-server.git /var/www/yana-server && sudo chown -R www-data:www-data yana-server && sudo chown root:www-data /var/www/yana-server/plugins/relay/radioEmission && sudo chmod +s /var/www/yana-server/plugins/relay/radioEmission

Le début ce passe bien mais une fois que l'on arrive à sudo git clone https://github.com/ldleman/yana-server.git /var/www/yana-server sa comment à Dl plus rien... Je stop la commande et la relance seul et la on me demande de m'authentifier. Je met mon compte github mais rien...

Quelqu'un à déjà rencontrer ce problème?

**Comment by ingfred** [comment]
Pour info c'est cela qui pose pb, la cle SSH, en tout cas pour moi.Merci à thib3113

**Comment by vouvrat** [comment]
Bonjour à tous, désoler pour le temps de réponse. Je viens fermer ce ticket car cela fonctionne correctement maintenant depuis l'achat de mon pi2 je viens juste de faire l'installation et aucun problème.
